import json,re,textwrap
from pathlib import Path
root=Path('.')
rows=json.loads(Path('work/dialogue-review-20260909/main-dialogue.json').read_text())
D={
14:"You don't need Incense to get baby POKéMON from compatible parents.\n\nSome Incenses have effects in battle, though. The CENTER vendors can help you find them.",
101:"WALLY: Aww, UNCLE, please?\n\nI feel so much better since moving to VERDANTURF. RALTS and I have been practicing every day!",
103:"WALLY: We've made new friends, too! I want to see how far we can go together.",
104:"WALLY: Oh! Hi, {PLAYER}!\n\nDo you remember helping me catch RALTS? We've come a long way since then.\n\nPlease, will you battle me? I want to show my UNCLE I'm ready.",
105:"WALLY: Oh… All right. I was hoping you could help me show him.",
108:"WALLY: Thank you, {PLAYER}!\n\nAll right, everyone. Let's show them what we can do!",
109:"WALLY: I… I lost.\n\nI really thought we were ready…",
110:"WALLY: UNCLE… I'll go back to VERDANTURF.\n\nBut I don't want to give up. RALTS and I still have so much to learn.",
187:"Some POKéMON evolve when you trade them.\n\nA LINKING CORD lets you evolve those partners yourself, too. Ask a CENTER vendor about evolution items!",
197:"MAY: {PLAYER}{KUN}! Are you shopping, too?\n\nI was looking for a gift for Dad, but I keep finding things I want!\n\nIt's been ages since our last battle. Want to show me your team?",
198:"MAY: Another time, then! I'll be here trying to choose a present.",
199:"MAY: Ready for a battle? I've met some wonderful POKéMON since ROUTE 119!",
200:"MAY: All right! Everyone, let's give it our best!",
206:"BRENDAN: {PLAYER}! Running an errand for Dad. No, I'm not buying DOLLS!\n\nIt's been a while since ROUTE 119. Got time for a battle?",
207:"BRENDAN: Got other plans? Fair enough. Come find me when you're ready!",
208:"BRENDAN: How about that battle? I've been looking forward to it!",
212:"BRENDAN: What's next, {PLAYER}? The rest of the BADGES, then the LEAGUE?\n\nMaybe I'll try that, too. But first, Dad's waiting for these supplies.\n\nDon't get too far ahead of me!",
268:"SCOTT: {PLAYER}{KUN}! I came to watch the GYM, but everyone's worried about a threat to the SPACE CENTER.\n\nSTEVEN is looking into it. I hope those researchers are safe.",
303:"MAXIE: GROUDON, stop!\n\nI wanted more land for people and POKéMON to live on. You're burning the homes they already have!",
304:"MAXIE: The heat is fading… RAYQUAZA stopped them.\n\nI was so certain more land would help HOENN. I wouldn't listen to anyone who questioned me.\n\nLook what that certainty nearly cost us.",
306:"ARCHIE: The rain's stopped. People can come out again.\n\nI said I was protecting sea POKéMON. I nearly washed away every home along this coast.\n\nWe have to return the ORBS, MAXIE.",
308:"STEVEN: I understand why people are frightened. Neither leader could control the POKéMON they awakened.\n\nBut POKéMON have helped us through this, too. We must find a way to stop the fighting.",
312:"STEVEN: So that's RAYQUAZA…\n\nJust as the old tale said, it stopped their clash. You reached it in time, {PLAYER}.",
315:"WALLACE: MAXIE and ARCHIE are still here. They owe you an explanation.\n\nReturning the ORBS will be a start. There is much more for them to put right.",
316:"WALLACE: You crossed HOENN to stop this disaster, then climbed SKY PILLAR when we needed you most.\n\nThank you, {PLAYER}{KUN}. SOOTOPOLIS is safe again. Please accept this.",
318:"WALLACE: JUAN, my mentor, leads this city's GYM. His BADGE is the last you need for the LEAGUE.\n\nYou've helped our city through so much. I look forward to seeing how far your journey takes you.",
324:"MOM: {PLAYER}! Did you meet PROF. BIRCH?\n\nOh! Look at your two new friends! You're setting off together? How lovely!\n\nYour father will be so proud. Here, honey, take these RUNNING SHOES.\n\nThey'll put a zip in your step!",
344:"A POTION can help an injured partner while you're exploring.\n\nYou can't use your BAG during TRAINER battles, so patch everyone up before a challenge!",
352:"There's a meadow west of town. Lately, travelers have spotted some very unusual POKéMON there.\n\nThe old manor holds records of MEGA EVOLUTION. Someone must have studied it here long ago.",
431:"MAY: The partner you left with Dad has joined my team!\n\nI've been so excited to introduce everyone. Ready for our DOUBLE BATTLE?",
435:"BRENDAN: I took the partner you left with Dad. We're getting along great!\n\nLet's see how your team and mine measure up. DOUBLE BATTLE. Ready?",
451:"MAY: {PLAYER}{KUN}! I've been finding new POKéMON all the way from OLDALE.\n\nYou must have met some, too! Let's have a battle and introduce them!",
452:"Wow! You've gotten stronger!",
459:"BRENDAN: Hey, {PLAYER}! Figured you'd come this way.\n\nI've been looking forward to another battle. Let's see how far we've come!",
460:"Hah… You've been busy, too!",
495:"MAY: {PLAYER}{KUN}! There you are!\n\nI keep stopping to take notes, and then the rain washes them away!\n\nA battle will cheer us up. Ready?",
496:"Whew! That was worth getting soaked for!",
498:"MAY: Your FLIGHT BEACON works once you earn the FEATHER BADGE from WINONA in FORTREE.\n\nFollow this road north! Then use the beacon from your BAG to fly to towns you've visited.\n\nStop by home sometime. Your mom would love to see you!",
501:"BRENDAN: {PLAYER}! I wondered when you'd catch up.\n\nA little rain hasn't stopped us practicing. Come on, let's battle!",
503:"BRENDAN: I knew you'd give us a good battle. Here, take this!",
575:"{RIVAL} is studying POKéMON on ROUTE 103. Why not introduce your new partners?\n\nOLDALE's CENTER can help you prepare. Its free LEVELER brings your POKéMON up to the current training limit.\n\nWould you like to go find {RIVAL}?",
595:"PROF. BIRCH: {PLAYER}{KUN}, {RIVAL}, you've both brought back so many field notes!\n\nYour POKéDEX units could record every region from the start. Let's add our latest observations to both.\n\nMay I see them for a moment?",
603:"PROF. BIRCH: Every known HOENN species! What a remarkable record of your journey.\n\nI've kept a spare set of our legendary form tools here. Take any you're missing!\n\nThey're also in the CENTER vendors' Evolution Items archive. Your MEGA RING gives you access there.",
605:"The tools let KYUREM, ZYGARDE, NECROZMA, and CALYREX change forms or combine with certain partners.\n\nThere's always something new to learn about POKéMON!",
788:"DAD: Four BADGES already… I still remember you setting out from LITTLEROOT.\n\nI'm proud of you, {PLAYER}. But here in the GYM, I have to give every challenger my best.\n\nShow me how far you and your POKéMON have come!",
915:'“THE FERRY S.S. TIDAL”\n\n“A scale replica of the vessel designed at STERN\'S SHIPYARD.”',
919:"The ferry opens to TRAINERS with six BADGES. Come back with the FEATHER BADGE!",
921:"You'll need a ferry pass. With six BADGES, speak to the sailor at LILYCOVE HARBOR. He can register yours.",
953:"Send electricity, and LANTURN drinks it. Send water, and HELIOLISK drinks that.\n\nWhat else can your partners do?",
979:"One of our researchers was robbed of an important parcel. I hope he's all right.",
981:"That parcel holds instruments for CAPT. STERN's research.\n\nWho would go to so much trouble to steal them? They must know what the captain is studying.",
984:"After that robbery, we're being much more careful with our research deliveries.",
1087:"The man next door gave me CUT!\n\nWith the STONE BADGE and a compatible partner, I can clear skinny trees. It doesn't take up a battle move slot.",
1160:"I am WINONA, FORTREE's GYM LEADER.\n\nMy POKéMON and I have flown through clear skies and sudden storms. We know how quickly the wind can turn.\n\nShow me how your team meets a changing sky!",
1161:"You've carried your team through our strongest winds. The FEATHER BADGE is yours.",
1167:"WINONA: A strong wind can carry you far, but you must choose where to go.\n\nTo follow AQUA to MT. PYRE, head east through ROUTES 120 and 121, then SURF south on ROUTE 122.\n\nI hope the people there are safe.",
1174:"WINONA: A strong wind can carry you far, but you must choose where to go.\n\nMay your journey bring you clear skies.",
1205:"The ferry opens to TRAINERS with six BADGES. Come back with the FEATHER BADGE!",
1207:"You'll need a ferry pass. With six BADGES, speak to the sailor here in LILYCOVE HARBOR. He can register yours.",
1218:"I've received two sightings: red LATIAS and blue LATIOS!\n\nOne will travel HOENN's routes. The other waits on SOUTHERN ISLAND.\n\nWhich mainland lead shall we follow: red or blue?",
1243:"METAGROSS is tough to break through, and MIMIKYU hides behind its DISGUISE.\n\nCan you get past both of them?",
1255:"LATIOS is quick, and AEGISLASH can make a careless attack costly.\n\nChoose your moment!",
1259:"TATE: We grew up battling together.\nLIZA: We know when to help each other.\n\nTATE: Psychic Terrain protects grounded partners from priority moves.\n\nLIZA: And under TRICK ROOM…\nTATE: …the slowest may move first!\n\nBOTH: Ready to face us?",
1276:"We were preparing for a launch when MAGMA arrived.\n\nThe crew needs that fuel. We can't let them take it!",
1277:"We'd completed launch no. {STR_VAR_1} safely. Then TEAM MAGMA arrived.\n\nI can't believe they're trying to steal our fuel!",
1279:"Those MAGMA thugs have threatened the SPACE CENTER.\n\nWe're securing the rocket fuel. If they take it, they could do terrible damage.",
1282:"TEAM MAGMA mustn't get that fuel!\n\nI found this SUN STONE on the beach. If it can help one of your POKéMON, please take it.",
1308:"You'll have to battle all three of us, one after another!\n\nStill want to come through?",
1309:"That's right. Go downstairs while you can!",
1310:"I'm first! You're not getting past this corridor!",
1311:"What?! It's your turn. Stop that kid!",
1312:"You beat one of us. Let's see you beat two!",
1313:"Oh, no… It's all up to you now!",
1314:"I'm the last one! MAXIE's counting on me!",
1315:"All three of us… defeated!",
1316:"Three of us guarding one corridor. I thought this would be an easy job.",
1317:"I can't believe you beat us all. What do I tell MAXIE?",
1318:"We were supposed to keep everyone downstairs until MAXIE had the fuel.",
1319:"The others couldn't stop you? Then we will!\n\nMAXIE isn't leaving without that fuel.",
1320:"MAXIE: You again? STEVEN is already wasting my time. Stand aside!",
1323:"STEVEN: {PLAYER}! Help me stop them.\n\nAre you ready to battle alongside me?",
1326:"I couldn't keep you away…",
1327:"TABITHA: MAXIE needs that rocket fuel. My orders are to keep everyone else away!",
1328:"TABITHA: You beat me, but MAXIE won't leave empty-handed. STEVEN is still trying to stop him.",
1330:"COURTNEY: Defeated… Both of us.",
1331:"COURTNEY: STEVEN… and you.\n\nMAXIE, I'll cover you. We still need that fuel.",
1332:"MAXIE: We couldn't control GROUDON. So I came here to take fuel and force an eruption anyway.\n\nI nearly destroyed the very land I claimed to protect.\n\nIf I was this wrong… ARCHIE may be making the same mistake at sea.",
1333:"MAXIE: Keep the fuel. We're leaving.\n\nI must find GROUDON, and stop ARCHIE before he awakens KYOGRE.",
1334:"STEVEN: Thank you, {PLAYER}. Together, we kept the staff and their research safe.\n\nCome to my home west of the GYM. I have DIVE for you.\n\nYou'll need it to follow AQUA's stolen submarine.",
1337:"I am JUAN, WALLACE's mentor and SOOTOPOLIS's GYM LEADER.\n\nYou have done our city a great service. Now let us meet as TRAINERS.\n\nMy partners thrive in rain. Each brings a different strength to our performance. Shall we begin?",
1382:"Many families are sheltering indoors until the weather settles.\n\nI'd rather stay here, too. That clash outside is frightening.",
1393:"MT. PYRE… I once visited its summit and saw the two ORBS in the elders' care.\n\nHave you heard their story?",
1394:"The elders said those ORBS were passed down for generations.\n\nI still remember how carefully they watched over them.",
1395:"The elders at MT. PYRE can tell you. They've kept HOENN's old stories alive for so long.",
1447:"What a wonderful team! My grandmother would love to meet your POKéMON.",
1451:"DRAKE waits ahead. He's sailed through many storms with his DRAGON POKéMON.\n\nYou have earned his full attention.",
1455:"WALLACE: Welcome, {PLAYER}.\n\nWhen we met in SOOTOPOLIS, HOENN needed your courage. Today, you've come here to pursue your own dream.\n\nEight BADGES. The ELITE FOUR. You and your partners have earned this challenge.\n\nI am WALLACE, HOENN's CHAMPION. I will give you everything I have!",
1457:"WALLACE: This victory belongs to you and the partners who brought you here.\n\nAll the roads you traveled, all the people and POKéMON you met… They brought you to this moment.\n\nI proclaim you the new HOENN CHAMPION!",
1462:"BIRCH: You did it, {PLAYER}!\n\nIt seems like yesterday you and those two POKéMON rescued me on ROUTE 101. Now look at you!\n\nMay I see your POKéDEX? I'd love to see the record of your journey.",
1463:"BIRCH: Congratulations, {PLAYER}! Your parents will be so proud.\n\nAnd thank you, all of you POKéMON, for looking after our new CHAMPION!",
1466:"MAY: Aww… I wanted to come, too!\n\nHehe! Go on, {PLAYER}{KUN}. This is your moment.\n\nI'm so happy for you. Congratulations!",
1467:"BRENDAN: What?! I wanted to see it!\n\nAll right, all right. You earned this, {PLAYER}.\n\nWay to go! I'll tell Dad every detail when we get home.",
1475:"SCOTT: {PLAYER}{KUN}! You've made it to the POKéMON LEAGUE!\n\nI knew you were one to watch. Now you've got a shot at the championship!\n\nI'll be cheering for you. Give them a battle they'll remember!",
1478:"COURTNEY: You helped AQUA at the volcano's approach. Now you're here.\n\nNo… You won't reach MAXIE. I'll stop you.",
1479:"COURTNEY: You broke through…",
1480:"We lost, even here?!",
1483:"ARCHIE: We met at SLATEPORT's MUSEUM. {PLAYER}, wasn't it?\n\nYou stopped my crew there. But we both know what MAGMA is planning now.\n\nIf MAXIE sets off MT. CHIMNEY, the lava could destroy habitats all the way to the coast.\n\nWe're going after him. You can help, if you mean to stop that eruption.",
1485:"ARCHIE: Right! No time to waste. Get to MT. CHIMNEY before MAXIE starts that machine!",
1486:"ARCHIE: ROUTE 112's cable car leads to the summit. We'll see you there, {PLAYER}!",
1493:"I don't have a matching Mega Stone for your original partners here.\n\nKeep exploring. Other members of your team may be able to Mega Evolve, too!",
1494:"The RING lets your partners use Mega Stones you find across HOENN. Look off the path, and talk to people you meet!\n\nIt also opens the CENTER vendors' free Evolution Items archive. Legendary form tools are there, too.",
1528:"It's a TART APPLE. Use it on APPLIN to evolve it into FLAPPLE.\n\nFunny how the same POKéMON can grow differently depending on its favorite treat!",
1533:"You stopped my team… How?!",
1534:"MAXIE: You've stopped this machine. But MAGMA's work will continue.\n\nThere is a greater power beneath HOENN. We will find a way to awaken it.",
1535:"TABITHA: So you followed us from METEOR FALLS!\n\nMAXIE is working with the METEORITE. I'm not letting you near his machine!",
1536:"I couldn't hold you off!",
1537:"TABITHA: MAXIE! The intruder is coming!",
1539:"I couldn't protect the machine…",
1541:"LAVARIDGE sits beside a volcano. Imagine if we could make all that land safe!\n\nThat's what MAXIE promised us. I'm not letting you stop him!",
1542:"Even with all our training…",
1543:"I thought this would make people feel safer. Why are they all so frightened?",
1544:"Those AQUA grunts keep trying to reach our machine!",
1546:"Stand back! MAXIE is working at the crater!",
1547:"MAGMA wants more land. AQUA wants more sea.\n\nAnd neither side is giving way today!",
1549:"More land means more places to live! That's why we're here!",
1553:"ARCHIE: You stopped him. I owe you that.\n\nThe sea POKéMON along this coast can breathe easy. But AQUA's work isn't finished.\n\nJAGGED PASS leads down to LAVARIDGE. You've earned a rest.\n\nAnd that METEORITE is still in the machine. COZMO in FALLARBOR will want it back.",
1554:"MAGMA outnumbers us! We can't get through to the machine!",
1555:"If lava pours into the sea, what happens to the POKéMON living there?",
1556:"We joined AQUA to protect the sea. We can't let MAGMA destroy it!",
1562:"A METEORITE is fitted into the machine. Cables run from it toward the crater.",
1567:"{DOWN_ARROW} JAGGED PASS\nLAVARIDGE TOWN AHEAD",
1603:"MATT: Hey, I know you! ARCHIE said you'd turn up again.\n\nHe needs more time at the summit. So you get to battle me!",
1604:"You're tougher than I expected!",
1606:"MAGMA got here first. We're not letting them take both ORBS!\n\nAnd you're not getting through, either!",
1607:"You got past me, too…",
1608:"ARCHIE's farther up. The others will stop you!",
1609:"We came all this way for the RED ORB. Don't think we're leaving without it!",
1610:"That wasn't supposed to happen!",
1611:"Why do you keep following us? MAGMA is the one you should be stopping!",
1612:"You helped stop MAGMA at MT. CHIMNEY. So why are you fighting us now?\n\nFine! I'll stop you myself!",
1613:"You're really not on our side…",
1615:"You again?! Do you ever get tired of chasing TEAM AQUA?\n\nI'm putting an end to it!",
1616:"Not again!",
1617:"ARCHIE will know what to do. He has to.",
1624:"Both GROUDON and KYOGRE are awake? Then we are all in danger.\n\nThe ORBS are part of their ancient bond. They are no guarantee of obedience.\n\nOnly RAYQUAZA stopped their last clash. You must find someone who knows where it rests.",
1625:"The two men returned the ORBS themselves. They finally saw what their plans would do to HOENN.\n\nI am glad they came back. But repairing the harm will take more than returning what they stole.",
1631:"Our old tale tells how RAYQUAZA stopped a terrible clash. Now we have seen it happen again.\n\nWill you hear what people are saying about SOOTOPOLIS?",
1636:"ARCHIE: Look at it, {PLAYER}. KYOGRE! The POKéMON that made the sea.\n\nWith its power, the ocean can grow. Sea POKéMON will have all the space they need!",
1637:"You've chased us this far. But I won't let you stop us now!\n\nThis dream means everything to TEAM AQUA!",
1638:"No… Not after coming so far!",
1643:"ARCHIE: Heavy rain? Good! KYOGRE is expanding the sea!\n\nWhat? The routes are flooding? Our own crews are trapped?\n\nTell them to get to high ground! How can the rain still be getting worse?",
1644:"ARCHIE: The RED ORB woke KYOGRE. Why won't it answer me now?\n\nI never wanted people to get hurt…",
1645:"MAXIE: ARCHIE! KYOGRE's rain is spreading, and GROUDON's heat is getting worse.\n\nIf they meet, the people and POKéMON of HOENN will be caught between them!",
1646:"ARCHIE: You're the one who woke GROUDON!\n\nI thought the ORB would let me control KYOGRE. But it's not listening. Neither of them is!",
1647:"MAXIE: We can argue later! We need to get everyone out of this cavern.\n\nCome and see what's happening outside, ARCHIE. We have to stop it.",
1650:"WALLACE: Where might a POKéMON of the sky rest?\n\nHave you heard of any place on your travels that could shelter RAYQUAZA?",
1651:"WALLACE: We've searched the CAVE OF ORIGIN. There is no sign of RAYQUAZA here.\n\nPerhaps somewhere higher, closer to the sky?",
1652:"WALLACE: The elders at MT. PYRE told me RAYQUAZA's story, but it doesn't rest there.\n\nPerhaps another place high above the sea?",
1653:"WALLACE: There is an old tower called SKY PILLAR, near ROUTE 131. It reaches high above the sea.\n\nCould that be the place we're looking for?",
1661:"COURTNEY: You reached the chamber.\n\nMAXIE must not be interrupted. I will stop you here.",
1662:"COURTNEY: Defeated… Again.",
1663:"COURTNEY: MAXIE is just ahead.\n\nGROUDON… What will it do when it wakes?",
1665:"MAXIE promised solid ground under every home in HOENN. I believe him.\n\nYou're not getting into that chamber!",
1666:"You beat my whole team…",
1667:"None of us have seen GROUDON. MAXIE keeps the last chamber closed.\n\nThe mountain's shaking. I hope he knows what he's doing.",
1668:"Can you feel the mountain shaking? That's GROUDON's power!\n\nMAXIE's waited years for this. I won't let you spoil it!",
1669:"I couldn't stop you…",
1671:"This is the last chamber. GROUDON is just beyond us.\n\nYou want to stop MAXIE? You'll have to get past me!",
1672:"My team couldn't hold you back…",
1673:"That tremor… Was it stronger than the last one?",
1674:"TABITHA: You've made it through the entire hideout. I should have expected it.\n\nMAXIE is with GROUDON. This is the moment we've worked for.\n\nI'm not letting you take it from us!",
1675:"Even here, I couldn't defeat you…",
1676:"TABITHA: MAXIE is just ahead.\n\nThe shaking keeps getting worse. What is happening in there?",
1678:"MAXIE: GROUDON! What's wrong? The BLUE ORB was supposed to awaken you!\n\nWait! Where are you going?",
1679:"MAXIE: You! Did you see that? GROUDON left without a single command.\n\nDon't look at me like that. You won't stop TEAM MAGMA!",
1681:"MAXIE: GROUDON is loose. I have to find out why the ORB failed to control it.\n\nARCHIE still has the RED ORB. He'll need STERN's submarine to reach KYOGRE on the seafloor.\n\nGo warn CAPT. STERN at the harbor in northeast SLATEPORT.\n\nI'm going after GROUDON.",
1682:"These maps show storms all over HOENN. ARCHIE wants to know where they begin.\n\nHe'll get his answers. You're not getting upstairs!",
1683:"I couldn't keep you out…",
1685:"You crossed all that rain to get here? Should've stayed where it was dry!\n\nNow you've got TEAM AQUA to deal with!",
1686:"So much for scaring you off…",
1687:"There's a bed over there. You might want to rest.\n\nSHELLY's upstairs with the researchers. She's tougher than I am.",
1694:"The researchers say CASTFORM changes with the weather. ARCHIE wants to know why!\n\nYou can't go into the research wing!",
1695:"I couldn't stop you…",
1697:"Weather records, rare POKéMON… This place has everything ARCHIE asked for!\n\nYou're not taking it away from us!",
1698:"But I was guarding the records…",
1699:"We've watched strange storms gather out at sea. ARCHIE says these records will tell us what they mean.",
1700:"What are you after? The records? The weather POKéMON?\n\nWhatever it is, TEAM AQUA got here first!",
1701:"I couldn't hold my post…",
1702:"The storm records led us to old stories about MT. PYRE. ARCHIE thinks its ORBS are the key.",
1703:"SHELLY: We came for weather records. They show something powerful stirring in the ocean.\n\nYou should have stayed out of this, {PLAYER}. I'm not letting you interfere with ARCHIE's work!",
1704:"You've beaten us here, too…",
1705:"SHELLY: You're as persistent as ARCHIE said.\n\nWe have what we need. These records point to MT. PYRE.",
1707:"What?! MAGMA is heading for the BLUE ORB?\n\nSHELLY: Then we can't waste another moment here. AQUA! To MT. PYRE!",
1708:"You saved us, and our research. Thank you!\n\nThis CASTFORM has helped us study the weather. I think it would enjoy traveling with you. Please take it!",
}
may="You're {PLAYER}, right? I'm MAY. Welcome to LITTLEROOT!\n\nDad said a GYM LEADER's family was moving next door. I hoped we'd get to be friends!\n\nHe studies POKéMON from all nine regions. He took their starter partners out for fieldwork today.\n\nYou can meet him on ROUTE 101, north of town!"
brendan="You're {PLAYER}? I'm BRENDAN. Dad told me you were moving next door.\n\nA GYM LEADER's kid, huh? We'll have to battle sometime!\n\nDad studies POKéMON from all nine regions. He's on ROUTE 101 with their starter partners today.\n\nHead north out of town. You can't miss him!"
for i in (558,561):D[i]=may
for i in (559,563):D[i]=brendan
D.update({1478: "COURTNEY: The METEORITE is ours.\n\nYou won't take it from us. I'll stop you here.", 1467: 'BRENDAN: What?! I wanted to see it!\n\nAll right, all right. You earned this, {PLAYER}.\n\nWay to go! Dad will be talking about this for weeks!', 859: "MR. BRINEY: Ah, {PLAYER}{KUN}! It's been too long!\n\nI've joined DOCK here at the shipyard. That lad's S.S. TIDAL is a fine vessel!\n\nHe knows the engineering, and I know the sea. Together, we'll keep her sailing for years!", 857: "DOCK: MR. BRINEY's joined us!\n\nThe ferry is sailing, but there's always work to do. His experience at sea is a great help.", 1390: 'Use a RAZOR CLAW on SNEASEL at night to evolve it into WEAVILE.\n\nA Hisuian SNEASEL needs it during the day instead, to become SNEASLER.', 635: "Once you have an HM and its BADGE, a compatible partner lets you use that field skill.\n\nIt doesn't take up a battle move slot. You can even clear the way if that partner has fainted.", 621: "POKéMON grow stronger as they gain levels.\n\nThe CENTER's free LEVELER brings your whole party to the current limit. It's handy when a new partner joins!", 622: 'Get to know what each partner does well.\n\nA new move or a different teammate can make all the difference in a tough battle.'})
# Apply only to exact currently owned text blocks. No event logic rewritten here.
changes=[]
for i,value in D.items():
 b=rows[i-1];p=root/b['file'];s=p.read_text();pat=r'(?m)^'+re.escape(b['label'])+r'::?\n(?:\s*\.string[^\n]*\n)+'
 m=re.search(pat,s);assert m,(i,b['label'])
 chunks=[]
 for pi,para in enumerate(value.split('\n\n')):
  lines=[]
  for explicit in para.split('\n'):
   lines.extend(textwrap.wrap(explicit,width=33,break_long_words=False,break_on_hyphens=False))
  for li,line in enumerate(lines):
   end=('\\n' if li==0 else '\\l') if li<len(lines)-1 else ('\\p' if pi<len(value.split('\n\n'))-1 else '$')
   chunks.append('\t.string '+json.dumps(line+end,ensure_ascii=False).replace('\\\\','\\'))
 replacement=b['label']+(':\n' if m.group().startswith(b['label']+':\n') else '::\n')+'\n'.join(chunks)+'\n'
 s=s[:m.start()]+replacement+s[m.end():];p.write_text(s)
 changes.append({'index':i,'file':b['file'],'label':b['label'],'before':b['text'],'after':value})
Path('work/dialogue-review-20260909/main-edits.json').write_text(json.dumps(changes,indent=2,ensure_ascii=False)+'\n')
print('Edited',len(changes),'blocks across',len({x['file'] for x in changes}),'files')
