#ifndef GUARD_CONSTANTS_EMERALD_CHAMPIONS_H
#define GUARD_CONSTANTS_EMERALD_CHAMPIONS_H

#define EC_BATTLE_SET_FAILED                 0
#define EC_BATTLE_SET_SUCCESS                1
#define EC_BATTLE_SET_SPECIAL_ITEM_EQUIPPED  2
#define EC_BATTLE_SET_MEGA                   3

#define EMERALD_CHAMPIONS_MEGA_ONLY          TRUE

#endif // GUARD_CONSTANTS_EMERALD_CHAMPIONS_H
