MoveRelearner_Text_AnythingElse:
	.string "Is there anything else I may do\n"
	.string "for you?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Please choose your Pokémon.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "You have no Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Sorry…\n"
	.string "But an Egg can't learn moves.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Sorry…\p"
	.string "It doesn't appear as if I have any move\n"
	.string "I can teach that Pokémon.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "level up move$"

MoveRelearner_Text_EggMoveLWR::
	.string "egg move$"

MoveRelearner_Text_MoveLWR::
	.string "move$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Which {STR_VAR_3} should I teach?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Thank you for using our services.\n"
	.string "Please come again!$"
