ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Are you planning on going deep\n"
	.string "in there?\p"
	.string "How about bringing me back some\n"
	.string "SHOAL SALT and SHOAL SHELLS?\p"
	.string "I can make you something good if\n"
	.string "you bring me the ingredients.$"
ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Bring me four each of SHOAL SALT\n"
	.string "and SHOAL SHELLS, and I can weave\l"
	.string "a reusable LINKING CORD.$"
ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hey! You found enough SHOAL SALT\n"
	.string "and SHOAL SHELLS!\p"
	.string "Would you like me to weave them into\n"
	.string "a LINKING CORD?$"
ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "All right! I'll make that LINKING CORD\n"
	.string "right away.\p"
	.string "… … … … … … … …\n"
	.string "There! Done!$"
ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "This reusable LINKING CORD lets\n"
	.string "certain POKéMON evolve without a trade.$"
ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Is that so?\n"
	.string "I wanted to weave a LINKING CORD…$"
ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "There is no room in your KEY ITEMS\n"
	.string "pocket. Make space and come back.$"

ShoalCave_LowTideEntranceRoom_Text_AlreadyHasLinkingCord:
	.string "You already have the LINKING CORD\n"
	.string "I made. It is reusable, so one is enough.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "There was some SHOAL SALT here.\n"
	.string "But, there's nothing here now.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "There was a SHOAL SHELL here.\n"
	.string "But, there's nothing here now.$"
