from pathlib import Path
import json,copy
B=Path(__file__).resolve().parents[1];j=json.loads((B/'review/shared-ai-audit.json').read_text());j=copy.deepcopy(j)
for f in j['findings']:
 if f['id']=='SAI-07':
  f['editor_refinement']='Final book avoids a fixed two-action shortlist that could omit the enabling move. Evaluate the bounded full one-turn legal action-pair set using shared caches; profile before considering any pruning.'
  f['final_algorithm']='Carry an explicit candidate tuple: action kind, move, target, switch recipient, Mega choice and speculative/committed status. Enumerate the legal one-turn move/target choices and owner-valid switches for each active actor, then compare their valid pairs under the form scenarios from SAI-06. Reuse native per-action damage/effect caches; recompute partner payoff for the actual pair and order. Before controller output reject duplicate reserve claims, wasted support with no payoff, incompatible field changes, avoidable ally knockouts and duplicate same-owner Mega activation. Terminal winning lines outrank preserving HP or dramatic aces; assess uncertain outcomes honestly. Preserve recognized support/enabling moves even when their independent score is low. Counterfactual evaluation does not consume gameplay RNG; final genuine ties may use the existing decision seed. No fixed two-candidate cap is adopted.'
  f['bound']='One turn only. The current four-move/four-actor/at-most-six-party model has a small finite action set; use a32-entry bound per actor with checked construction, at most1024pair checks per legal form scenario, and cache expensive calculations. Actual legal counts are normally lower. No recursive multi-turn tree or external simulator. Profile on target; any pruning needs measured justification and regression coverage for enabling actions.'
 if f['id']=='SAI-04':f['final_algorithm']=f['final_algorithm'].replace('Rank legality/survival and immediate joint knockout/preservation value before damage/support and tie preferences.','Reject illegal candidates; prioritize actual winning outcomes, then survival and joint knockout/preservation value before secondary damage/support and tie preferences. A necessary winning sacrifice must not be rejected merely for losing HP.')
(B/'review/shared-ai-final.json').write_text(json.dumps(j,indent=2,ensure_ascii=False)+'\n')
lines=['# 06 — Shared expert AI and tactical execution','','**Authority:** these are the final shared AI specifications used by every authored trainer, including the new opening rival and explicitly scripted rescue. Individual battle chapters name required scenarios; they do not each install another trainer-specific scoring patch. Difficulty settings change levels, not access to these tactical capabilities.','','The current engine already contains substantial damage, status, switching, partner and field logic. Preserve successful behavior. The source review identified specific defects and limitations below; the book has not executed a new native battle build or proven mathematical optimality. Every repair needs a reproducing fixture and relevant negative control before implementation is called verified.','','## Common information and decision contract','','Use one explicit expert campaign profile. Opponents may know team species, moves, items and abilities through that profile, but must not read the player\'s unexecuted chosen-command buffer as foreknowledge. Current transformed/suppressed abilities, consumed items, PP, status and field state override stale assumptions. Keep the observation contract consistent across trainer classes and difficulty modes. Document this game rule in the optional battle guide rather than claim exact equivalence to another live ladder\'s information rules.','','Champions Points use the formula and fixed effectiveIV31 in chapter02. Compare priority before Speed: Spore already precedes Trick Room by priority, while Speed investment can determine whether the sleeper acts before the setter\'s attacking partner. Ability/item/field changes can alter that order. Never substitute a conventional EV or zero-Speed-IV calculation.','','### Integration sequence','','1. SAI-03 andSAI-11: trustworthy candidate state and current-hit damage.','2. SAI-02: truthful roll/crit forecasts.','3. SAI-01 andSAI-09: shared capabilities and one owner per mechanic.','4. SAI-06: real base/Mega form evaluation and owner budgets.','5. SAI-04/05/07/08/10: reserve, paired-action, ally-activation and field decisions on those reliable inputs.','6. SAI-12: preserve existing working cases and validate the actual authored matchups.','','Do not introduce a monolithic replacement AI or a parallel external battle simulator. Reuse native move, stat, ability, form and field primitives with compact scratch state. Do not copy entire save blocks or allocate a new heap object for every candidate.','']
for f in j['findings']:
 lines +=[f"## {f['id']} — {f['title']}",'',f"**Disposition: {f['disposition']}.**",'', '**Source evidence**','']
 for r in f['source_references']:lines.append(f"- [{r['file']}:{r['line']}](../baseline/source/{r['file']}#L{r['line']})")
 lines +=['',f['evidence'],'','**Assessment**','',f.get('assessment','Preserve the specifically identified working behaviors while implementing isolated changes around them.'),'','**Final specification**','',f['final_algorithm'],'','**Implementation bound**','',f['bound'],'','**Acceptance evidence**','',f['acceptance'],'','**Limits**','',f['limits'],'']
 if f.get('editor_refinement'):lines +=['**Lead-editor reconciliation:** '+f['editor_refinement'],'']
lines +=['## Authored teams remain the consumers','','The battle volumes reproduce full baseline and final teams. Their specific examples include Falinks/Gallade ordering, Fake Out plus setup, Room setters, Instruct, ally Surf/Steam Engine, snow screens, Palafin activation, Choice-locked friendly spread damage and actual Mega abilities. Test the intended board and an interrupted board; do not prove a combo only by forcing the desired commands.','','The newly restored Walrein, Dusclops and Nosepass need purposeful decisions with their partners. The revised Huge Power Mega Starmie requires actual transformed Attack in AI forecasts. Rayquaza\'s move-based Mega eligibility must be considered alongside Steven\'s Metagross; one stone is not proof that only one Pokémon can Mega. Zygarde\'s Complete transition and Eternal Floette\'s specific Mega eligibility are also part of the final acquisition/team reconciliation.','','## Verification discipline','','Audit any existing test that disagrees: its current contract, configured forms, exact Points/natures/levels, fixture Speed/HP, branch setup, and source/artifact freshness. Preserve real invariants; update or retire obsolete assumptions. A score-number difference alone does not establish worse play. Conversely, a source comparison or scripted forced move is not proof the AI independently chooses the right action.','','Use a focused set of production-function and native action-selection tests covering the distinct failures above, followed by actual representative authored battles. Measure decision latency and peak scratch memory at doubles, full-party, dual-owner and multiple-Mega-candidate boundaries. Re-run only when a change or unresolved concern justifies it; no historical test-count floor is added.','']
(B/'chapters/06-shared-ai.md').write_text('\n'.join(lines)+'\n')
print('Shared AI specifications',len(j['findings']))
