#include "global.h"
#include "test/battle.h"
#include "battle_ai_main.h"
#include "main.h"

AI_DOUBLE_BATTLE_TEST("EC expert pair: timing probe with full parties and legal Mega reserves")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_SMART_SWITCHING | AI_FLAG_SMART_MON_CHOICES
            | AI_FLAG_PREDICTION | AI_FLAG_PP_STALL_PREVENTION | AI_FLAG_HP_AWARE | AI_FLAG_TRY_TO_2HKO
            | AI_FLAG_POWERFUL_STATUS | AI_FLAG_KNOW_OPPONENT_PARTY | AI_FLAG_DOUBLE_BATTLE);
        PLAYER(SPECIES_ORANGURU) { HP(500); MaxHP(500); Ability(ABILITY_TELEPATHY); Speed(90); Moves(MOVE_CELEBRATE, MOVE_THUNDERBOLT, MOVE_SHADOW_BALL, MOVE_PROTECT); }
        PLAYER(SPECIES_ORANGURU) { HP(500); MaxHP(500); Ability(ABILITY_TELEPATHY); Speed(80); Moves(MOVE_CELEBRATE, MOVE_SURF, MOVE_ICE_BEAM, MOVE_HELPING_HAND); }
        PLAYER(SPECIES_WOBBUFFET) { HP(500); MaxHP(500); Speed(60); Moves(MOVE_COUNTER, MOVE_MIRROR_COAT, MOVE_ENCORE, MOVE_DESTINY_BOND); }
        PLAYER(SPECIES_WOBBUFFET) { HP(500); MaxHP(500); Speed(60); Moves(MOVE_COUNTER, MOVE_MIRROR_COAT, MOVE_ENCORE, MOVE_DESTINY_BOND); }
        PLAYER(SPECIES_WOBBUFFET) { HP(500); MaxHP(500); Speed(60); Moves(MOVE_COUNTER, MOVE_MIRROR_COAT, MOVE_ENCORE, MOVE_DESTINY_BOND); }
        PLAYER(SPECIES_WOBBUFFET) { HP(500); MaxHP(500); Speed(60); Moves(MOVE_COUNTER, MOVE_MIRROR_COAT, MOVE_ENCORE, MOVE_DESTINY_BOND); }
        OPPONENT(SPECIES_MAWILE) { HP(300); MaxHP(300); Speed(70); Ability(ABILITY_INTIMIDATE); Item(ITEM_MAWILITE); Moves(MOVE_IRON_HEAD, MOVE_PLAY_ROUGH, MOVE_SUCKER_PUNCH, MOVE_PROTECT); }
        OPPONENT(SPECIES_TORKOAL) { HP(300); MaxHP(300); Speed(70); Ability(ABILITY_DROUGHT); Moves(MOVE_ERUPTION, MOVE_HEAT_WAVE, MOVE_BODY_PRESS, MOVE_PROTECT); }
        OPPONENT(SPECIES_VENUSAUR) { HP(300); MaxHP(300); Speed(70); Ability(ABILITY_CHLOROPHYLL); Item(ITEM_VENUSAURITE); Moves(MOVE_GIGA_DRAIN, MOVE_SLUDGE_BOMB, MOVE_SLEEP_POWDER, MOVE_PROTECT); }
        OPPONENT(SPECIES_METAGROSS) { HP(300); MaxHP(300); Speed(70); Item(ITEM_METAGROSSITE); Moves(MOVE_IRON_HEAD, MOVE_ZEN_HEADBUTT, MOVE_BULLET_PUNCH, MOVE_PROTECT); }
        OPPONENT(SPECIES_GASTRODON) { HP(300); MaxHP(300); Speed(70); Ability(ABILITY_STORM_DRAIN); Moves(MOVE_MUDDY_WATER, MOVE_EARTH_POWER, MOVE_RECOVER, MOVE_PROTECT); }
        OPPONENT(SPECIES_ORANGURU) { HP(300); MaxHP(300); Speed(70); Ability(ABILITY_TELEPATHY); Moves(MOVE_INSTRUCT, MOVE_TRICK_ROOM, MOVE_PSYCHIC, MOVE_PROTECT); }
    } WHEN {
        TURN { MOVE(playerLeft, MOVE_CELEBRATE); MOVE(playerRight, MOVE_CELEBRATE); }
    } THEN {
        gAiLogicData->battlerMovesScored = 0;
        u32 start = gMain.vblankCounter1;
        bool32 selected = AI_ComputeDoublesDecisions(opponentLeft - gBattleMons);
        Test_MgbaPrintf("full-party paired decision selected=%d frames=%d", selected, gMain.vblankCounter1 - start);
    }
}
