OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 81FBE86
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
	.string "In a Double Battle, your first two\n"
	.string "healthy Pokémon lead the team.\p"
	.string "Try changing their order in your\n"
	.string "party to find partners that work\l"
	.string "well together!$"
