OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "In a DOUBLE BATTLE, your first two\n"
	.string "Pokémon able to battle form your\l"
	.string "opening pair.\p"
	.string "Change their party order before\n"
	.string "you challenge a Trainer. Those two\l"
	.string "partners set the opening.$"

