AbandonedShip_Rooms_1F_MapScripts::
	.byte 0

AbandonedShip_Rooms_1F_EventScript_Gentleman::
	msgbox AbandonedShip_Rooms_1F_Text_TakingALookAround, MSGBOX_NPC
	end

AbandonedShip_Rooms_1F_EventScript_Demetrius::
	msgbox AbandonedShip_Rooms_1F_Text_DemetriusPostBattle, MSGBOX_NPC
	end

AbandonedShip_Rooms_1F_EventScript_Thalia::
	msgbox AbandonedShip_Rooms_1F_Text_ThaliaPostBattle, MSGBOX_NPC
	end

AbandonedShip_Rooms_1F_Text_TakingALookAround:
	.string "Ships of this sort are rare, so I'm\n"
	.string "taking a look around.\p"
	.string "Hmhm…\n"
	.string "There appear to be other cabins…$"

AbandonedShip_Rooms_1F_Text_ThaliaPostBattle:
	.string "The man next door…\p"
	.string "He says he's just sightseeing,\n"
	.string "but I don't know about that.$"

AbandonedShip_Rooms_1F_Text_DemetriusPostBattle:
	.string "I'm in trouble with my mom, so I ran.\n"
	.string "Keep it a secret where I am!$"

