// Generated by scripts/verdant_gen9_curated.py.
const u8 gVerdantGen9SprigatitoPokedexText[] = _(
    "The sweet scent its body gives off\n"
    "mesmerizes those around it. The\n"
    "scent grows stronger when this\n"
    "Pokémon is in the sun.");
const u8 gVerdantGen9FloragatoPokedexText[] = _(
    "Floragato deftly wields the vine\n"
    "hidden beneath its long fur, slamming\n"
    "the hard flower bud against its\n"
    "opponents.");
const u8 gVerdantGen9MeowscaradaPokedexText[] = _(
    "This Pokémon uses the reflective\n"
    "fur lining its cape to camouflage the\n"
    "stem of its flower, creating the\n"
    "illusion that the flower is floating.");
const u8 gVerdantGen9FuecocoPokedexText[] = _(
    "Its flame sac is small, so energy is\n"
    "always leaking out. This energy is\n"
    "released from the dent atop\n"
    "Fuecoco's head and flickers to and fro.");
const u8 gVerdantGen9CrocalorPokedexText[] = _(
    "The combination of Crocalor's fire\n"
    "energy and overflowing vitality has\n"
    "caused an egg-shaped fireball to\n"
    "appear on the Pokémon's head.");
const u8 gVerdantGen9SkeledirgePokedexText[] = _(
    "Skeledirge's gentle singing\n"
    "soothes the souls of all that hear it. It\n"
    "burns its enemies to a crisp with\n"
    "flames of over 5,400 degrees Fahrenheit.");
const u8 gVerdantGen9NacliPokedexText[] = _(
    "The ground scrapes its body as it\n"
    "travels, causing it to leave salt\n"
    "behind. Salt is constantly being created\n"
    "and replenished inside Nacli's body.");
const u8 gVerdantGen9NaclstackPokedexText[] = _(
    "It compresses rock salt inside its\n"
    "body and shoots out hardened salt\n"
    "pellets with enough force to\n"
    "perforate an iron sheet.");
const u8 gVerdantGen9GarganaclPokedexText[] = _(
    "Garganacl will rub its fingertips\n"
    "together and sprinkle injured\n"
    "Pokémon with salt. Even severe wounds will\n"
    "promptly heal afterward.");
const u8 gVerdantGen9FinizenPokedexText[] = _(
    "Its water ring is made from\n"
    "seawater mixed with a sticky fluid that\n"
    "Finizen secretes from its blowhole.");
const u8 gVerdantGen9PalafinPokedexText[] = _(
    "This Pokémon changes its appearance\n"
    "if it hears its allies calling for\n"
    "help. Palafin will never show\n"
    "anybody its moment of transformation.");
const u8 gVerdantGen9DondozoPokedexText[] = _(
    "It treats Tatsugiri like its boss\n"
    "and follows it loyally. Though\n"
    "powerful, Dondozo is apparently not very\n"
    "smart.");
const u8 gVerdantGen9TatsugiriPokedexText[] = _(
    "This is a small dragon Pokémon. It\n"
    "lives inside the mouth of Dondozo to\n"
    "protect itself from enemies on the\n"
    "outside.");
const u8 gVerdantGen9AnnihilapePokedexText[] = _(
    "When its anger rose beyond a\n"
    "critical point, this Pokémon gained power\n"
    "that is unfettered by the limits of\n"
    "its physical body.");
const u8 gVerdantGen9FarigirafPokedexText[] = _(
    "Now that the brain waves from the\n"
    "head and tail are synced up, the\n"
    "psychic power of this Pokémon is 10\n"
    "times stronger than Girafarig's.");
const u8 gVerdantGen9KingambitPokedexText[] = _(
    "Though it commands a massive army\n"
    "in battle, it's not skilled at\n"
    "devising complex strategies. It just uses\n"
    "brute strength to keep pushing.");
const u8 gVerdantGen9GreatTuskPokedexText[] = _(
    "Sightings of this Pokémon have\n"
    "occurred in recent years. The name\n"
    "Great Tusk was taken from a creature\n"
    "listed in a certain book.");
const u8 gVerdantGen9FlutterManePokedexText[] = _(
    "It has similar features to a\n"
    "ghostly pterosaur that was covered in a\n"
    "paranormal magazine, but the two\n"
    "have little else in common.");
const u8 gVerdantGen9IronBundlePokedexText[] = _(
    "Its shape is similar to a robot\n"
    "featured in a paranormal magazine\n"
    "article. The robot was said to have been\n"
    "created by an ancient civilization.");
const u8 gVerdantGen9IronHandsPokedexText[] = _(
    "It is very similar to a cyborg\n"
    "covered exclusively by a paranormal\n"
    "magazine. The cyborg was said to be the\n"
    "modified form of a certain athlete.");
const u8 gVerdantGen9GlimmetPokedexText[] = _(
    "Glimmet's toxic mineral crystals\n"
    "look just like flower petals. This\n"
    "Pokémon scatters poisonous powder like\n"
    "pollen to protect itself.");
const u8 gVerdantGen9GlimmoraPokedexText[] = _(
    "Glimmora's petals are made of\n"
    "crystallized poison energy. When\n"
    "it detects danger, it opens them\n"
    "and fires a poisonous beam.");
const u8 gVerdantGen9GimmighoulPokedexText[] = _(
    "It lives inside an old treasure\n"
    "chest. Sometimes it gets left in shop\n"
    "corners since no one realizes it's\n"
    "actually a Pokémon.");
const u8 gVerdantGen9GholdengoPokedexText[] = _(
    "It has a sturdy body made up of\n"
    "stacked coins. Gholdengo overwhelms\n"
    "its enemies by firing coin after coin\n"
    "at them in quick succession.");
const u8 gVerdantGen9ChienPaoPokedexText[] = _(
    "This Pokémon can control 100 tons\n"
    "of fallen snow. It plays around\n"
    "innocently by leaping in and out of\n"
    "avalanches it has caused.");
const u8 gVerdantGen9TingLuPokedexText[] = _(
    "It slowly brings its exceedingly\n"
    "heavy head down upon the ground,\n"
    "splitting the earth open with huge\n"
    "fissures that run over 160 feet deep.");
const u8 gVerdantGen9ChiYuPokedexText[] = _(
    "It controls flames burning at over\n"
    "5,400 degrees Fahrenheit. It\n"
    "casually swims through the sea of lava it\n"
    "creates by melting rock and sand.");
const u8 gVerdantGen9RoaringMoonPokedexText[] = _(
    "According to an article in a\n"
    "dubious magazine, this Pokémon has some\n"
    "connection to Mega Evolution that\n"
    "occurs in Hoenn.");
const u8 gVerdantGen9IronValiantPokedexText[] = _(
    "It has some similarities to a mad\n"
    "scientist's invention covered in a\n"
    "paranormal magazine.");
const u8 gVerdantGen9WalkingWakePokedexText[] = _(
    "This ferocious creature is shrouded in\n"
    "mystery. It's named after an aquatic\n"
    "monster mentioned in an old journal.");
const u8 gVerdantGen9OgerponPokedexText[] = _(
    "This Pokémon's type changes based on\n"
    "which mask it's wearing. It confounds\n"
    "its enemies with nimble movements\n"
    "and kicks.");
const u8 gVerdantGen9ArchaludonPokedexText[] = _(
    "It gathers static electricity\n"
    "from its surroundings. The beams\n"
    "it launches when down on all fours\n"
    "are tremendously powerful.");
const u8 gVerdantGen9GougingFirePokedexText[] = _(
    "There are scant few reports of\n"
    "this creature being sighted.\n"
    "One short video shows it rampaging,\n"
    "and spouting pillars of flame.");
const u8 gVerdantGen9RagingBoltPokedexText[] = _(
    "It bears resemblance to a Pokémon\n"
    "that became a hot topic for a short\n"
    "while after a paranormal magazine\n"
    "touted it as Raikou's ancestor.");
