// Generated by scripts/verdant_handbook_battle_sets.py. Do not edit by hand.
static const u8 sVerdantDefaultSetName_VENUSAUR[] = _("Attacker");
static const u8 sVerdantDefaultSetName_CHARIZARD[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_BLASTOISE[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_RAICHU[] = _("Support");
static const u8 sVerdantDefaultSetName_CLEFABLE[] = _("Support");
static const u8 sVerdantDefaultSetName_NINETALES[] = _("Support");
static const u8 sVerdantDefaultSetName_ARCANINE[] = _("Support");
static const u8 sVerdantDefaultSetName_ALAKAZAM[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_VICTREEBEL[] = _("Attacker");
static const u8 sVerdantDefaultSetName_GOLEM[] = _("Attacker");
static const u8 sVerdantDefaultSetName_SLOWBRO[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_DODRIO[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_GENGAR[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_KANGASKHAN[] = _("Attacker");
static const u8 sVerdantDefaultSetName_STARMIE[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_TAUROS[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_GYARADOS[] = _("Recommended");
static const u8 sVerdantDefaultSetName_AERODACTYL[] = _("Support");
static const u8 sVerdantDefaultSetName_ZAPDOS[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_MOLTRES[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_DRAGONITE[] = _("Recommended");
static const u8 sVerdantDefaultSetName_MEWTWO[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_MEW[] = _("Support");
static const u8 sVerdantDefaultSetName_TYPHLOSION[] = _("Spread Attacker");
static const u8 sVerdantDefaultSetName_FERALIGATR[] = _("Recommended");
static const u8 sVerdantDefaultSetName_LANTURN[] = _("Recommended");
static const u8 sVerdantDefaultSetName_JUMPLUFF[] = _("Redirection");
static const u8 sVerdantDefaultSetName_SLOWKING[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_STEELIX[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_SCIZOR[] = _("Recommended");
static const u8 sVerdantDefaultSetName_SKARMORY[] = _("Physical Wall");
static const u8 sVerdantDefaultSetName_HOUNDOOM[] = _("Spread Attacker");
static const u8 sVerdantDefaultSetName_KINGDRA[] = _("Attacker");
static const u8 sVerdantDefaultSetName_PORYGON2[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_RAIKOU[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_SUICUNE[] = _("Support");
static const u8 sVerdantDefaultSetName_TYRANITAR[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_CELEBI[] = _("Support");
static const u8 sVerdantDefaultSetName_SCEPTILE[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_BLAZIKEN[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_SWAMPERT[] = _("Attacker");
static const u8 sVerdantDefaultSetName_LUDICOLO[] = _("Attacker");
static const u8 sVerdantDefaultSetName_SHIFTRY[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_GARDEVOIR[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_HARIYAMA[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_SABLEYE[] = _("Support");
static const u8 sVerdantDefaultSetName_AGGRON[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_MEDICHAM[] = _("Attacker");
static const u8 sVerdantDefaultSetName_MANECTRIC[] = _("Recommended");
static const u8 sVerdantDefaultSetName_SHARPEDO[] = _("Recommended");
static const u8 sVerdantDefaultSetName_FLYGON[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_ALTARIA[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_CRAWDAUNT[] = _("Wallbreaker");
static const u8 sVerdantDefaultSetName_ABSOL[] = _("Attacker");
static const u8 sVerdantDefaultSetName_GLALIE[] = _("Attacker");
static const u8 sVerdantDefaultSetName_METAGROSS[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_REGIROCK[] = _("Recommended");
static const u8 sVerdantDefaultSetName_REGICE[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_LATIAS[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_LATIOS[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_GROUDON[] = _("Recommended");
static const u8 sVerdantDefaultSetName_RAYQUAZA[] = _("Recommended");
static const u8 sVerdantDefaultSetName_JIRACHI[] = _("Support");
static const u8 sVerdantDefaultSetName_STARAPTOR[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_FLOATZEL[] = _("Attacker");
static const u8 sVerdantDefaultSetName_GASTRODON[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_LOPUNNY[] = _("Recommended");
static const u8 sVerdantDefaultSetName_BRONZONG[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_GARCHOMP[] = _("Spread Attacker");
static const u8 sVerdantDefaultSetName_LUCARIO[] = _("Attacker");
static const u8 sVerdantDefaultSetName_ABOMASNOW[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_ELECTIVIRE[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_MAGMORTAR[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_YANMEGA[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_GALLADE[] = _("Attacker");
static const u8 sVerdantDefaultSetName_PROBOPASS[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_DUSKNOIR[] = _("Support");
static const u8 sVerdantDefaultSetName_FROSLASS[] = _("Recommended");
static const u8 sVerdantDefaultSetName_ROTOM[] = _("Spread Attacker");
static const u8 sVerdantDefaultSetName_MESPRIT[] = _("Support");
static const u8 sVerdantDefaultSetName_AZELF[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_PALKIA[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_REGIGIGAS[] = _("Attacker");
static const u8 sVerdantDefaultSetName_GIRATINA[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_MANAPHY[] = _("Attacker");
static const u8 sVerdantDefaultSetName_VICTINI[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_ZEBSTRIKA[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_EXCADRILL[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_AUDINO[] = _("Recommended");
static const u8 sVerdantDefaultSetName_LEAVANNY[] = _("Recommended");
static const u8 sVerdantDefaultSetName_SCOLIPEDE[] = _("Attacker");
static const u8 sVerdantDefaultSetName_BASCULIN[] = _("Recommended");
static const u8 sVerdantDefaultSetName_SCRAFTY[] = _("Recommended");
static const u8 sVerdantDefaultSetName_ZOROARK[] = _("Recommended");
static const u8 sVerdantDefaultSetName_SWANNA[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_AMOONGUSS[] = _("Recommended");
static const u8 sVerdantDefaultSetName_EELEKTROSS[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_CHANDELURE[] = _("Recommended");
static const u8 sVerdantDefaultSetName_HAXORUS[] = _("Recommended");
static const u8 sVerdantDefaultSetName_STUNFISK[] = _("Attacker");
static const u8 sVerdantDefaultSetName_MIENSHAO[] = _("Recommended");
static const u8 sVerdantDefaultSetName_GOLURK[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_MANDIBUZZ[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_COBALION[] = _("Recommended");
static const u8 sVerdantDefaultSetName_TERRAKION[] = _("Recommended");
static const u8 sVerdantDefaultSetName_THUNDURUS[] = _("Recommended");
static const u8 sVerdantDefaultSetName_KYUREM[] = _("Recommended");
static const u8 sVerdantDefaultSetName_GENESECT[] = _("Recommended");
static const u8 sVerdantDefaultSetName_CHESNAUGHT[] = _("Recommended");
static const u8 sVerdantDefaultSetName_DELPHOX[] = _("Setup Sweeper");
static const u8 sVerdantDefaultSetName_GRENINJA[] = _("Attacker");
static const u8 sVerdantDefaultSetName_FLOETTE[] = _("Support");
static const u8 sVerdantDefaultSetName_MEOWSTIC[] = _("Recommended");
static const u8 sVerdantDefaultSetName_MALAMAR[] = _("Recommended");
static const u8 sVerdantDefaultSetName_DRAGALGE[] = _("Wallbreaker");
static const u8 sVerdantDefaultSetName_HAWLUCHA[] = _("Attacker");
static const u8 sVerdantDefaultSetName_GOODRA[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_GOURGEIST[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_XERNEAS[] = _("Recommended");
static const u8 sVerdantDefaultSetName_YVELTAL[] = _("Recommended");
static const u8 sVerdantDefaultSetName_DIANCIE[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_CRABOMINABLE[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_LYCANROC[] = _("Attacker");
static const u8 sVerdantDefaultSetName_LURANTIS[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_SILVALLY[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_BRUXISH[] = _("Setup Sweeper");
static const u8 sVerdantDefaultSetName_DRAMPA[] = _("Spread Attacker");
static const u8 sVerdantDefaultSetName_SOLGALEO[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_LUNALA[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_PHEROMOSA[] = _("Recommended");
static const u8 sVerdantDefaultSetName_CELESTEELA[] = _("Bulky Support");
static const u8 sVerdantDefaultSetName_GUZZLORD[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_NECROZMA[] = _("Attacker");
static const u8 sVerdantDefaultSetName_MAGEARNA[] = _("Trick Room");
static const u8 sVerdantDefaultSetName_NAGANADEL[] = _("Tailwind");
static const u8 sVerdantDefaultSetName_ZERAORA[] = _("Recommended");
static const u8 sVerdantDefaultSetName_RILLABOOM[] = _("Recommended");
static const u8 sVerdantDefaultSetName_CINDERACE[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_DREDNAW[] = _("Spread Attacker");
static const u8 sVerdantDefaultSetName_TOXTRICITY[] = _("Spread Attacker");
static const u8 sVerdantDefaultSetName_FALINKS[] = _("Attacker");
static const u8 sVerdantDefaultSetName_STONJOURNER[] = _("Attacker");
static const u8 sVerdantDefaultSetName_INDEEDEE[] = _("Recommended");
static const u8 sVerdantDefaultSetName_COPPERAJAH[] = _("Wallbreaker");
static const u8 sVerdantDefaultSetName_DURALUDON[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_ZAMAZENTA[] = _("Support");
static const u8 sVerdantDefaultSetName_ETERNATUS[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_TATSUGIRI[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_FLUTTER_MANE[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_IRON_BUNDLE[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_IRON_HANDS[] = _("Recommended");
static const u8 sVerdantDefaultSetName_GLIMMORA[] = _("Recommended");
static const u8 sVerdantDefaultSetName_CHIEN_PAO[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_TING_LU[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_CHI_YU[] = _("Special Attacker");
static const u8 sVerdantDefaultSetName_ROARING_MOON[] = _("Physical Attacker");
static const u8 sVerdantDefaultSetName_OGERPON[] = _("Recommended");
static const u8 sVerdantDefaultSetName_RAGING_BOLT[] = _("Special Attacker");

const u8 *const gVerdantDefaultBattleSetNames[NUM_SPECIES] =
{
    [SPECIES_VENUSAUR] = sVerdantDefaultSetName_VENUSAUR,
    [SPECIES_CHARIZARD] = sVerdantDefaultSetName_CHARIZARD,
    [SPECIES_BLASTOISE] = sVerdantDefaultSetName_BLASTOISE,
    [SPECIES_RAICHU] = sVerdantDefaultSetName_RAICHU,
    [SPECIES_CLEFABLE] = sVerdantDefaultSetName_CLEFABLE,
    [SPECIES_NINETALES] = sVerdantDefaultSetName_NINETALES,
    [SPECIES_ARCANINE] = sVerdantDefaultSetName_ARCANINE,
    [SPECIES_ALAKAZAM] = sVerdantDefaultSetName_ALAKAZAM,
    [SPECIES_VICTREEBEL] = sVerdantDefaultSetName_VICTREEBEL,
    [SPECIES_GOLEM] = sVerdantDefaultSetName_GOLEM,
    [SPECIES_SLOWBRO] = sVerdantDefaultSetName_SLOWBRO,
    [SPECIES_DODRIO] = sVerdantDefaultSetName_DODRIO,
    [SPECIES_GENGAR] = sVerdantDefaultSetName_GENGAR,
    [SPECIES_KANGASKHAN] = sVerdantDefaultSetName_KANGASKHAN,
    [SPECIES_STARMIE] = sVerdantDefaultSetName_STARMIE,
    [SPECIES_TAUROS] = sVerdantDefaultSetName_TAUROS,
    [SPECIES_GYARADOS] = sVerdantDefaultSetName_GYARADOS,
    [SPECIES_AERODACTYL] = sVerdantDefaultSetName_AERODACTYL,
    [SPECIES_ZAPDOS] = sVerdantDefaultSetName_ZAPDOS,
    [SPECIES_MOLTRES] = sVerdantDefaultSetName_MOLTRES,
    [SPECIES_DRAGONITE] = sVerdantDefaultSetName_DRAGONITE,
    [SPECIES_MEWTWO] = sVerdantDefaultSetName_MEWTWO,
    [SPECIES_MEW] = sVerdantDefaultSetName_MEW,
    [SPECIES_TYPHLOSION] = sVerdantDefaultSetName_TYPHLOSION,
    [SPECIES_FERALIGATR] = sVerdantDefaultSetName_FERALIGATR,
    [SPECIES_LANTURN] = sVerdantDefaultSetName_LANTURN,
    [SPECIES_JUMPLUFF] = sVerdantDefaultSetName_JUMPLUFF,
    [SPECIES_SLOWKING] = sVerdantDefaultSetName_SLOWKING,
    [SPECIES_STEELIX] = sVerdantDefaultSetName_STEELIX,
    [SPECIES_SCIZOR] = sVerdantDefaultSetName_SCIZOR,
    [SPECIES_SKARMORY] = sVerdantDefaultSetName_SKARMORY,
    [SPECIES_HOUNDOOM] = sVerdantDefaultSetName_HOUNDOOM,
    [SPECIES_KINGDRA] = sVerdantDefaultSetName_KINGDRA,
    [SPECIES_PORYGON2] = sVerdantDefaultSetName_PORYGON2,
    [SPECIES_RAIKOU] = sVerdantDefaultSetName_RAIKOU,
    [SPECIES_SUICUNE] = sVerdantDefaultSetName_SUICUNE,
    [SPECIES_TYRANITAR] = sVerdantDefaultSetName_TYRANITAR,
    [SPECIES_CELEBI] = sVerdantDefaultSetName_CELEBI,
    [SPECIES_SCEPTILE] = sVerdantDefaultSetName_SCEPTILE,
    [SPECIES_BLAZIKEN] = sVerdantDefaultSetName_BLAZIKEN,
    [SPECIES_SWAMPERT] = sVerdantDefaultSetName_SWAMPERT,
    [SPECIES_LUDICOLO] = sVerdantDefaultSetName_LUDICOLO,
    [SPECIES_SHIFTRY] = sVerdantDefaultSetName_SHIFTRY,
    [SPECIES_GARDEVOIR] = sVerdantDefaultSetName_GARDEVOIR,
    [SPECIES_HARIYAMA] = sVerdantDefaultSetName_HARIYAMA,
    [SPECIES_SABLEYE] = sVerdantDefaultSetName_SABLEYE,
    [SPECIES_AGGRON] = sVerdantDefaultSetName_AGGRON,
    [SPECIES_MEDICHAM] = sVerdantDefaultSetName_MEDICHAM,
    [SPECIES_MANECTRIC] = sVerdantDefaultSetName_MANECTRIC,
    [SPECIES_SHARPEDO] = sVerdantDefaultSetName_SHARPEDO,
    [SPECIES_FLYGON] = sVerdantDefaultSetName_FLYGON,
    [SPECIES_ALTARIA] = sVerdantDefaultSetName_ALTARIA,
    [SPECIES_CRAWDAUNT] = sVerdantDefaultSetName_CRAWDAUNT,
    [SPECIES_ABSOL] = sVerdantDefaultSetName_ABSOL,
    [SPECIES_GLALIE] = sVerdantDefaultSetName_GLALIE,
    [SPECIES_METAGROSS] = sVerdantDefaultSetName_METAGROSS,
    [SPECIES_REGIROCK] = sVerdantDefaultSetName_REGIROCK,
    [SPECIES_REGICE] = sVerdantDefaultSetName_REGICE,
    [SPECIES_LATIAS] = sVerdantDefaultSetName_LATIAS,
    [SPECIES_LATIOS] = sVerdantDefaultSetName_LATIOS,
    [SPECIES_GROUDON] = sVerdantDefaultSetName_GROUDON,
    [SPECIES_RAYQUAZA] = sVerdantDefaultSetName_RAYQUAZA,
    [SPECIES_JIRACHI] = sVerdantDefaultSetName_JIRACHI,
    [SPECIES_STARAPTOR] = sVerdantDefaultSetName_STARAPTOR,
    [SPECIES_FLOATZEL] = sVerdantDefaultSetName_FLOATZEL,
    [SPECIES_GASTRODON] = sVerdantDefaultSetName_GASTRODON,
    [SPECIES_LOPUNNY] = sVerdantDefaultSetName_LOPUNNY,
    [SPECIES_BRONZONG] = sVerdantDefaultSetName_BRONZONG,
    [SPECIES_GARCHOMP] = sVerdantDefaultSetName_GARCHOMP,
    [SPECIES_LUCARIO] = sVerdantDefaultSetName_LUCARIO,
    [SPECIES_ABOMASNOW] = sVerdantDefaultSetName_ABOMASNOW,
    [SPECIES_ELECTIVIRE] = sVerdantDefaultSetName_ELECTIVIRE,
    [SPECIES_MAGMORTAR] = sVerdantDefaultSetName_MAGMORTAR,
    [SPECIES_YANMEGA] = sVerdantDefaultSetName_YANMEGA,
    [SPECIES_GALLADE] = sVerdantDefaultSetName_GALLADE,
    [SPECIES_PROBOPASS] = sVerdantDefaultSetName_PROBOPASS,
    [SPECIES_DUSKNOIR] = sVerdantDefaultSetName_DUSKNOIR,
    [SPECIES_FROSLASS] = sVerdantDefaultSetName_FROSLASS,
    [SPECIES_ROTOM] = sVerdantDefaultSetName_ROTOM,
    [SPECIES_MESPRIT] = sVerdantDefaultSetName_MESPRIT,
    [SPECIES_AZELF] = sVerdantDefaultSetName_AZELF,
    [SPECIES_PALKIA] = sVerdantDefaultSetName_PALKIA,
    [SPECIES_REGIGIGAS] = sVerdantDefaultSetName_REGIGIGAS,
    [SPECIES_GIRATINA] = sVerdantDefaultSetName_GIRATINA,
    [SPECIES_MANAPHY] = sVerdantDefaultSetName_MANAPHY,
    [SPECIES_VICTINI] = sVerdantDefaultSetName_VICTINI,
    [SPECIES_ZEBSTRIKA] = sVerdantDefaultSetName_ZEBSTRIKA,
    [SPECIES_EXCADRILL] = sVerdantDefaultSetName_EXCADRILL,
    [SPECIES_AUDINO] = sVerdantDefaultSetName_AUDINO,
    [SPECIES_LEAVANNY] = sVerdantDefaultSetName_LEAVANNY,
    [SPECIES_SCOLIPEDE] = sVerdantDefaultSetName_SCOLIPEDE,
    [SPECIES_BASCULIN] = sVerdantDefaultSetName_BASCULIN,
    [SPECIES_SCRAFTY] = sVerdantDefaultSetName_SCRAFTY,
    [SPECIES_ZOROARK] = sVerdantDefaultSetName_ZOROARK,
    [SPECIES_SWANNA] = sVerdantDefaultSetName_SWANNA,
    [SPECIES_AMOONGUSS] = sVerdantDefaultSetName_AMOONGUSS,
    [SPECIES_EELEKTROSS] = sVerdantDefaultSetName_EELEKTROSS,
    [SPECIES_CHANDELURE] = sVerdantDefaultSetName_CHANDELURE,
    [SPECIES_HAXORUS] = sVerdantDefaultSetName_HAXORUS,
    [SPECIES_STUNFISK] = sVerdantDefaultSetName_STUNFISK,
    [SPECIES_MIENSHAO] = sVerdantDefaultSetName_MIENSHAO,
    [SPECIES_GOLURK] = sVerdantDefaultSetName_GOLURK,
    [SPECIES_MANDIBUZZ] = sVerdantDefaultSetName_MANDIBUZZ,
    [SPECIES_COBALION] = sVerdantDefaultSetName_COBALION,
    [SPECIES_TERRAKION] = sVerdantDefaultSetName_TERRAKION,
    [SPECIES_THUNDURUS] = sVerdantDefaultSetName_THUNDURUS,
    [SPECIES_KYUREM] = sVerdantDefaultSetName_KYUREM,
    [SPECIES_GENESECT] = sVerdantDefaultSetName_GENESECT,
    [SPECIES_CHESNAUGHT] = sVerdantDefaultSetName_CHESNAUGHT,
    [SPECIES_DELPHOX] = sVerdantDefaultSetName_DELPHOX,
    [SPECIES_GRENINJA] = sVerdantDefaultSetName_GRENINJA,
    [SPECIES_FLOETTE] = sVerdantDefaultSetName_FLOETTE,
    [SPECIES_MEOWSTIC] = sVerdantDefaultSetName_MEOWSTIC,
    [SPECIES_MALAMAR] = sVerdantDefaultSetName_MALAMAR,
    [SPECIES_DRAGALGE] = sVerdantDefaultSetName_DRAGALGE,
    [SPECIES_HAWLUCHA] = sVerdantDefaultSetName_HAWLUCHA,
    [SPECIES_GOODRA] = sVerdantDefaultSetName_GOODRA,
    [SPECIES_GOURGEIST] = sVerdantDefaultSetName_GOURGEIST,
    [SPECIES_XERNEAS] = sVerdantDefaultSetName_XERNEAS,
    [SPECIES_YVELTAL] = sVerdantDefaultSetName_YVELTAL,
    [SPECIES_DIANCIE] = sVerdantDefaultSetName_DIANCIE,
    [SPECIES_CRABOMINABLE] = sVerdantDefaultSetName_CRABOMINABLE,
    [SPECIES_LYCANROC] = sVerdantDefaultSetName_LYCANROC,
    [SPECIES_LURANTIS] = sVerdantDefaultSetName_LURANTIS,
    [SPECIES_SILVALLY] = sVerdantDefaultSetName_SILVALLY,
    [SPECIES_BRUXISH] = sVerdantDefaultSetName_BRUXISH,
    [SPECIES_DRAMPA] = sVerdantDefaultSetName_DRAMPA,
    [SPECIES_SOLGALEO] = sVerdantDefaultSetName_SOLGALEO,
    [SPECIES_LUNALA] = sVerdantDefaultSetName_LUNALA,
    [SPECIES_PHEROMOSA] = sVerdantDefaultSetName_PHEROMOSA,
    [SPECIES_CELESTEELA] = sVerdantDefaultSetName_CELESTEELA,
    [SPECIES_GUZZLORD] = sVerdantDefaultSetName_GUZZLORD,
    [SPECIES_NECROZMA] = sVerdantDefaultSetName_NECROZMA,
    [SPECIES_MAGEARNA] = sVerdantDefaultSetName_MAGEARNA,
    [SPECIES_NAGANADEL] = sVerdantDefaultSetName_NAGANADEL,
    [SPECIES_ZERAORA] = sVerdantDefaultSetName_ZERAORA,
    [SPECIES_RILLABOOM] = sVerdantDefaultSetName_RILLABOOM,
    [SPECIES_CINDERACE] = sVerdantDefaultSetName_CINDERACE,
    [SPECIES_DREDNAW] = sVerdantDefaultSetName_DREDNAW,
    [SPECIES_TOXTRICITY] = sVerdantDefaultSetName_TOXTRICITY,
    [SPECIES_FALINKS] = sVerdantDefaultSetName_FALINKS,
    [SPECIES_STONJOURNER] = sVerdantDefaultSetName_STONJOURNER,
    [SPECIES_INDEEDEE] = sVerdantDefaultSetName_INDEEDEE,
    [SPECIES_COPPERAJAH] = sVerdantDefaultSetName_COPPERAJAH,
    [SPECIES_DURALUDON] = sVerdantDefaultSetName_DURALUDON,
    [SPECIES_ZAMAZENTA] = sVerdantDefaultSetName_ZAMAZENTA,
    [SPECIES_ETERNATUS] = sVerdantDefaultSetName_ETERNATUS,
    [SPECIES_TATSUGIRI] = sVerdantDefaultSetName_TATSUGIRI,
    [SPECIES_FLUTTER_MANE] = sVerdantDefaultSetName_FLUTTER_MANE,
    [SPECIES_IRON_BUNDLE] = sVerdantDefaultSetName_IRON_BUNDLE,
    [SPECIES_IRON_HANDS] = sVerdantDefaultSetName_IRON_HANDS,
    [SPECIES_GLIMMORA] = sVerdantDefaultSetName_GLIMMORA,
    [SPECIES_CHIEN_PAO] = sVerdantDefaultSetName_CHIEN_PAO,
    [SPECIES_TING_LU] = sVerdantDefaultSetName_TING_LU,
    [SPECIES_CHI_YU] = sVerdantDefaultSetName_CHI_YU,
    [SPECIES_ROARING_MOON] = sVerdantDefaultSetName_ROARING_MOON,
    [SPECIES_OGERPON] = sVerdantDefaultSetName_OGERPON,
    [SPECIES_RAGING_BOLT] = sVerdantDefaultSetName_RAGING_BOLT,
};

const struct VerdantBattleSetRange gVerdantBattleSetRanges[NUM_SPECIES] =
{
    [SPECIES_VENUSAUR] = {0, 1},
    [SPECIES_CHARIZARD] = {1, 2},
    [SPECIES_BLASTOISE] = {3, 1},
    [SPECIES_RAICHU] = {4, 2},
    [SPECIES_CLEFABLE] = {6, 1},
    [SPECIES_NINETALES] = {7, 1},
    [SPECIES_ARCANINE] = {8, 1},
    [SPECIES_ALAKAZAM] = {9, 1},
    [SPECIES_VICTREEBEL] = {10, 1},
    [SPECIES_GOLEM] = {11, 1},
    [SPECIES_SLOWBRO] = {12, 1},
    [SPECIES_DODRIO] = {13, 1},
    [SPECIES_GENGAR] = {14, 1},
    [SPECIES_KANGASKHAN] = {15, 1},
    [SPECIES_STARMIE] = {16, 1},
    [SPECIES_TAUROS] = {17, 1},
    [SPECIES_GYARADOS] = {18, 1},
    [SPECIES_AERODACTYL] = {19, 1},
    [SPECIES_ZAPDOS] = {20, 1},
    [SPECIES_MOLTRES] = {21, 1},
    [SPECIES_DRAGONITE] = {22, 1},
    [SPECIES_MEWTWO] = {23, 1},
    [SPECIES_MEW] = {24, 2},
    [SPECIES_TYPHLOSION] = {26, 1},
    [SPECIES_FERALIGATR] = {27, 1},
    [SPECIES_LANTURN] = {28, 1},
    [SPECIES_JUMPLUFF] = {29, 1},
    [SPECIES_SLOWKING] = {30, 1},
    [SPECIES_STEELIX] = {31, 1},
    [SPECIES_SCIZOR] = {32, 1},
    [SPECIES_SKARMORY] = {33, 1},
    [SPECIES_HOUNDOOM] = {34, 1},
    [SPECIES_KINGDRA] = {35, 1},
    [SPECIES_PORYGON2] = {36, 1},
    [SPECIES_RAIKOU] = {37, 1},
    [SPECIES_SUICUNE] = {38, 1},
    [SPECIES_TYRANITAR] = {39, 1},
    [SPECIES_CELEBI] = {40, 1},
    [SPECIES_SCEPTILE] = {41, 1},
    [SPECIES_BLAZIKEN] = {42, 1},
    [SPECIES_SWAMPERT] = {43, 1},
    [SPECIES_LUDICOLO] = {44, 1},
    [SPECIES_SHIFTRY] = {45, 1},
    [SPECIES_GARDEVOIR] = {46, 1},
    [SPECIES_HARIYAMA] = {47, 1},
    [SPECIES_SABLEYE] = {48, 1},
    [SPECIES_AGGRON] = {49, 1},
    [SPECIES_MEDICHAM] = {50, 1},
    [SPECIES_MANECTRIC] = {51, 1},
    [SPECIES_SHARPEDO] = {52, 1},
    [SPECIES_FLYGON] = {53, 1},
    [SPECIES_ALTARIA] = {54, 1},
    [SPECIES_CRAWDAUNT] = {55, 1},
    [SPECIES_ABSOL] = {56, 1},
    [SPECIES_GLALIE] = {57, 1},
    [SPECIES_METAGROSS] = {58, 1},
    [SPECIES_REGIROCK] = {59, 1},
    [SPECIES_REGICE] = {60, 1},
    [SPECIES_LATIAS] = {61, 1},
    [SPECIES_LATIOS] = {62, 1},
    [SPECIES_GROUDON] = {63, 1},
    [SPECIES_RAYQUAZA] = {64, 1},
    [SPECIES_JIRACHI] = {65, 1},
    [SPECIES_STARAPTOR] = {66, 1},
    [SPECIES_FLOATZEL] = {67, 1},
    [SPECIES_GASTRODON] = {68, 1},
    [SPECIES_LOPUNNY] = {69, 1},
    [SPECIES_BRONZONG] = {70, 1},
    [SPECIES_GARCHOMP] = {71, 1},
    [SPECIES_LUCARIO] = {72, 1},
    [SPECIES_ABOMASNOW] = {73, 1},
    [SPECIES_ELECTIVIRE] = {74, 1},
    [SPECIES_MAGMORTAR] = {75, 1},
    [SPECIES_YANMEGA] = {76, 1},
    [SPECIES_GALLADE] = {77, 1},
    [SPECIES_PROBOPASS] = {78, 1},
    [SPECIES_DUSKNOIR] = {79, 1},
    [SPECIES_FROSLASS] = {80, 1},
    [SPECIES_ROTOM] = {81, 1},
    [SPECIES_MESPRIT] = {82, 1},
    [SPECIES_AZELF] = {83, 1},
    [SPECIES_PALKIA] = {84, 1},
    [SPECIES_REGIGIGAS] = {85, 1},
    [SPECIES_GIRATINA] = {86, 1},
    [SPECIES_MANAPHY] = {87, 1},
    [SPECIES_VICTINI] = {88, 1},
    [SPECIES_ZEBSTRIKA] = {89, 1},
    [SPECIES_EXCADRILL] = {90, 1},
    [SPECIES_AUDINO] = {91, 1},
    [SPECIES_LEAVANNY] = {92, 1},
    [SPECIES_SCOLIPEDE] = {93, 1},
    [SPECIES_BASCULIN] = {94, 1},
    [SPECIES_SCRAFTY] = {95, 1},
    [SPECIES_ZOROARK] = {96, 1},
    [SPECIES_SWANNA] = {97, 1},
    [SPECIES_AMOONGUSS] = {98, 1},
    [SPECIES_EELEKTROSS] = {99, 1},
    [SPECIES_CHANDELURE] = {100, 1},
    [SPECIES_HAXORUS] = {101, 1},
    [SPECIES_STUNFISK] = {102, 1},
    [SPECIES_MIENSHAO] = {103, 1},
    [SPECIES_GOLURK] = {104, 1},
    [SPECIES_MANDIBUZZ] = {105, 1},
    [SPECIES_COBALION] = {106, 1},
    [SPECIES_TERRAKION] = {107, 1},
    [SPECIES_THUNDURUS] = {108, 1},
    [SPECIES_KYUREM] = {109, 1},
    [SPECIES_GENESECT] = {110, 1},
    [SPECIES_CHESNAUGHT] = {111, 1},
    [SPECIES_DELPHOX] = {112, 1},
    [SPECIES_GRENINJA] = {113, 1},
    [SPECIES_FLOETTE] = {114, 1},
    [SPECIES_MEOWSTIC] = {115, 1},
    [SPECIES_MALAMAR] = {116, 1},
    [SPECIES_DRAGALGE] = {117, 1},
    [SPECIES_HAWLUCHA] = {118, 1},
    [SPECIES_GOODRA] = {119, 1},
    [SPECIES_GOURGEIST] = {120, 1},
    [SPECIES_XERNEAS] = {121, 1},
    [SPECIES_YVELTAL] = {122, 1},
    [SPECIES_DIANCIE] = {123, 1},
    [SPECIES_CRABOMINABLE] = {124, 1},
    [SPECIES_LYCANROC] = {125, 1},
    [SPECIES_LURANTIS] = {126, 1},
    [SPECIES_SILVALLY] = {127, 1},
    [SPECIES_BRUXISH] = {128, 1},
    [SPECIES_DRAMPA] = {129, 1},
    [SPECIES_SOLGALEO] = {130, 1},
    [SPECIES_LUNALA] = {131, 2},
    [SPECIES_PHEROMOSA] = {133, 1},
    [SPECIES_CELESTEELA] = {134, 1},
    [SPECIES_GUZZLORD] = {135, 1},
    [SPECIES_NECROZMA] = {136, 2},
    [SPECIES_MAGEARNA] = {138, 1},
    [SPECIES_NAGANADEL] = {139, 1},
    [SPECIES_ZERAORA] = {140, 1},
    [SPECIES_RILLABOOM] = {141, 1},
    [SPECIES_CINDERACE] = {142, 2},
    [SPECIES_DREDNAW] = {144, 1},
    [SPECIES_TOXTRICITY] = {145, 1},
    [SPECIES_FALINKS] = {146, 1},
    [SPECIES_STONJOURNER] = {147, 1},
    [SPECIES_INDEEDEE] = {148, 1},
    [SPECIES_COPPERAJAH] = {149, 1},
    [SPECIES_DURALUDON] = {150, 1},
    [SPECIES_ZAMAZENTA] = {151, 1},
    [SPECIES_ETERNATUS] = {152, 2},
    [SPECIES_TATSUGIRI] = {154, 1},
    [SPECIES_FLUTTER_MANE] = {155, 1},
    [SPECIES_IRON_BUNDLE] = {156, 1},
    [SPECIES_IRON_HANDS] = {157, 1},
    [SPECIES_GLIMMORA] = {158, 1},
    [SPECIES_CHIEN_PAO] = {159, 1},
    [SPECIES_TING_LU] = {160, 1},
    [SPECIES_CHI_YU] = {161, 1},
    [SPECIES_ROARING_MOON] = {162, 1},
    [SPECIES_OGERPON] = {163, 1},
    [SPECIES_RAGING_BOLT] = {164, 2},
};

const struct VerdantBattleSetChoice gVerdantBattleSetAlternatives[] =
{
    {
        .name = _("Mega Special Attacker"),
        .preset =
        {
            .moves = {MOVE_SLUDGE_BOMB, MOVE_EARTH_POWER, MOVE_PROTECT, MOVE_GIGA_DRAIN},
            .nature = NATURE_MODEST,
            .abilitySlot = 1,
            .item = ITEM_NONE,
            .requiredItem = ITEM_VENUSAURITE,
        },
    },
    {
        .name = _("Mega X Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_DRAGON_CLAW, MOVE_DRAGON_DANCE, MOVE_FLARE_BLITZ},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_NONE,
            .requiredItem = ITEM_CHARIZARDITE_X,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_HEAT_WAVE, MOVE_SOLAR_BEAM, MOVE_WEATHER_BALL, MOVE_OVERHEAT},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_FLIP_TURN, MOVE_YAWN, MOVE_PROTECT},
            .nature = NATURE_IMPISH,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega X Physical"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_PROTECT, MOVE_VOLT_SWITCH, MOVE_VOLT_TACKLE},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_RAICHUNITE_X,
        },
    },
    {
        .name = _("Support II"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_VOLT_SWITCH, MOVE_NUZZLE, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_FOLLOW_ME, MOVE_MOONBLAST, MOVE_PROTECT, MOVE_DAZZLING_GLEAM},
            .nature = NATURE_CALM,
            .abilitySlot = 2,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_HEAT_WAVE, MOVE_SOLAR_BEAM, MOVE_OVERHEAT, MOVE_WEATHER_BALL},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_EXTREME_SPEED, MOVE_FLARE_BLITZ, MOVE_WILL_O_WISP},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker II"),
        .preset =
        {
            .moves = {MOVE_PSYCHIC, MOVE_PROTECT, MOVE_ENCORE, MOVE_HYPER_BEAM},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_SLEEP_POWDER, MOVE_PROTECT, MOVE_SLUDGE_BOMB, MOVE_ENCORE},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_ROCK_POLISH, MOVE_PROTECT, MOVE_ROCK_SLIDE, MOVE_HIGH_HORSEPOWER},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 1,
            .item = ITEM_WEAKNESS_POLICY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Trick Room II"),
        .preset =
        {
            .moves = {MOVE_TRICK_ROOM, MOVE_PROTECT, MOVE_FUTURE_SIGHT, MOVE_HYDRO_PUMP},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_QUICK_CLAW,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_DOUBLE_EDGE, MOVE_QUICK_ATTACK, MOVE_BRAVE_BIRD, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_CHOICE_BAND,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Trick Room"),
        .preset =
        {
            .moves = {MOVE_SHADOW_BALL, MOVE_SLUDGE_BOMB, MOVE_ICY_WIND, MOVE_TRICK_ROOM},
            .nature = NATURE_TIMID,
            .abilitySlot = 1,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_DOUBLE_EDGE, MOVE_ICE_PUNCH, MOVE_PROTECT},
            .nature = NATURE_BRAVE,
            .abilitySlot = 1,
            .item = ITEM_SILK_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker II"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_ICE_BEAM, MOVE_PSYCHIC, MOVE_THUNDERBOLT},
            .nature = NATURE_TIMID,
            .abilitySlot = 1,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker II"),
        .preset =
        {
            .moves = {MOVE_CLOSE_COMBAT, MOVE_PROTECT, MOVE_ROCK_SLIDE, MOVE_GIGA_IMPACT},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_WATERFALL, MOVE_DRAGON_DANCE, MOVE_PROTECT, MOVE_CRUNCH},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_NONE,
            .requiredItem = ITEM_GYARADOSITE,
        },
    },
    {
        .name = _("Mega Tailwind"),
        .preset =
        {
            .moves = {MOVE_ROCK_SLIDE, MOVE_TAILWIND, MOVE_DUAL_WINGBEAT, MOVE_ICE_FANG},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_AERODACTYLITE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_THUNDERBOLT, MOVE_HURRICANE, MOVE_TAILWIND, MOVE_HEAT_WAVE},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_BRAVE_BIRD, MOVE_SCORCHING_SANDS, MOVE_TAILWIND, MOVE_HEAT_WAVE},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Tailwind"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_DRAGON_PULSE, MOVE_TAILWIND, MOVE_HEAT_WAVE},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_DRAGONINITE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_AURA_SPHERE, MOVE_RECOVER, MOVE_PSYSTRIKE, MOVE_NASTY_PLOT},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_PSYCHIC, MOVE_NASTY_PLOT, MOVE_FIRE_BLAST, MOVE_BRAVE_BIRD},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_TRANSFORM, MOVE_COACHING, MOVE_PSYCHIC, MOVE_BRAVE_BIRD},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_ERUPTION, MOVE_PROTECT, MOVE_SCORCHING_SANDS, MOVE_HYPER_BEAM},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_CHARCOAL,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_LIQUIDATION, MOVE_ICE_PUNCH, MOVE_AQUA_JET, MOVE_ROCK_SLIDE},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_VOLT_SWITCH, MOVE_SCALD, MOVE_ICE_BEAM, MOVE_PROTECT},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_ENCORE, MOVE_SLEEP_POWDER, MOVE_ACROBATICS, MOVE_LEAF_STORM},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Trick Room II"),
        .preset =
        {
            .moves = {MOVE_TRICK_ROOM, MOVE_SCALD, MOVE_PSYCHIC, MOVE_HYPER_BEAM},
            .nature = NATURE_QUIET,
            .abilitySlot = 2,
            .item = ITEM_COLBUR_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_WIDE_GUARD, MOVE_BODY_PRESS, MOVE_HEAVY_SLAM, MOVE_ROCK_SLIDE},
            .nature = NATURE_CAREFUL,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_BULLET_PUNCH, MOVE_PROTECT, MOVE_SWORDS_DANCE, MOVE_BUG_BITE},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 1,
            .item = ITEM_NONE,
            .requiredItem = ITEM_SCIZORITE,
        },
    },
    {
        .name = _("Tailwind"),
        .preset =
        {
            .moves = {MOVE_BODY_PRESS, MOVE_ROOST, MOVE_TAILWIND, MOVE_IRON_DEFENSE},
            .nature = NATURE_IMPISH,
            .abilitySlot = 1,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_HEAT_WAVE, MOVE_PROTECT, MOVE_SUCKER_PUNCH, MOVE_SNARL},
            .nature = NATURE_HASTY,
            .abilitySlot = 1,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_DRACO_METEOR, MOVE_RAIN_DANCE, MOVE_HYDRO_PUMP},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_THUNDERBOLT, MOVE_ICY_WIND, MOVE_TRI_ATTACK, MOVE_RECOVER},
            .nature = NATURE_MODEST,
            .abilitySlot = 1,
            .item = ITEM_EVIOLITE,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_THUNDERBOLT, MOVE_CALM_MIND, MOVE_PROTECT, MOVE_HYPER_BEAM},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_ICE_BEAM, MOVE_SCALD, MOVE_CALM_MIND, MOVE_PROTECT},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_ROCK_SLIDE, MOVE_LOW_KICK, MOVE_ICE_PUNCH, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support II"),
        .preset =
        {
            .moves = {MOVE_LEAF_STORM, MOVE_TRICK_ROOM, MOVE_HELPING_HAND, MOVE_PROTECT},
            .nature = NATURE_QUIET,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker II"),
        .preset =
        {
            .moves = {MOVE_LEAF_STORM, MOVE_QUICK_GUARD, MOVE_EARTH_POWER, MOVE_ROCK_TOMB},
            .nature = NATURE_TIMID,
            .abilitySlot = 1,
            .item = ITEM_WHITE_HERB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_COACHING, MOVE_AURA_SPHERE, MOVE_HEAT_WAVE},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_WIDE_GUARD, MOVE_HIGH_HORSEPOWER, MOVE_LIQUIDATION},
            .nature = NATURE_IMPISH,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Offensive"),
        .preset =
        {
            .moves = {MOVE_ENERGY_BALL, MOVE_PROTECT, MOVE_RAIN_DANCE, MOVE_HYDRO_PUMP},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_LEAF_BLADE, MOVE_TAILWIND, MOVE_KNOCK_OFF, MOVE_FAKE_OUT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker II"),
        .preset =
        {
            .moves = {MOVE_DAZZLING_GLEAM, MOVE_PROTECT, MOVE_ENCORE, MOVE_FUTURE_SIGHT},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_HEAVY_SLAM, MOVE_FAKE_OUT, MOVE_BULLET_PUNCH, MOVE_CLOSE_COMBAT},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_PSYCH_UP, MOVE_FOUL_PLAY, MOVE_PAIN_SPLIT, MOVE_DARK_PULSE},
            .nature = NATURE_SASSY,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_SABLENITE,
        },
    },
    {
        .name = _("Physical Attacker II"),
        .preset =
        {
            .moves = {MOVE_HEAVY_SLAM, MOVE_BODY_PRESS, MOVE_ROCK_SLIDE, MOVE_ICE_PUNCH},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_EXPERT_BELT,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_CLOSE_COMBAT, MOVE_POISON_JAB, MOVE_ROCK_SLIDE},
            .nature = NATURE_BRAVE,
            .abilitySlot = 0,
            .item = ITEM_NONE,
            .requiredItem = ITEM_MEDICHAMITE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_VOLT_SWITCH, MOVE_FLAMETHROWER, MOVE_DISCHARGE, MOVE_RISING_VOLTAGE},
            .nature = NATURE_MODEST,
            .abilitySlot = 1,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_CRUNCH, MOVE_LIQUIDATION, MOVE_ICE_FANG},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_SHARPEDONITE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_SCALE_SHOT, MOVE_TAILWIND, MOVE_EARTH_POWER},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_YACHE_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Tailwind"),
        .preset =
        {
            .moves = {MOVE_HYPER_VOICE, MOVE_PROTECT, MOVE_TAILWIND, MOVE_ROOST},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_ALTARIANITE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_KNOCK_OFF, MOVE_AQUA_JET, MOVE_CRABHAMMER, MOVE_CLOSE_COMBAT},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_CHOICE_BAND,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_SUCKER_PUNCH, MOVE_PROTECT, MOVE_KNOCK_OFF, MOVE_CLOSE_COMBAT},
            .nature = NATURE_BRAVE,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_SHEER_COLD, MOVE_EXPLOSION, MOVE_TAUNT, MOVE_LIGHT_SCREEN},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_SILK_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker II"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_BULLET_PUNCH, MOVE_METEOR_MASH, MOVE_ZEN_HEADBUTT},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_REST, MOVE_STONE_EDGE, MOVE_IRON_DEFENSE, MOVE_BODY_PRESS},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_CHESTO_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_ICY_WIND, MOVE_BLIZZARD, MOVE_THUNDERBOLT},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_BLUNDER_POLICY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_RECOVER, MOVE_PROTECT, MOVE_DRACO_METEOR, MOVE_MIST_BALL},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_SOUL_DEW,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_TAILWIND, MOVE_DRACO_METEOR, MOVE_LUSTER_PURGE},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_SOUL_DEW,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_HEAT_CRASH, MOVE_PROTECT, MOVE_SWORDS_DANCE, MOVE_PRECIPICE_BLADES},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_DRAGON_ASCENT, MOVE_EARTHQUAKE, MOVE_EXTREME_SPEED, MOVE_DRAGON_DANCE},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_AGUAV_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_IRON_HEAD, MOVE_THUNDERBOLT, MOVE_TRICK, MOVE_PSYCHIC},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_FINAL_GAMBIT, MOVE_BRAVE_BIRD, MOVE_CLOSE_COMBAT, MOVE_U_TURN},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_AQUA_JET, MOVE_CLOSE_COMBAT, MOVE_GIGA_IMPACT, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_CHOICE_BAND,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_YAWN, MOVE_RECOVER, MOVE_EARTH_POWER, MOVE_ICE_BEAM},
            .nature = NATURE_MODEST,
            .abilitySlot = 1,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_CLOSE_COMBAT, MOVE_TRIPLE_AXEL, MOVE_GIGA_IMPACT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_IRON_DEFENSE, MOVE_BODY_PRESS, MOVE_TRICK_ROOM, MOVE_FUTURE_SIGHT},
            .nature = NATURE_QUIET,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_EARTHQUAKE, MOVE_DRAGON_CLAW},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_GARCHOMPITE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_CLOSE_COMBAT, MOVE_METEOR_MASH, MOVE_FINAL_GAMBIT, MOVE_BULLET_PUNCH},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_BLIZZARD, MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_AURORA_VEIL},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_EXPERT_BELT,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_ELECTROWEB, MOVE_ICE_PUNCH, MOVE_WILD_CHARGE, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_THUNDERBOLT, MOVE_FIRE_BLAST, MOVE_FOCUS_BLAST, MOVE_HEAT_WAVE},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SPECS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_BUG_BUZZ, MOVE_AIR_SLASH, MOVE_PROTECT, MOVE_TAILWIND},
            .nature = NATURE_TIMID,
            .abilitySlot = 1,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_PSYCHO_CUT, MOVE_CLOSE_COMBAT, MOVE_SACRED_SWORD},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_GALLADITE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_IRON_DEFENSE, MOVE_FLASH_CANNON, MOVE_REST, MOVE_POWER_GEM},
            .nature = NATURE_MODEST,
            .abilitySlot = 1,
            .item = ITEM_CHESTO_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_POLTERGEIST, MOVE_SHADOW_SNEAK, MOVE_WILL_O_WISP, MOVE_SHADOW_PUNCH},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_FROST_BREATH, MOVE_ICY_WIND, MOVE_DESTINY_BOND, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 1,
            .item = ITEM_WIDE_LENS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_VOLT_SWITCH, MOVE_THUNDERBOLT, MOVE_DISCHARGE, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_ICE_BEAM, MOVE_U_TURN, MOVE_PSYCHIC, MOVE_THUNDERBOLT},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SPECS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_FIRE_BLAST, MOVE_DAZZLING_GLEAM, MOVE_PSYCHIC, MOVE_U_TURN},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SPECS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_HYDRO_PUMP, MOVE_SPACIAL_REND, MOVE_THUNDER_WAVE, MOVE_FIRE_BLAST},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_SUBSTITUTE, MOVE_KNOCK_OFF, MOVE_BODY_SLAM, MOVE_SUPERPOWER},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_SHADOW_BALL, MOVE_CALM_MIND, MOVE_AURA_SPHERE},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_ICE_BEAM, MOVE_SCALD, MOVE_TAIL_GLOW, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_SEARING_SHOT, MOVE_TRICK_ROOM, MOVE_HELPING_HAND, MOVE_PROTECT},
            .nature = NATURE_QUIET,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_OVERHEAT, MOVE_PROTECT, MOVE_WILD_CHARGE, MOVE_GIGA_IMPACT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_IRON_HEAD, MOVE_PROTECT, MOVE_ROCK_SLIDE, MOVE_HIGH_HORSEPOWER},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_NONE,
            .requiredItem = ITEM_EXCADRITE,
        },
    },
    {
        .name = _("Mega Trick Room"),
        .preset =
        {
            .moves = {MOVE_DAZZLING_GLEAM, MOVE_SIMPLE_BEAM, MOVE_HYPER_VOICE, MOVE_FIRE_BLAST},
            .nature = NATURE_BOLD,
            .abilitySlot = 0,
            .item = ITEM_NONE,
            .requiredItem = ITEM_AUDINITE,
        },
    },
    {
        .name = _("Offensive"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_STICKY_WEB, MOVE_LEAF_BLADE, MOVE_X_SCISSOR},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_MEGAHORN, MOVE_POISON_JAB, MOVE_SUPERPOWER},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_FLIP_TURN, MOVE_PSYCHIC_FANGS, MOVE_AQUA_JET, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_CHOICE_BAND,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_KNOCK_OFF, MOVE_CLOSE_COMBAT, MOVE_DETECT},
            .nature = NATURE_CAREFUL,
            .abilitySlot = 2,
            .item = ITEM_CHOPLE_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_NIGHT_DAZE, MOVE_SUNNY_DAY, MOVE_ENCORE},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Offensive"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_HYDRO_PUMP, MOVE_BRAVE_BIRD, MOVE_TAILWIND},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_SPORE, MOVE_SLUDGE_BOMB, MOVE_RAGE_POWDER, MOVE_ENERGY_BALL},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_ROCKY_HELMET,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_FLAMETHROWER, MOVE_VOLT_SWITCH, MOVE_THUNDERBOLT},
            .nature = NATURE_MILD,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Trick Room"),
        .preset =
        {
            .moves = {MOVE_SHADOW_BALL, MOVE_HEAT_WAVE, MOVE_PROTECT, MOVE_TRICK_ROOM},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_NONE,
            .requiredItem = ITEM_CHANDELURITE,
        },
    },
    {
        .name = _("Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_CLOSE_COMBAT, MOVE_SWORDS_DANCE, MOVE_SCALE_SHOT, MOVE_GIGA_IMPACT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_YAWN, MOVE_FISSURE, MOVE_THUNDERBOLT},
            .nature = NATURE_IMPISH,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_CLOSE_COMBAT, MOVE_KNOCK_OFF, MOVE_U_TURN},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker II"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_POLTERGEIST, MOVE_STONE_EDGE, MOVE_SHADOW_PUNCH},
            .nature = NATURE_BRAVE,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_TAILWIND, MOVE_KNOCK_OFF, MOVE_BRAVE_BIRD, MOVE_ROOST},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 1,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_IRON_DEFENSE, MOVE_PROTECT, MOVE_CLOSE_COMBAT, MOVE_FLASH_CANNON},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_CLOSE_COMBAT, MOVE_ROCK_SLIDE, MOVE_STONE_EDGE, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_BAND,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Offensive"),
        .preset =
        {
            .moves = {MOVE_GRASS_KNOT, MOVE_PROTECT, MOVE_THUNDER_WAVE, MOVE_THUNDERBOLT},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_DRACO_METEOR, MOVE_PROTECT, MOVE_GLACIATE, MOVE_HYPER_VOICE},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_ELECTROWEB, MOVE_THUNDER_WAVE, MOVE_PROTECT, MOVE_BUG_BUZZ},
            .nature = NATURE_CALM,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_SPIKY_SHIELD, MOVE_BODY_PRESS, MOVE_WOOD_HAMMER, MOVE_GIGA_IMPACT},
            .nature = NATURE_RELAXED,
            .abilitySlot = 2,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Trick Room"),
        .preset =
        {
            .moves = {MOVE_HEAT_WAVE, MOVE_PROTECT, MOVE_PSYCHIC, MOVE_TRICK_ROOM},
            .nature = NATURE_QUIET,
            .abilitySlot = 0,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_DARK_PULSE, MOVE_ICE_BEAM, MOVE_BLIZZARD},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_NONE,
            .requiredItem = ITEM_GRENINJITE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_MOONBLAST, MOVE_DAZZLING_GLEAM, MOVE_ENERGY_BALL, MOVE_PROTECT},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_EXPANDING_FORCE, MOVE_FAKE_OUT, MOVE_DARK_PULSE},
            .nature = NATURE_HASTY,
            .abilitySlot = 2,
            .item = ITEM_LIGHT_CLAY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Trick Room"),
        .preset =
        {
            .moves = {MOVE_SUPERPOWER, MOVE_KNOCK_OFF, MOVE_TRICK_ROOM, MOVE_PROTECT},
            .nature = NATURE_BRAVE,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_SLUDGE_BOMB, MOVE_DRACO_METEOR, MOVE_FOCUS_BLAST},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_COACHING, MOVE_BRAVE_BIRD, MOVE_ENCORE, MOVE_QUICK_GUARD},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker II"),
        .preset =
        {
            .moves = {MOVE_DRACO_METEOR, MOVE_FLAMETHROWER, MOVE_DRAGON_TAIL, MOVE_PROTECT},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Trick Room"),
        .preset =
        {
            .moves = {MOVE_TRICK_ROOM, MOVE_TRICK_OR_TREAT, MOVE_POLTERGEIST, MOVE_DESTINY_BOND},
            .nature = NATURE_RELAXED,
            .abilitySlot = 1,
            .item = ITEM_OCCA_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_DAZZLING_GLEAM, MOVE_HEAL_PULSE, MOVE_THUNDER_WAVE, MOVE_PROTECT},
            .nature = NATURE_CALM,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_DARK_PULSE, MOVE_TAILWIND, MOVE_SNARL, MOVE_PROTECT},
            .nature = NATURE_CALM,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_BODY_PRESS, MOVE_TRICK_ROOM, MOVE_MOONBLAST, MOVE_DIAMOND_STORM},
            .nature = NATURE_BRAVE,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_ICE_HAMMER, MOVE_PROTECT, MOVE_CLOSE_COMBAT, MOVE_ROCK_SLIDE},
            .nature = NATURE_BRAVE,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_CLOSE_COMBAT, MOVE_ROCK_SLIDE, MOVE_PROTECT, MOVE_PSYCHIC_FANGS},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_LEAF_BLADE, MOVE_SUPERPOWER, MOVE_GIGA_IMPACT},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_HYPER_VOICE, MOVE_TAILWIND, MOVE_ICY_WIND, MOVE_PROTECT},
            .nature = NATURE_CALM,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_CRUNCH, MOVE_PSYCHIC_FANGS, MOVE_LIQUIDATION, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 1,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Special Attacker"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_HYPER_VOICE, MOVE_DRAGON_PULSE, MOVE_HEAT_WAVE},
            .nature = NATURE_QUIET,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_PROTECT, MOVE_CLOSE_COMBAT, MOVE_SUNSTEEL_STRIKE, MOVE_FLAME_CHARGE},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_WEAKNESS_POLICY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Offensive"),
        .preset =
        {
            .moves = {MOVE_METEOR_BEAM, MOVE_MOONBLAST, MOVE_MOONGEIST_BEAM, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_POWER_HERB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_MOONBLAST, MOVE_CALM_MIND, MOVE_MOONGEIST_BEAM, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_QUIVER_DANCE, MOVE_BUG_BUZZ, MOVE_FOCUS_BLAST, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_IRON_DEFENSE, MOVE_FLASH_CANNON, MOVE_PROTECT, MOVE_LEAF_STORM},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_DRACO_METEOR, MOVE_WIDE_GUARD, MOVE_SNARL, MOVE_PROTECT},
            .nature = NATURE_CALM,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Setup Sweeper"),
        .preset =
        {
            .moves = {MOVE_BRICK_BREAK, MOVE_KNOCK_OFF, MOVE_DRAGON_DANCE, MOVE_PRISMATIC_LASER},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_CALM_MIND, MOVE_PROTECT, MOVE_EARTH_POWER, MOVE_PRISMATIC_LASER},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_DAZZLING_GLEAM, MOVE_FLEUR_CANNON, MOVE_FLASH_CANNON, MOVE_AURA_SPHERE},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_DRACO_METEOR, MOVE_TAILWIND, MOVE_HELPING_HAND, MOVE_PROTECT},
            .nature = NATURE_CALM,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Support"),
        .preset =
        {
            .moves = {MOVE_DISCHARGE, MOVE_FAKE_OUT, MOVE_QUICK_GUARD, MOVE_PROTECT},
            .nature = NATURE_CALM,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_FAKE_OUT, MOVE_HIGH_HORSEPOWER, MOVE_WOOD_HAMMER, MOVE_GRASSY_GLIDE},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_U_TURN, MOVE_PYRO_BALL, MOVE_GUNK_SHOT, MOVE_HIGH_JUMP_KICK},
            .nature = NATURE_JOLLY,
            .abilitySlot = 2,
            .item = ITEM_CHOICE_BAND,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Offensive"),
        .preset =
        {
            .moves = {MOVE_U_TURN, MOVE_HIGH_JUMP_KICK, MOVE_PROTECT, MOVE_PYRO_BALL},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_ROCK_SLIDE, MOVE_LIQUIDATION, MOVE_PROTECT, MOVE_CRUNCH},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 1,
            .item = ITEM_WHITE_HERB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_OVERDRIVE, MOVE_SLUDGE_BOMB, MOVE_VOLT_SWITCH, MOVE_SNARL},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SCARF,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Physical Attacker"),
        .preset =
        {
            .moves = {MOVE_CLOSE_COMBAT, MOVE_NO_RETREAT, MOVE_PROTECT, MOVE_FIRST_IMPRESSION},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_HEAT_CRASH, MOVE_STONE_EDGE, MOVE_ROCK_SLIDE, MOVE_PROTECT},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_BAND,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_HYPER_VOICE, MOVE_EXPANDING_FORCE, MOVE_PSYSHOCK, MOVE_TRICK},
            .nature = NATURE_TIMID,
            .abilitySlot = 2,
            .item = ITEM_CHOICE_SPECS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_HEAVY_SLAM, MOVE_STONE_EDGE, MOVE_HEAT_CRASH, MOVE_HIGH_HORSEPOWER},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 2,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_IRON_DEFENSE, MOVE_PROTECT, MOVE_FLASH_CANNON, MOVE_BODY_PRESS},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_EVIOLITE,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_IRON_DEFENSE, MOVE_PROTECT, MOVE_CRUNCH, MOVE_CLOSE_COMBAT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_TOXIC_SPIKES, MOVE_DYNAMAX_CANNON, MOVE_RECOVER, MOVE_SLUDGE_BOMB},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_RECOVER, MOVE_COSMIC_POWER, MOVE_FLAMETHROWER, MOVE_DYNAMAX_CANNON},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_MUDDY_WATER, MOVE_RAPID_SPIN, MOVE_ICY_WIND, MOVE_PROTECT},
            .nature = NATURE_MODEST,
            .abilitySlot = 2,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_SHADOW_BALL, MOVE_MOONBLAST, MOVE_DAZZLING_GLEAM, MOVE_ICY_WIND},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SPECS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_HYDRO_PUMP, MOVE_FREEZE_DRY, MOVE_PROTECT, MOVE_HYPER_BEAM},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_FOCUS_SASH,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Setup"),
        .preset =
        {
            .moves = {MOVE_SWORDS_DANCE, MOVE_THUNDER_PUNCH, MOVE_PROTECT, MOVE_CLOSE_COMBAT},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_LEFTOVERS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Mega Special Attacker"),
        .preset =
        {
            .moves = {MOVE_POWER_GEM, MOVE_SLUDGE_BOMB, MOVE_SPIKY_SHIELD, MOVE_HYPER_BEAM},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_NONE,
            .requiredItem = ITEM_GLIMMORANITE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_SACRED_SWORD, MOVE_PROTECT, MOVE_SUCKER_PUNCH, MOVE_ICICLE_CRASH},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_STOMPING_TANTRUM, MOVE_RUINATION, MOVE_PROTECT, MOVE_THROAT_CHOP},
            .nature = NATURE_ADAMANT,
            .abilitySlot = 0,
            .item = ITEM_SITRUS_BERRY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Choice Attacker"),
        .preset =
        {
            .moves = {MOVE_DARK_PULSE, MOVE_OVERHEAT, MOVE_HYPER_BEAM, MOVE_PROTECT},
            .nature = NATURE_TIMID,
            .abilitySlot = 0,
            .item = ITEM_CHOICE_SPECS,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Fast Attacker"),
        .preset =
        {
            .moves = {MOVE_BREAKING_SWIPE, MOVE_JAW_LOCK, MOVE_ROCK_SLIDE, MOVE_PROTECT},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_BOOSTER_ENERGY,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_SUPERPOWER, MOVE_IVY_CUDGEL, MOVE_SPIKY_SHIELD, MOVE_THROAT_CHOP},
            .nature = NATURE_JOLLY,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Bulky Attacker"),
        .preset =
        {
            .moves = {MOVE_THUNDERCLAP, MOVE_THUNDERBOLT, MOVE_DRAGON_PULSE, MOVE_PROTECT},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_ASSAULT_VEST,
            .requiredItem = ITEM_NONE,
        },
    },
    {
        .name = _("Wallbreaker"),
        .preset =
        {
            .moves = {MOVE_THUNDERCLAP, MOVE_THUNDERBOLT, MOVE_PROTECT, MOVE_DRAGON_PULSE},
            .nature = NATURE_MODEST,
            .abilitySlot = 0,
            .item = ITEM_LIFE_ORB,
            .requiredItem = ITEM_NONE,
        },
    },
};

const u16 gVerdantFreeBattleItems[] =
{
    ITEM_BERRY_JUICE,
    ITEM_BRIGHT_POWDER,
    ITEM_WHITE_HERB,
    ITEM_QUICK_CLAW,
    ITEM_MENTAL_HERB,
    ITEM_CHOICE_BAND,
    ITEM_FOCUS_BAND,
    ITEM_SCOPE_LENS,
    ITEM_BLACK_GLASSES,
    ITEM_MYSTIC_WATER,
    ITEM_CHARCOAL,
    ITEM_SILK_SCARF,
    ITEM_LEFTOVERS,
    ITEM_POWER_HERB,
    ITEM_CHOICE_SCARF,
    ITEM_CHOICE_SPECS,
    ITEM_FOCUS_SASH,
    ITEM_WIDE_LENS,
    ITEM_ZOOM_LENS,
    ITEM_METRONOME,
    ITEM_MUSCLE_BAND,
    ITEM_WISE_GLASSES,
    ITEM_EXPERT_BELT,
    ITEM_LIGHT_CLAY,
    ITEM_DAMP_ROCK,
    ITEM_LIFE_ORB,
    ITEM_TOXIC_ORB,
    ITEM_FLAME_ORB,
    ITEM_BLACK_SLUDGE,
    ITEM_SHED_SHELL,
    ITEM_EVIOLITE,
    ITEM_ROCKY_HELMET,
    ITEM_AIR_BALLOON,
    ITEM_RED_CARD,
    ITEM_EJECT_BUTTON,
    ITEM_ABSORB_BULB,
    ITEM_CELL_BATTERY,
    ITEM_LUMINOUS_MOSS,
    ITEM_SNOWBALL,
    ITEM_WEAKNESS_POLICY,
    ITEM_ASSAULT_VEST,
    ITEM_SAFETY_GOGGLES,
    ITEM_ADRENALINE_ORB,
    ITEM_TERRAIN_EXTENDER,
    ITEM_PROTECTIVE_PADS,
    ITEM_ELECTRIC_SEED,
    ITEM_PSYCHIC_SEED,
    ITEM_MISTY_SEED,
    ITEM_GRASSY_SEED,
    ITEM_BUG_GEM,
    ITEM_FIGHTING_GEM,
    ITEM_FLYING_GEM,
    ITEM_NORMAL_GEM,
    ITEM_ROCK_GEM,
    ITEM_THROAT_SPRAY,
    ITEM_EJECT_PACK,
    ITEM_HEAVY_DUTY_BOOTS,
    ITEM_BLUNDER_POLICY,
    ITEM_ROOM_SERVICE,
    ITEM_UTILITY_UMBRELLA,
    ITEM_SOUL_DEW,
    ITEM_THICK_CLUB,
    ITEM_LEEK,
    ITEM_LIGHT_BALL,
    ITEM_BOOSTER_ENERGY,
    ITEM_NONE,
};
