#!/usr/bin/env python3
"""Generate the Mega catalogue and free evolution/form-tool catalogue."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "data" / "pokemon" / "form_change_tables.h"
OUTPUT = ROOT / "src" / "data" / "emerald_champions_mega_stones.h"
EVOLUTION_OUTPUT = ROOT / "src" / "data" / "emerald_champions_evolution_items.h"

FORM_ACCESS_ITEMS = {
    "ITEM_ROTOM_CATALOG", "ITEM_GRACIDEA", "ITEM_PRISON_BOTTLE",
    "ITEM_RED_NECTAR", "ITEM_YELLOW_NECTAR", "ITEM_PINK_NECTAR", "ITEM_PURPLE_NECTAR",
    "ITEM_ADAMANT_CRYSTAL", "ITEM_LUSTROUS_GLOBE", "ITEM_GRISEOUS_CORE",
    "ITEM_DOUSE_DRIVE", "ITEM_SHOCK_DRIVE", "ITEM_BURN_DRIVE", "ITEM_CHILL_DRIVE",
}


def stones() -> list[str]:
    values = re.findall(
        r"FORM_CHANGE_BATTLE_MEGA_EVOLUTION_ITEM,\s*SPECIES_[A-Z0-9_]+,\s*(ITEM_[A-Z0-9_]+)",
        SOURCE.read_text(),
    )
    return list(dict.fromkeys(values))


def evolution_items() -> list[str]:
    source = "\n".join(
        path.read_text()
        for path in sorted((ROOT / "src" / "data" / "pokemon" / "species_info").glob("*families.h"))
    )
    return sorted(FORM_ACCESS_ITEMS | set(re.findall(
        r"\{(?:EVO_ITEM(?:_MALE|_FEMALE|_DAY|_NIGHT)?|IF_HOLD_ITEM)\s*,\s*(ITEM_[A-Z0-9_]+)",
        source,
    )))


def main() -> None:
    values = stones()
    OUTPUT.write_text(
        "// Generated by scripts/generate_emerald_champions_mega_archive.py.\n"
        + "\n".join(f"    {item}," for item in values)
        + "\n"
    )
    evo_items = evolution_items()
    EVOLUTION_OUTPUT.write_text(
        "// Generated by scripts/generate_emerald_champions_mega_archive.py.\n"
        + "\n".join(f"    {item}," for item in evo_items)
        + "\n"
    )
    print(f"generated postgame archive with {len(values)} Mega Stones")
    print(f"generated pre-League archive with {len(evo_items)} evolution items")


if __name__ == "__main__":
    main()
