#!/usr/bin/env python3
"""Generate the Mega catalogue and free evolution/form-tool catalogue."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "data" / "pokemon" / "form_change_tables.h"
OUTPUT = ROOT / "src" / "data" / "emerald_champions_mega_stones.h"
EVOLUTION_OUTPUT = ROOT / "src" / "data" / "emerald_champions_evolution_items.h"

FORM_ACCESS_ITEMS = {
    "ITEM_ROTOM_CATALOG", "ITEM_GRACIDEA", "ITEM_PRISON_BOTTLE",
    "ITEM_RED_NECTAR", "ITEM_YELLOW_NECTAR", "ITEM_PINK_NECTAR", "ITEM_PURPLE_NECTAR",
    "ITEM_ADAMANT_CRYSTAL", "ITEM_LUSTROUS_GLOBE", "ITEM_GRISEOUS_CORE",
    "ITEM_DOUSE_DRIVE", "ITEM_SHOCK_DRIVE", "ITEM_BURN_DRIVE", "ITEM_CHILL_DRIVE",
    "ITEM_DNA_SPLICERS", "ITEM_ZYGARDE_CUBE", "ITEM_N_SOLARIZER", "ITEM_N_LUNARIZER",
    "ITEM_REINS_OF_UNITY",
}


def stones() -> list[str]:
    values = re.findall(
        r"FORM_CHANGE_BATTLE_MEGA_EVOLUTION_ITEM,\s*SPECIES_[A-Z0-9_]+,\s*(ITEM_[A-Z0-9_]+)",
        SOURCE.read_text(),
    )
    return list(dict.fromkeys(values))


def evolution_items() -> list[str]:
    source = "\n".join(
        path.read_text()
        for path in sorted((ROOT / "src" / "data" / "pokemon" / "species_info").glob("*families.h"))
    )
    return sorted(FORM_ACCESS_ITEMS | set(re.findall(
        r"\{(?:EVO_ITEM(?:_MALE|_FEMALE|_DAY|_NIGHT)?|IF_HOLD_ITEM)\s*,\s*(ITEM_[A-Z0-9_]+)",
        source,
    )))


def main() -> None:
    values = stones()
    OUTPUT.write_text(
        "// Generated by scripts/generate_emerald_champions_mega_archive.py.\n"
        + "\n".join(f"    {item}," for item in values)
        + "\n"
    )
    evo_items = evolution_items()
    EVOLUTION_OUTPUT.write_text(
        "// Generated by scripts/generate_emerald_champions_mega_archive.py.\n"
        + "\n".join(f"    {item}," for item in evo_items)
        + "\n"
    )
    for filename, items in (
        ("emerald_champions_form_items.h", sorted(FORM_ACCESS_ITEMS)),
        ("emerald_champions_paid_evolution_items.h", sorted(set(evo_items) - FORM_ACCESS_ITEMS)),
    ):
        (ROOT / "src" / "data" / filename).write_text(
            "// Generated by scripts/generate_emerald_champions_mega_archive.py.\n"
            + "\n".join(f"    {item}," for item in items) + "\n"
        )
    print(f"generated catalogue with {len(values)} Mega Stones")
    print(f"generated protection catalogue with {len(evo_items)} evolution and form items")


if __name__ == "__main__":
    main()
