#!/usr/bin/env python3
"""Generate the postgame Mega Stone archive from native form-change data."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "data" / "pokemon" / "form_change_tables.h"
OUTPUT = ROOT / "src" / "data" / "emerald_champions_mega_stones.h"
EVOLUTION_OUTPUT = ROOT / "src" / "data" / "emerald_champions_evolution_items.h"


def stones() -> list[str]:
    values = re.findall(
        r"FORM_CHANGE_BATTLE_MEGA_EVOLUTION_ITEM,\s*SPECIES_[A-Z0-9_]+,\s*(ITEM_[A-Z0-9_]+)",
        SOURCE.read_text(),
    )
    return list(dict.fromkeys(values))


def evolution_items() -> list[str]:
    source = "\n".join(
        path.read_text()
        for path in sorted((ROOT / "src" / "data" / "pokemon" / "species_info").glob("*families.h"))
    )
    return sorted(set(re.findall(
        r"\{EVO_ITEM(?:_MALE|_FEMALE|_DAY|_NIGHT)?\s*,\s*(ITEM_[A-Z0-9_]+)",
        source,
    )))


def main() -> None:
    values = stones()
    if len(values) < 90:
        raise SystemExit(f"expected the complete modern Mega roster, found {len(values)} stones")
    OUTPUT.write_text(
        "// Generated by scripts/generate_emerald_champions_mega_archive.py.\n"
        + "\n".join(f"    {item}," for item in values)
        + "\n"
    )
    evo_items = evolution_items()
    if len(evo_items) < 40:
        raise SystemExit(f"expected the complete evolution-item roster, found {len(evo_items)}")
    EVOLUTION_OUTPUT.write_text(
        "// Generated by scripts/generate_emerald_champions_mega_archive.py.\n"
        + "\n".join(f"    {item}," for item in evo_items)
        + "\n"
    )
    print(f"generated postgame archive with {len(values)} Mega Stones")
    print(f"generated pre-League archive with {len(evo_items)} evolution items")


if __name__ == "__main__":
    main()
