#!/usr/bin/env python3
"""Generate the runtime legendary/mythical species exclusion switch."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from verdant_custom_teams import LEGENDARY_FAMILIES


ROOT = Path(__file__).resolve().parents[1]
SPECIES_SOURCES = (
    ROOT / "include/constants/species.h",
    ROOT / "include/constants/verdant_gen9_species.h",
)
OUTPUT = ROOT / "src/data/pokemon/verdant_legendary_species.h"


def selected_species() -> list[str]:
    definitions = [
        definition
        for path in SPECIES_SOURCES
        for definition in re.findall(r"^#define\s+(SPECIES_[A-Z0-9_]+)\s+([^\n/]+)", path.read_text(), re.M)
    ]
    constants = [name for name, value in definitions if not value.strip().startswith("SPECIES_")]
    selected = []
    represented = set()
    for species in constants:
        name = species.removeprefix("SPECIES_")
        matches = [family for family in LEGENDARY_FAMILIES if name == family or name.startswith(family + "_")]
        if matches:
            family = max(matches, key=len)
            selected.append(species)
            represented.add(family)
    missing = sorted(set(LEGENDARY_FAMILIES) - represented)
    if missing:
        raise SystemExit(f"legendary families missing species constants: {', '.join(missing)}")
    return selected


def render(species: list[str]) -> str:
    lines = [
        "// Generated by scripts/generate_verdant_legendary_species.py. Do not edit by hand.",
        "// These case labels intentionally fall through to one shared TRUE return.",
    ]
    lines.extend(f"    case {name}:" for name in species)
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(selected_species())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("generated legendary species header is stale")
        print(f"PASS: {expected.count('case SPECIES_')} legendary and mythical species/forms classified")
    else:
        OUTPUT.write_text(expected)
        print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
