#!/usr/bin/env python3
"""Generate src/data/wild_evolution_floors.h: the lowest level each species
reaches by level-up evolution. The wild level floor (src/wild_encounter.c)
reads it so no evolved Pokemon is met below the level it evolves at, without
scanning every species per encounter."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/data/wild_evolution_floors.h"
EVO = re.compile(r"\{EVO_LEVEL(?:_BATTLE_ONLY)?,\s*(\d+),\s*(SPECIES_[A-Z0-9_]+)")

floors: dict[str, int] = {}
for path in sorted((ROOT / "src/data/pokemon/species_info").glob("*families.h")):
    for level, target in EVO.findall(path.read_text()):
        if target.endswith("_") or int(level) == 0:  # macro-built form names; level-0 rows are friendship/condition evolutions
            continue
        floors[target] = min(int(level), floors.get(target, 255))

lines = ["// Generated by scripts/generate_wild_evolution_floors.py; do not edit.",
         "static const struct { u16 species; u8 level; } sWildEvolutionFloors[] =", "{"]
lines += [f"    {{{species}, {level}}}," for species, level in sorted(floors.items())]
lines += ["};", ""]
OUT.write_text("\n".join(lines))
print(f"wrote {len(floors)} evolution floors to {OUT.relative_to(ROOT)}")
