#!/usr/bin/env python3
"""Standalone readable view of the battle/availability manifest."""
from __future__ import annotations
import html
import json
import re
from pathlib import Path


def pretty(token):
    return re.sub(r'^(SPECIES|ITEM|TRAINER)_','',token).replace('_',' ').title()


def render(manifest, out):
    out=Path(out);out.mkdir(parents=True,exist_ok=True)
    # The reader needs collection sources and battle conditions, not the
    # parser's full execution histories or collision-state snapshots.
    view={k:manifest[k] for k in ('schema_version','generated_at','scope','finale_reached')}
    view['periods']=[{k:v for k,v in p.items() if k!='source_rows'} for p in manifest['periods']]
    for period in view['periods']:
        period['state']={'cap':period['state']['cap']}
    battle_keys={'site_id','display_name','trainers','wild_species','label','command','locations',
                 'battle_number','team','source','level_note','regional_note'}
    view['battles']=[dict({k:v for k,v in b.items() if k in battle_keys},
                        paths=[{'conditions':p['conditions']} for p in b['paths']])
                     for b in manifest['battles']]
    source_keys={'species','key','kind','where','detail','price','quantity','cite','citations',
                 'requires','needs_species','needs_items','activity_requirement','campaign_scope'}
    for key in ('pokemon_sources','item_sources'):
        rows=[{k:v for k,v in r.items() if k in source_keys} for r in manifest[key]]
        view[key]=list({json.dumps(r,sort_keys=True):r for r in rows}.values())
    data=json.dumps(view,separators=(',',':')).replace('</','<\\/')
    page=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inclement Emerald 2 · Progression manifest</title>
<style>:root{color-scheme:light;--ink:#172b26;--muted:#61766f;--line:#dfe7e2;--green:#14634a;--paper:#f7faf7}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 system-ui,sans-serif}header{padding:32px max(24px,calc((100vw - 1160px)/2));background:#fff;border-bottom:1px solid var(--line)}h1{font-size:29px;letter-spacing:-.8px;line-height:1.2;margin:6px 0 12px}h2{font-size:21px;margin:0 0 14px}h3{font-size:17px;margin:0 0 8px}p{margin:8px 0}small,.muted{color:var(--muted)}.eyebrow{font-size:11px;letter-spacing:1.8px;text-transform:uppercase;font-weight:700;color:var(--green)}.wrap{max-width:1160px;margin:auto;padding:28px 24px;display:grid;grid-template-columns:220px minmax(0,1fr);gap:30px}nav{position:sticky;top:20px;align-self:start;max-height:90vh;overflow:auto}nav button{display:block;border:0;background:transparent;color:var(--muted);padding:9px 12px;width:100%;text-align:left;border-radius:6px;cursor:pointer}nav button.active{background:#e2eee6;color:var(--green);font-weight:650}.box,.battle{background:white;border:1px solid var(--line);border-radius:10px;padding:20px;margin-bottom:18px}.resources{display:grid;grid-template-columns:1fr 1fr;gap:20px}.chips{display:flex;gap:6px;flex-wrap:wrap}.chip{display:inline-block;padding:3px 8px;border:1px solid var(--line);border-radius:5px;font-size:13px;background:#fbfdfb}.meta{font-size:12px;color:var(--muted)}details{margin:8px 0}summary{cursor:pointer;color:var(--green);font-weight:550}.source{font-size:12px;color:var(--muted)}input{width:100%;border:1px solid var(--line);border-radius:7px;padding:11px 12px;font:inherit;margin:0 0 18px}a{color:var(--green)}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;padding:7px 6px;border-bottom:1px solid var(--line);vertical-align:top}.badge{display:inline-block;font-size:12px;padding:2px 8px;background:#eaf2eb;border-radius:4px}.warning{border-left:3px solid #c7a866;padding:10px 14px;background:#fff8e6}.empty{font-style:italic;color:var(--muted)}@media(max-width:760px){.wrap{display:block}.resources{grid-template-columns:1fr}nav{position:static;max-height:240px;margin-bottom:22px}}</style></head><body><header><div class="eyebrow">Inclement Emerald 2 · Source-backed reference</div><h1>What opens before the next battle</h1><p>Pokémon, items and places are introduced when their actual access opens. Optional fights and starter alternatives are shown separately.</p><p class="meta">Wild-held items, stolen items and Pickup rewards are excluded. Prices and conditional rewards remain visible. No party can contain more than one Legendary, Mythical, Ultra Beast or Paradox Pokémon.</p></header><div class="wrap"><nav id="nav"></nav><main><input id="search" type="search" placeholder="Find a Pokémon, item, trainer or place…" aria-label="Search the manifest"><div id="content"></div></main></div><script id="manifest" type="application/json">'''+data+r'''</script><script>
const M=JSON.parse(document.getElementById('manifest').textContent),$=s=>document.querySelector(s);let selected=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pretty=s=>String(s).replace(/^(SPECIES|ITEM|TRAINER)_/,'').replace(/_/g,' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const battles=new Map(M.battles.map(b=>[b.site_id,b]));
function chips(items){return items.length?'<div class="chips">'+items.map(x=>'<button type="button" class="chip" data-query="'+esc(pretty(x))+'">'+esc(pretty(x))+'</button>').join('')+'</div>':'<p class="empty">No new entries.</p>'}
function where(w){return Array.isArray(w)?`${w[0]} (${w[1]}, ${w[2]})`:w||'See prerequisite'}
function prerequisites(r){let a=[];if(r.needs_species?.length)a.push('Requires Pokémon: '+r.needs_species.map(pretty).join(', '));if(r.needs_items?.length)a.push('Requires items: '+r.needs_items.map(pretty).join(', '));if(r.activity_requirement)a.push('Activity requirement: '+JSON.stringify(r.activity_requirement));if(r.requires?.some(x=>x.length))a.push('Unlocks: '+r.requires.map(x=>x.map(pretty).join(' + ')).join(' OR '));if(r.campaign_scope)a.push(r.campaign_scope);return a.length?'<br><span class="meta">'+esc(a.join(' · '))+'</span>':''}
function sourceList(key,type){const rows=type==='pokemon'?M.pokemon_sources.filter(r=>r.species===key):M.item_sources.filter(r=>r.key===key);return rows.map(r=>'<p><strong>'+esc(where(r.where))+'</strong> · '+esc(r.kind.replace(/_/g,' '))+'<br>'+esc(r.detail||'')+prerequisites(r)+(r.price!==undefined?' · ¥'+esc(r.price):'')+'<br><span class="source">'+esc(r.cite||r.citations?.join('; '))+'</span></p>').join('')}
function resourceBox(d,title){return '<section class="box"><h2>'+esc(title)+'</h2><div class="resources"><div><h3>Pokémon <span class="badge">'+d.pokemon.length+'</span></h3>'+chips(d.pokemon)+'</div><div><h3>Items <span class="badge">'+d.items.length+'</span></h3>'+chips(d.items)+'</div></div>'+ (d.areas.length?'<details><summary>New places ('+d.areas.length+')</summary>'+chips(d.areas)+'</details>':'')+'</section>'}
function battleCard(id){const b=battles.get(id);if(!b)return '';const locations=b.locations.map(l=>l.map).filter((v,i,a)=>a.indexOf(v)===i);const title=b.display_name||b.trainers.map(pretty).join(' + ')||b.wild_species.map(pretty).join(' + ')||b.label;let body='<article class="battle"><div class="eyebrow">'+esc(b.battle_number?'Possible battle '+b.battle_number:'Battle alternative')+'</div><h3>'+esc(title)+'</h3><p class="meta">'+esc(locations.join(' · '))+' · '+esc(b.command.replace(/_/g,' '))+'</p>';if(b.team){body+='<details><summary>Opponent team and levels</summary><table><thead><tr><th>Pokémon</th><th>Item</th><th>Easy / Medium / Hard</th><th>Moves</th></tr></thead><tbody>'+b.team.map(m=>'<tr><td>'+esc(pretty(m.species))+'</td><td>'+esc(pretty(m.item))+'</td><td>'+esc(m.levels?.join(' / ')||'scales with your cap')+'</td><td>'+esc(m.moves.map(pretty).join(', '))+'</td></tr>').join('')+'</tbody></table></details>'}body+='<details><summary>Exact unlock conditions and source</summary><p class="source">'+esc(b.source)+'</p>'+b.paths.map(p=>'<p>'+p.conditions.map(c=>esc(`${c.key} ${c.op} ${c.value}`)).join('<br>')+'</p>').join('')+'</details>';return body+'</article>'}
function draw(){const q=$('#search').value.trim().toLowerCase();let body='';if(q){const pokemon=[...new Set(M.pokemon_sources.map(r=>r.species))].filter(x=>pretty(x).toLowerCase().includes(q));const items=[...new Set(M.item_sources.map(r=>r.key))].filter(x=>pretty(x).toLowerCase().includes(q));body='<h2>Search results</h2>'+pokemon.map(k=>'<section class="box"><h3>'+esc(pretty(k))+'</h3>'+sourceList(k,'pokemon')+'</section>').join('')+items.map(k=>'<section class="box"><h3>'+esc(pretty(k))+'</h3>'+sourceList(k,'item')+'</section>').join('');body+=M.battles.filter(b=>JSON.stringify([b.display_name,b.trainers,b.locations]).toLowerCase().includes(q)).map(b=>battleCard(b.site_id)).join('');if(!body.includes('class="box"')&&!body.includes('class="battle"'))body+='<p class="empty">No matches.</p>'}else{const p=M.periods[selected];body='<h2>'+esc(p.label)+'</h2><p class="meta">Level cap '+p.state.cap+' · Optional battles within a frontier may be taken in different orders.</p>'+resourceBox(p.new,selected?'New resources since the previous frontier':'Available before the first rival');body+='<h2>Possible next battles</h2>'+p.battles.map(battleCard).join('');body+='<h2>What each victory opens</h2>';for(const a of p.after_victory){const b=battles.get(a.battle);body+='<details class="box"><summary>'+esc(b?.display_name||b?.trainers.map(pretty).join(' + ')||a.battle)+'</summary>'+resourceBox(a.new,'After this victory')+'<p class="meta">Already completed in this reference order: '+esc(a.reference_previous_victories.map(pretty).join(', ')||'none')+'</p></details>'}body+='<details class="box"><summary>Full collection available at this frontier</summary>'+resourceBox(p.available,'Available collection')+'</details>'}$('#content').innerHTML=body;$('#nav').innerHTML='<div class="eyebrow">Progression</div>'+M.periods.map((p,i)=>'<button class="'+(i===selected?'active':'')+'" data-stage="'+i+'">'+esc(p.label)+'</button>').join('')+'<hr><a href="manifest.json">Download full JSON manifest</a>';document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.stage);$('#search').value='';draw();window.scrollTo(0,0)})}
$('#search').addEventListener('input',draw);document.addEventListener('click',e=>{const b=e.target.closest('[data-query]');if(b){$('#search').value=b.dataset.query;draw();window.scrollTo(0,0)}});draw();
</script></body></html>'''
    (out/'index.html').write_text(page)
    return out/'index.html'
