#!/usr/bin/env python3
"""The story machine's build-side tool. data/progression/story.yaml is the only place
that says what exists when; this reads the maps and scripts and holds them to it.

  story.py generate           write include/constants/story.h and src/data/story.h
  story.py maps               write map.json object/trigger/sign lists from data/progression/maps
  story.py import ID MAP...   one-time: read these maps into data/progression/maps, numbering
                              their entities from ID
  story.py inventory MAP...   list every entity on these maps and every exchange its
                              scripts make (bootstrap for a region's registry entries)

Every step S also gets STORY_REACHED_S, a window open before S: as a flag it reads set
once the story has reached S. Old progress flags become aliases of these.

Windows: a window is open from step `from` (inclusive) until step `until` (exclusive;
omitted = forever). A window id is a flag id in the story range: FlagGet(id) is TRUE
when the window is CLOSED, so an object whose flag is a window is present only inside
it, and a trigger whose var is a window with var_value 0 fires only inside it.
"""
import glob, json, re, sys
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
STORY = ROOT / 'data/progression/story.yaml'
STORY_WINDOWS_START = 0x6000          # above TESTING_FLAGS (0x5000); below SPECIAL_VARS (0x8000)
PLAYERS = {None: 0, 'male': 1, 'female': 2}


def load_story():
    d = yaml.safe_load(open(STORY))
    steps = d['steps']
    if len(set(steps)) != len(steps):
        raise SystemExit('story.yaml: duplicate step')
    index = {s: i for i, s in enumerate(steps)}
    windows = d.get('windows') or []
    windows = windows + [{'id': f'REACHED_{s}', 'from': steps[0], 'until': s} for s in steps[1:]]
    seen = set()
    for w in windows:
        if w['id'] in seen: raise SystemExit(f"story.yaml: duplicate window {w['id']}")
        seen.add(w['id'])
        if w.get('never'):
            w['from'] = w['until'] = steps[0]
            continue
        for k in ('from', 'until'):
            if w.get(k) is not None and w[k] not in index:
                raise SystemExit(f"story.yaml: window {w['id']}: unknown step {w[k]}")
        if w.get('until') is not None and index[w['until']] <= index[w['from']] and not w['id'].startswith('REACHED_'):
            raise SystemExit(f"story.yaml: window {w['id']} closes before it opens")
        if w.get('player') not in PLAYERS:
            raise SystemExit(f"story.yaml: window {w['id']}: player must be male or female")
    return steps, index, windows


def write_if_changed(path, text):
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def all_entities():
    for f in sorted(MAPS.glob('*.yaml')):
        d = yaml.safe_load(open(f))
        for e in d['entities']:
            yield d['map'], e


DONE_FLAGS = ROOT / 'data/progression/done_flags.yaml'


def done_flag_defines():
    """Entities marked `once` get a save flag from the free pool (FLAG_UNUSED_* in flags.h).
    The allocation is persisted append-only in done_flags.yaml so saves keep their meaning."""
    alloc = (yaml.safe_load(open(DONE_FLAGS)) or {}) if DONE_FLAGS.exists() else {}
    free = [m.group(1) for m in re.finditer(r'^#define (FLAG_UNUSED_0x[0-9A-F]+)\s', (ROOT / 'include/constants/flags.h').read_text(), re.M)]
    free = [f for f in free if f not in alloc.values()]
    changed = False
    for _, e in all_entities():
        if e.get('once') and e['id'] not in alloc:
            if not free: raise SystemExit('story.py: no free flags left for `once` entities')
            alloc[e['id']] = free.pop(0); changed = True
    if changed:
        DONE_FLAGS.write_text('# Generated, append-only: entity id -> its save flag (scripts/story.py). Do not edit.\n'
                              + yaml.safe_dump(alloc, sort_keys=True))
    return [f'#define FLAG_STORY_E{i}_DONE {f}' for i, f in sorted(alloc.items())]


GIFT_BUFFER = re.compile(r'\{GIFT_(\d)\}')


def game_string(text):
    """YAML text -> .string lines. {GIFT_n} shows the n-th gift's name (buffered at runtime)."""
    text = GIFT_BUFFER.sub(lambda m: '{STR_VAR_' + m.group(1) + '}', text)
    parts = re.split(r'(?<=\\[npl])', text)
    out = [f'\t.string "{p}"' for p in parts if p]
    out[-1] = out[-1][:-1] + '$"'
    return out


def entity_scripts():
    """Each entity's reward, name buffer and text, generated from its entry. Scenes call
    these (npc_reward, npc_say); hand-written scripts never give, set or advance."""
    out = ['@ Generated by scripts/story.py from data/progression/maps. Do not edit.', '']
    for mapid, e in all_entities():
        gives, text, adv = e.get('gives') or [], e.get('text') or {}, e.get('advances')
        if not (gives or text or adv or e.get('once')):
            continue
        n = e['id']
        out += [f'@ entity {n} on {mapid}', f'Story_E{n}_Buffer::']
        for i, g in enumerate(gives[:3], 1):
            what = g.split()[0]
            out.append(f'\tbufferspeciesname STR_VAR_{i}, {what}' if what.startswith('SPECIES_') else f'\tbufferitemname STR_VAR_{i}, {what}')
        out += ['\treturn', f'Story_E{n}_Reward::', f'\tsetvar VAR_RESULT, TRUE']
        for g in gives:
            what, *rest = g.split()
            if what.startswith('ITEM_'):
                out.append(f'\tcheckitemspace {what}, {rest[0] if rest else 1}')
                out.append('\tgoto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull')
        for g in gives:
            what, *rest = g.split()
            if what.startswith('ITEM_'):
                out.append(f'\tgiveitem {what}, {rest[0] if rest else 1}')
            elif what.startswith('SPECIES_'):
                out.append(f'\tgivemon {what}, {rest[0]}')
            else:
                raise SystemExit(f'entity {n}: cannot give {g}')
        if e.get('once'):
            out.append(f'\tsetflag FLAG_STORY_E{n}_DONE')
        if adv:
            out.append(f'\tadvance_story {adv}')
        out += ['\tsetvar VAR_RESULT, TRUE', '\treturn']
        for key, t in text.items():
            out += [f'Story_E{n}_Text_{key}:'] + game_string(t)
        out.append('')
    return '\n'.join(out) + '\n'


def generate():
    steps, index, windows = load_story()
    h = ['// Generated by scripts/story.py from data/progression/story.yaml. Do not edit.',
         '#ifndef GUARD_CONSTANTS_STORY_H', '#define GUARD_CONSTANTS_STORY_H', '']
    for i, s in enumerate(steps):
        h.append(f'#define STORY_STEP_{s} {i}')
    h += [f'#define STORY_STEP_COUNT {len(steps)}', '',
          f'#define STORY_WINDOWS_START 0x{STORY_WINDOWS_START:X}']
    for i, w in enumerate(windows):
        h.append(f"#define STORY_{w['id']} (STORY_WINDOWS_START + {i})")
    h += [f'#define STORY_WINDOWS_COUNT {len(windows)}', '',
          '// Every entity: its position, and for objects its local id (data/progression/maps).']
    for mapid, e in all_entities():
        h.append(f"#define STORY_E{e['id']}_X {e['at'][0]}")
        h.append(f"#define STORY_E{e['id']}_Y {e['at'][1]}")
        if 'name' in e:
            h.append(f"#define STORY_E{e['id']} LOCALID_{e['name']}")
    h += ['', '#endif // GUARD_CONSTANTS_STORY_H', '']
    c = ['// Generated by scripts/story.py from data/progression/story.yaml. Do not edit.',
         'const struct StoryWindow gStoryWindows[STORY_WINDOWS_COUNT + 1] =', '{']
    for w in windows:
        until = (f"STORY_STEP_{w['until']}" if w.get('until') is not None else 'STORY_STEP_COUNT')
        c.append(f"    [STORY_{w['id']} - STORY_WINDOWS_START] = {{STORY_STEP_{w['from']}, {until}, {PLAYERS[w.get('player')]}}},")
    c += ['};', '', 'const u8 *const gStoryStepNames[STORY_STEP_COUNT] =', '{']
    for s in steps:
        c.append(f'    [STORY_STEP_{s}] = (const u8 *)"{s}",')
    c += ['};', '']
    h.insert(-2, '')
    for line in done_flag_defines():
        h.insert(-2, line)
    write_if_changed(ROOT / 'data/scripts/story_entities.inc', entity_scripts())
    for path, lines in ((ROOT / 'include/constants/story.h', h), (ROOT / 'src/data/story.h', c)):
        text = '\n'.join(lines)
        if not path.exists() or path.read_text() != text:
            path.write_text(text)

# Script commands that move something between the player and the world. Each is an
# exchange the registry must declare. Pattern -> (kind, how to render the arguments).
EXCHANGES = [
    (re.compile(r'^\s*(giveitem|additem|finditem)\s+(\w+)(?:\s*,\s*(\w+))?'), 'item_in'),
    (re.compile(r'^\s*removeitem\s+(\w+)(?:\s*,\s*(\w+))?'), 'item_out'),
    (re.compile(r'^\s*(givemon|giveegg)\s+(\w+)(?:\s*,\s*(\w+))?'), 'mon_in'),
    (re.compile(r'^\s*(addmoney|removemoney)\s+(\w+)'), 'money'),
    (re.compile(r'^\s*(addcoins|removecoins)\s+(\w+)'), 'coins'),
    (re.compile(r'^\s*trainerbattle\w*\s+(\w+)'), 'battle'),
    (re.compile(r'^\s*(pokemart|pokemartdecoration\w*)\s+(\w+)'), 'shop'),
    (re.compile(r'^\s*special\s+(\w*(?:Trade|Tutor|MoveRelearner|ChooseStarter|BattleVendor|Exchange|Buy|Sell|Give|Gift)\w*)'), 'special'),
    (re.compile(r'^\s*callnative\s+(\w+)'), 'native'),
    (re.compile(r'^\s*(setflag|clearflag)\s+(\w+)'), 'flag'),
    (re.compile(r'^\s*setvar\s+(VAR_(?!TEMP|RESULT|0x)\w+)\s*,\s*(\w+)'), 'var'),
    (re.compile(r'^\s*(addvar|subvar)\s+(VAR_(?!TEMP|RESULT|0x)\w+)\s*,\s*(\w+)'), 'var'),
]


class Scripts:
    """Every script label in the game, with the label its body falls into."""
    def __init__(self):
        self.body, self.after, self.file = {}, {}, {}
        for f in sorted(glob.glob(str(ROOT / 'data/maps/*/scripts.inc')) + glob.glob(str(ROOT / 'data/scripts/*.inc'))):
            cur = None
            for line in open(f, errors='ignore'):
                m = re.match(r'^(\w+)::?', line)
                if m:
                    if cur: self.after[cur] = m.group(1)
                    cur = m.group(1); self.body[cur] = []; self.file[cur] = f
                elif cur:
                    self.body[cur].append(line.split('@')[0].rstrip())

    def graph(self, label):
        """Labels reachable from label by goto/call/fallthrough, in visit order."""
        out, todo, seen = [], [label], set()
        while todo:
            l = todo.pop(0)
            if l in seen or l not in self.body: continue
            seen.add(l); out.append(l)
            lines = [x for x in self.body[l] if x.strip()]
            for x in lines:
                for j in re.findall(r'^\s*(?:goto|call)\w*\s+(?:[^\n]*,\s*)?(\w+)\s*$', x):
                    todo.append(j)
                for j in re.findall(r'\bcase\s+[^,\n]+,\s*(\w+)', x):
                    todo.append(j)
            if not lines or not re.match(r'\s*(end\b|return\b|goto\s|step_end|\.)', lines[-1]):
                if l in self.after: todo.append(self.after[l])
        return out

    def exchanges(self, label):
        found = []
        for l in self.graph(label):
            for x in self.body[l]:
                for pat, kind in EXCHANGES:
                    m = pat.match(x)
                    if m:
                        found.append((kind, ' '.join(g for g in m.groups() if g)))
        uniq = []
        for e in found:
            if e not in uniq: uniq.append(e)
        return uniq


def map_dir(name):
    """MAP_ROUTE101 or Route101 -> data/maps/Route101."""
    if not name.startswith('MAP_'):
        return ROOT / 'data/maps' / name
    for d in glob.glob(str(ROOT / 'data/maps/*/map.json')):
        if json.load(open(d))['id'] == name:
            return Path(d).parent
    raise SystemExit(f'unknown map {name}')


def entities(mdir):
    m = json.load(open(mdir / 'map.json'))
    for i, o in enumerate(m.get('object_events') or [], 1):
        kind = ('trainer' if o.get('trainer_type', 'TRAINER_TYPE_NONE') not in ('TRAINER_TYPE_NONE', '0')
                else 'item' if 'ITEM_BALL' in o['graphics_id']
                else 'berry_tree' if 'BERRY_TREE' in o['graphics_id']
                else 'obstacle' if o['script'] in ('EventScript_CutTree', 'EventScript_RockSmash', 'EventScript_StrengthBoulder')
                else 'npc')
        yield dict(kind=kind, index=i, local_id=o.get('local_id', ''), x=o['x'], y=o['y'],
                   gfx=o['graphics_id'].replace('OBJ_EVENT_GFX_', ''), script=o['script'], flag=o['flag'])
    for c in m.get('coord_events') or []:
        if c['type'] == 'trigger':
            yield dict(kind='trigger', x=c['x'], y=c['y'], script=c['script'], var=c['var'], value=c['var_value'])
    for b in m.get('bg_events') or []:
        if b['type'] == 'hidden_item':
            yield dict(kind='hidden_item', x=b['x'], y=b['y'], item=b['item'], flag=b['flag'])
        else:
            yield dict(kind='sign', x=b['x'], y=b['y'], script=b.get('script', ''))
    for i, w in enumerate(m.get('warp_events') or []):
        yield dict(kind='warp', x=w['x'], y=w['y'], dest=w['dest_map'])


def conditions(maps):
    """Every condition reachable from these maps' entities and map scripts, by subject."""
    s = Scripts()
    sites = {}
    roots = []
    for name in maps:
        mdir = map_dir(name)
        m = json.load(open(mdir / 'map.json'))
        for o in m.get('object_events') or []:
            if o.get('flag', '0') != '0': sites.setdefault(('object-flag', o['flag']), set()).add(f"{m['name']} object {o.get('local_id', '')}@{o['x']},{o['y']}")
            roots.append(o['script'])
        for c in m.get('coord_events') or []:
            if c['type'] == 'trigger':
                sites.setdefault(('trigger-var', c['var']), set()).add(f"{m['name']} trigger @{c['x']},{c['y']} == {c['var_value']}")
                roots.append(c['script'])
        for b in m.get('bg_events') or []:
            if b['type'] == 'hidden_item': sites.setdefault(('hidden-flag', b['flag']), set()).add(f"{m['name']} hidden {b['item']}")
            else: roots.append(b.get('script', ''))
        roots += [l for l in s.body if s.file[l] == str(mdir / 'scripts.inc')]
    seen = set()
    for root in roots:
        for l in s.graph(root):
            if l in seen: continue
            seen.add(l)
            body = s.body[l]
            for i, x in enumerate(body):
                for pat, f in COND:
                    mt = pat.match(x)
                    if not mt: continue
                    kind, subj = f(mt)
                    if kind == 'var' and subj == 'VAR_RESULT':
                        before = '\n'.join(body[max(0, i - 6):i])
                        kind, subj = ('choice', 'VAR_RESULT') if CHOICE.search(before) else ('result', 'VAR_RESULT')
                    if kind in ('var', 'flag') and SCRATCH.match(subj): kind = 'scratch'
                    sites.setdefault((kind, subj), set()).add(l)
                    break
    order = ['object-flag', 'trigger-var', 'hidden-flag', 'flag', 'var', 'bag', 'money', 'player', 'special', 'result', 'choice', 'scratch']
    for kind in order:
        keys = sorted(k for k in sites if k[0] == kind)
        if not keys: continue
        print(f'\n## {kind} ({len(keys)})')
        for k in keys:
            where = sorted(sites[k])
            print(f'  {k[1]}  [{len(where)}]  ' + ', '.join(where[:4]) + (' ...' if len(where) > 4 else ''))


def inventory(maps):
    s = Scripts()
    for name in maps:
        mdir = map_dir(name)
        mid = json.load(open(mdir / 'map.json'))['id']
        print(f'\n# {mid}')
        for e in entities(mdir):
            ex = s.exchanges(e['script']) if e.get('script') and e['script'] not in ('0x0', 'NULL') else []
            head = {k: v for k, v in e.items()}
            print('-', json.dumps(head))
            for kind, args in ex:
                print(f'    {kind}: {args}')
        # Map scripts (on-load, on-frame) run with no entity; they can still change the world.
        ms = f"{mdir.name}_MapScripts"
        if ms in s.body:
            for l in s.graph(ms)[1:]:
                pass
        for l, body in s.body.items():
            if s.file[l] == str(mdir / 'scripts.inc') and re.search(r'_On(Transition|Load|Frame|Resume|WarpInto|Return)', l):
                ex = s.exchanges(l)
                if ex:
                    print('- {"kind": "map_script", "script": "%s"}' % l)
                    for kind, args in ex:
                        print(f'    {kind}: {args}')


MAPS = ROOT / 'data/progression/maps'

# Conditions: every place a script tests something. On a story map, each must be the
# story step, a window, scene-local scratch, a player choice or trait, or a declared gate.
SCRATCH = re.compile(r'^(VAR_TEMP_\w+|VAR_0x[0-9A-F]+|FLAG_TEMP_\w+|VAR_FACING|VAR_LAST_TALKED)$')
COND = [
    (re.compile(r'^\s*(goto|call)_if_(set|unset)\s+(\w+)'), lambda m: ('flag', m.group(3))),
    (re.compile(r'^\s*checkflag\s+(\w+)'), lambda m: ('flag', m.group(1))),
    (re.compile(r'^\s*compare\s+(\w+)\s*,'), lambda m: ('var', m.group(1))),
    (re.compile(r'^\s*(goto|call)_if_(eq|ne|lt|ge|le|gt)\s+(\w+)\s*,\s*[^,]+,'), lambda m: ('var', m.group(3))),
    (re.compile(r'^\s*switch\s+(\w+)'), lambda m: ('var', m.group(1))),
    (re.compile(r'^\s*map_script_2\s+(\w+)\s*,'), lambda m: ('var', m.group(1))),
    (re.compile(r'^\s*(checkitem|checkitemspace|checkpcitem|checkdecor|checkdecorspace)\s+(\w+)'), lambda m: ('bag', m.group(1) + ' ' + m.group(2))),
    (re.compile(r'^\s*(checkmoney|checkcoins)\b'), lambda m: ('money', m.group(1))),
    (re.compile(r'^\s*(checkpartymove|getpartysize|checkplayergender|checktrainerflag|checkfieldmove)\b\s*(\w*)'), lambda m: ('player', (m.group(1) + ' ' + m.group(2)).strip())),
    (re.compile(r'^\s*(special|specialvar\s+\w+\s*,)\s*(\w+)'), lambda m: ('special', m.group(2))),
    (re.compile(r'^\s*callnative\s+(\w+)'), lambda m: ('special', m.group(1))),
]
CHOICE = re.compile(r'MSGBOX_YESNO|yesnobox|multichoice|ShowScrollableMultichoice|ChooseStarter|ChoosePartyMon|ChooseMonFor|ScrollableMultichoice|ShowNatureGirl')
OBJ_DEFAULT = dict(elevation=3, movement_type='MOVEMENT_TYPE_FACE_DOWN', movement_range_x=0, movement_range_y=0,
                   trainer_type='TRAINER_TYPE_NONE', trainer_sight_or_berry_tree_id='0', script='0x0', flag='0')
KIND_OF_GFX = (('ITEM_BALL', 'item'), ('BERRY_TREE', 'berry_tree'), ('CUTTABLE_TREE', 'obstacle'), ('BREAKABLE_ROCK', 'obstacle'),
               ('PUSHABLE_BOULDER', 'obstacle'))


def _flow(d):
    """One-line YAML mapping for an entity (keeps each entity on one line)."""
    return yaml.safe_dump(d, default_flow_style=True, sort_keys=False, width=10**6).strip()


def import_maps(first_id, names):
    """Map files -> entity files. Lossless: `story.py maps` must write the same map.json back."""
    MAPS.mkdir(parents=True, exist_ok=True)
    n = first_id
    for name in names:
        mdir = map_dir(name)
        m = json.load(open(mdir / 'map.json'))
        out = [f"# {m['name']}: every object, trigger, sign and hidden item on this map. map.json's",
               '# object_events, coord_events and bg_events are generated from this file (scripts/story.py).',
               f"map: {m['id']}", 'entities:']
        prefix = m['id'][4:]
        used = set()
        for o in m.get('object_events') or []:
            gfx = o['graphics_id']
            kind = next((k for g, k in KIND_OF_GFX if g in gfx), 'trainer' if o.get('trainer_type', 'TRAINER_TYPE_NONE') != 'TRAINER_TYPE_NONE' else 'npc')
            e = {'id': n, 'kind': kind}
            if 'local_id' in o:
                name = o['local_id'][len('LOCALID_'):]
            else:
                base = name = f"{prefix}_{gfx.replace('OBJ_EVENT_GFX_', '')}"
                k2 = 2
                while name in used:
                    name = f'{base}_{k2}'; k2 += 1
            used.add(name)
            e['name'] = name
            e['at'] = [o['x'], o['y']]
            e['sprite'] = gfx.replace('OBJ_EVENT_GFX_', '')
            for k, dv in OBJ_DEFAULT.items():
                if k in ('script', 'flag'): continue
                v = o.get(k, dv)
                if v != dv: e[k] = v
            e['script'] = o['script']
            e['when'] = o['flag']
            out.append('  - ' + _flow(e)); n += 1
        for c in m.get('coord_events') or []:
            e = {'id': n, 'kind': 'trigger' if c['type'] == 'trigger' else c['type'], 'at': [c['x'], c['y']]}
            if c.get('elevation', 3) != 3: e['elevation'] = c['elevation']
            for k in c:
                if k not in ('type', 'x', 'y', 'elevation'): e[k] = c[k]
            out.append('  - ' + _flow(e)); n += 1
        for b in m.get('bg_events') or []:
            e = {'id': n, 'kind': 'hidden_item' if b['type'] == 'hidden_item' else b['type'], 'at': [b['x'], b['y']]}
            for k in b:
                if k not in ('type', 'x', 'y'): e[k] = b[k]
            out.append('  - ' + _flow(e)); n += 1
        for w in m.get('warp_events') or []:
            e = {'id': n, 'kind': 'warp', 'at': [w['x'], w['y']]}
            for k in w:
                if k not in ('x', 'y'): e[k] = w[k]
            out.append('  - ' + _flow(e)); n += 1
        (MAPS / f"{m['name']}.yaml").write_text('\n'.join(out) + '\n')
        print(f"{m['name']}: ids up to {n - 1}")


def write_maps():
    """data/progression/maps/*.yaml -> map.json object_events, coord_events, bg_events."""
    seen = {}
    for f in sorted(MAPS.glob('*.yaml')):
        d = yaml.safe_load(open(f))
        mdir = map_dir(d['map'])
        m = json.load(open(mdir / 'map.json'))
        objs, coords, bgs, warps = [], [], [], []
        for e in d['entities']:
            if e['id'] in seen: raise SystemExit(f"entity {e['id']} in {f.name} and {seen[e['id']]}")
            seen[e['id']] = f.name
            k = e['kind']
            if k in ('npc', 'trainer', 'item', 'berry_tree', 'obstacle'):
                o = {'local_id': 'LOCALID_' + e['name']}
                o['graphics_id'] = 'OBJ_EVENT_GFX_' + e['sprite']
                o['x'], o['y'] = e['at']
                for key, dv in OBJ_DEFAULT.items():
                    if key == 'script': o[key] = e['script']
                    elif key == 'flag': o[key] = when_flag(e['when'])
                    else: o[key] = e.get(key, dv)
                objs.append(o)
            elif k == 'warp':
                w = {'x': e['at'][0], 'y': e['at'][1]}
                w.update({key: v for key, v in e.items() if key not in ('id', 'kind', 'at')})
                warps.append(w)
            elif k in ('trigger', 'weather'):
                c = {'type': k, 'x': e['at'][0], 'y': e['at'][1], 'elevation': e.get('elevation', 3)}
                c.update({key: v for key, v in e.items() if key not in ('id', 'kind', 'at', 'elevation')})
                coords.append(c)
            else:
                b = {'type': 'hidden_item' if k == 'hidden_item' else k, 'x': e['at'][0], 'y': e['at'][1]}
                b.update({key: v for key, v in e.items() if key not in ('id', 'kind', 'at')})
                bgs.append(b)
        m['object_events'], m['warp_events'], m['coord_events'], m['bg_events'] = objs, warps, coords, bgs
        old = (mdir / 'map.json').read_text()
        text = json.dumps(m, indent=2, ensure_ascii=False) + ('\n' if old.endswith('\n') else '')
        if old != text:
            (mdir / 'map.json').write_text(text)


def when_flag(when):
    """An entity's `when`: a story window id, or (unconverted) a legacy flag, or 0 = always."""
    if when in (0, '0', 'always', None): return '0'
    return when if str(when).startswith(('FLAG_', 'STORY_')) else f'STORY_{when}'


if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] == 'generate':
        generate()
    elif len(sys.argv) == 2 and sys.argv[1] == 'maps':
        write_maps()
    elif len(sys.argv) >= 4 and sys.argv[1] == 'import':
        import_maps(int(sys.argv[2]), sys.argv[3:])
    elif len(sys.argv) >= 2 and sys.argv[1] == 'conditions':
        conditions(sys.argv[2:])
    elif len(sys.argv) >= 2 and sys.argv[1] == 'inventory':
        inventory(sys.argv[2:])
    else:
        print(__doc__); sys.exit(2)
