PetalburgWoods_3_MapScripts::
	.byte 0

PetalburgWoods_3_EventScript_Ranger::
	msgbox PetalburgWoods_3_Text_Ranger, MSGBOX_NPC
	end
PetalburgWoods_3_Text_Ranger:
	.string "CELEBI has been slipping between\n"
	.string "the trees. With the STONE BADGE,\l"
	.string "you can find it in this grove's\l"
	.string "grass.\p"
	.string "It has a 1% encounter chance.\n"
	.string "SWEET SCENT raises it to 25%.$"
