#ifndef GUARD_EMERALD_CHAMPIONS_HEADLESS_H
#define GUARD_EMERALD_CHAMPIONS_HEADLESS_H

#include "global.h"

enum EmeraldChampionsHeadlessScenario
{
    EC_HEADLESS_SCENARIO_NONE,
    EC_HEADLESS_SCENARIO_CENTER_OLDALE,
    EC_HEADLESS_SCENARIO_CENTER_LAVARIDGE,
    EC_HEADLESS_SCENARIO_ABILITY_MENU,
    EC_HEADLESS_SCENARIO_OPTIONS,
    EC_HEADLESS_SCENARIO_BATTLE_VENDOR,
    EC_HEADLESS_SCENARIO_MOVE_SPECIALIST,
    EC_HEADLESS_SCENARIO_THUNDURUS,
    EC_HEADLESS_SCENARIO_TORNADUS,
    EC_HEADLESS_SCENARIO_LANDORUS,
    EC_HEADLESS_SCENARIO_GAME_CORNER,
    EC_HEADLESS_SCENARIO_CIRCUIT_LOBBY,
    EC_HEADLESS_SCENARIO_LEVELER,
    EC_HEADLESS_SCENARIO_ALL_LEGAL_MOVES,
    EC_HEADLESS_SCENARIO_ALL_LEGAL_MOVES_MEW,
    EC_HEADLESS_SCENARIO_WILD_ACTION_MENU,
    EC_HEADLESS_SCENARIO_MOVE_DETAILS,
    EC_HEADLESS_SCENARIO_MOVE_SPECIALIST_CURRENT_SET,
    EC_HEADLESS_SCENARIO_NAMING,
    EC_HEADLESS_SCENARIO_STORAGE,
    EC_HEADLESS_SCENARIO_STARTER_REGIONS,
    EC_HEADLESS_SCENARIO_CIRCUIT_ROOM,
    EC_HEADLESS_SCENARIO_MOVE_ANIMATION,
    EC_HEADLESS_SCENARIO_POKEDEX,
    EC_HEADLESS_SCENARIO_SUMMARY,
    EC_HEADLESS_SCENARIO_BAG,
    EC_HEADLESS_SCENARIO_FRONTIER_PASS,
    EC_HEADLESS_SCENARIO_EMBER_PATH_WARDEN,
    EC_HEADLESS_SCENARIO_SPECIES_OVERWORLD,
    EC_HEADLESS_SCENARIO_DOUBLE_STATUS_ABILITY,
    EC_HEADLESS_SCENARIO_MEGA,
    EC_HEADLESS_SCENARIO_PRIMALS,
    EC_HEADLESS_SCENARIO_SAFARI,
    EC_HEADLESS_SCENARIO_TITLE,
    EC_HEADLESS_SCENARIO_BIRCH,
    EC_HEADLESS_SCENARIO_POKEBLOCK,
    EC_HEADLESS_SCENARIO_TRAINER_CARD,
    EC_HEADLESS_SCENARIO_DOME_INFO,
    EC_HEADLESS_SCENARIO_CONTEST_RESULTS,
    EC_HEADLESS_SCENARIO_SLOT_MACHINE,
    EC_HEADLESS_SCENARIO_FAIRY_SUMMARY,
    EC_HEADLESS_SCENARIO_SPECIES_OVERWORLD_BACKGROUND,
    EC_HEADLESS_SCENARIO_MAGMA_SPARKLE,
    EC_HEADLESS_SCENARIO_FURFROU_TRIMS,
    EC_HEADLESS_SCENARIO_HEAL_LOCATION_WHITEOUT,
    EC_HEADLESS_SCENARIO_HALL_OF_FAME_RECORD,
    EC_HEADLESS_SCENARIO_MULTI_CORRIDOR_DOOR,
    EC_HEADLESS_SCENARIO_FIELD_MOVE_CUT,
    EC_HEADLESS_SCENARIO_FIELD_MOVE_ROCK_SMASH,
    EC_HEADLESS_SCENARIO_FIELD_MOVE_STRENGTH,
    EC_HEADLESS_SCENARIO_FLIGHT_BEACON,
};

enum EmeraldChampionsHeadlessPokedexState
{
    EC_HEADLESS_POKEDEX_LIST,
    EC_HEADLESS_POKEDEX_INFO,
    EC_HEADLESS_POKEDEX_AREA,
    EC_HEADLESS_POKEDEX_STATS,
    EC_HEADLESS_POKEDEX_EVOLUTIONS,
    EC_HEADLESS_POKEDEX_FORMS,
    EC_HEADLESS_POKEDEX_CRY,
    EC_HEADLESS_POKEDEX_SIZE,
    EC_HEADLESS_POKEDEX_SEARCH,
    EC_HEADLESS_POKEDEX_SEARCH_RESULTS,
};

enum EmeraldChampionsHeadlessSummaryState
{
    EC_HEADLESS_SUMMARY_INFO,
    EC_HEADLESS_SUMMARY_SKILLS,
    EC_HEADLESS_SUMMARY_BATTLE_MOVES,
    EC_HEADLESS_SUMMARY_CONTEST_MOVES,
    EC_HEADLESS_SUMMARY_MOVE_DETAILS,
    EC_HEADLESS_SUMMARY_PARTY_ROUNDTRIP,
};

enum EmeraldChampionsHeadlessFurfrouTrimState
{
    EC_HEADLESS_FURFROU_TRIMS_OPEN,
    EC_HEADLESS_FURFROU_TRIMS_SCROLLED,
    EC_HEADLESS_FURFROU_TRIMS_B_CANCELLED,
    EC_HEADLESS_FURFROU_TRIMS_BACK_SELECTED,
};

#if EC_HEADLESS_FIXTURES
extern volatile u32 gEcHeadlessFixtureScenario;
extern volatile u32 gEcHeadlessFixtureActiveScenario;
extern volatile u32 gEcHeadlessFixtureSetupResult;
extern volatile u32 gEcHeadlessFixtureObservedResult;
extern volatile u32 gEcHeadlessFixtureParam;
extern volatile u32 gEcHeadlessFixtureTrigger;
void CB2_EmeraldChampionsHeadlessFixture(void);
void EmeraldChampionsHeadlessObserve(void);
#endif

#endif // GUARD_EMERALD_CHAMPIONS_HEADLESS_H
