#ifndef GUARD_EMERALD_CHAMPIONS_HEADLESS_H
#define GUARD_EMERALD_CHAMPIONS_HEADLESS_H

#include "global.h"

enum EmeraldChampionsHeadlessScenario
{
    EC_HEADLESS_SCENARIO_NONE,
    EC_HEADLESS_SCENARIO_CENTER_OLDALE,
    EC_HEADLESS_SCENARIO_CENTER_LAVARIDGE,
    EC_HEADLESS_SCENARIO_ABILITY_MENU,
    EC_HEADLESS_SCENARIO_OPTIONS,
    EC_HEADLESS_SCENARIO_BATTLE_VENDOR,
    EC_HEADLESS_SCENARIO_MOVE_SPECIALIST,
    EC_HEADLESS_SCENARIO_THUNDURUS,
    EC_HEADLESS_SCENARIO_TORNADUS,
    EC_HEADLESS_SCENARIO_LANDORUS,
    EC_HEADLESS_SCENARIO_GAME_CORNER,
    EC_HEADLESS_SCENARIO_CIRCUIT_LOBBY,
    EC_HEADLESS_SCENARIO_LEVELER,
    EC_HEADLESS_SCENARIO_ALL_LEGAL_MOVES,
    EC_HEADLESS_SCENARIO_ALL_LEGAL_MOVES_MEW,
    EC_HEADLESS_SCENARIO_WILD_ACTION_MENU,
    EC_HEADLESS_SCENARIO_MOVE_DETAILS,
    EC_HEADLESS_SCENARIO_MOVE_SPECIALIST_CURRENT_SET,
    EC_HEADLESS_SCENARIO_NAMING,
    EC_HEADLESS_SCENARIO_STORAGE,
    EC_HEADLESS_SCENARIO_STARTER_REGIONS,
    EC_HEADLESS_SCENARIO_CIRCUIT_ROOM,
    EC_HEADLESS_SCENARIO_MOVE_ANIMATION,
    EC_HEADLESS_SCENARIO_POKEDEX,
    EC_HEADLESS_SCENARIO_SUMMARY,
    EC_HEADLESS_SCENARIO_BAG,
    EC_HEADLESS_SCENARIO_FRONTIER_PASS,
    EC_HEADLESS_SCENARIO_EMBER_PATH_WARDEN,
    EC_HEADLESS_SCENARIO_SPECIES_OVERWORLD,
    EC_HEADLESS_SCENARIO_DOUBLE_STATUS_ABILITY,
    EC_HEADLESS_SCENARIO_MEGA,
    EC_HEADLESS_SCENARIO_PRIMALS,
    EC_HEADLESS_SCENARIO_SAFARI,
    EC_HEADLESS_SCENARIO_TITLE,
    EC_HEADLESS_SCENARIO_BIRCH,
    EC_HEADLESS_SCENARIO_POKEBLOCK,
    EC_HEADLESS_SCENARIO_TRAINER_CARD,
    EC_HEADLESS_SCENARIO_DOME_INFO,
    EC_HEADLESS_SCENARIO_CONTEST_RESULTS,
    EC_HEADLESS_SCENARIO_SLOT_MACHINE,
    EC_HEADLESS_SCENARIO_FAIRY_SUMMARY,
    EC_HEADLESS_SCENARIO_SPECIES_OVERWORLD_BACKGROUND,
    EC_HEADLESS_SCENARIO_MAGMA_SPARKLE,
    EC_HEADLESS_SCENARIO_FURFROU_TRIMS,
    EC_HEADLESS_SCENARIO_HEAL_LOCATION_WHITEOUT,
    EC_HEADLESS_SCENARIO_HALL_OF_FAME_RECORD,
    EC_HEADLESS_SCENARIO_MULTI_CORRIDOR_DOOR,
    EC_HEADLESS_SCENARIO_FIELD_MOVE_CUT,
    EC_HEADLESS_SCENARIO_FIELD_MOVE_ROCK_SMASH,
    EC_HEADLESS_SCENARIO_FIELD_MOVE_STRENGTH,
    EC_HEADLESS_SCENARIO_FLIGHT_BEACON,
    EC_HEADLESS_SCENARIO_WILD_FOE_TYPES,
    EC_HEADLESS_SCENARIO_MOVE_FOE_TYPES,
    EC_HEADLESS_SCENARIO_HM_REPLACEMENT,
    EC_HEADLESS_SCENARIO_DEWFORD_GYM_ENTRY,
    EC_HEADLESS_SCENARIO_START_MENU_FULL,
    EC_HEADLESS_SCENARIO_MAP_SWEEP,
    EC_HEADLESS_SCENARIO_BATTLE_SET_LONG_LIST,
    EC_HEADLESS_SCENARIO_CAMPAIGN_AUTOWIN,
    EC_HEADLESS_SCENARIO_CAPTURE_TO_PARTY,
    EC_HEADLESS_SCENARIO_CAPTURE_TO_PC,
    EC_HEADLESS_SCENARIO_CAPTURE_QUEST_DIANCIE,
    EC_HEADLESS_SCENARIO_CAPTURE_QUEST_REGISTEEL,
    EC_HEADLESS_SCENARIO_CAPTURE_QUEST_LATIOS,
    EC_HEADLESS_SCENARIO_CAPTURE_ORDINARY_FIRST,
    EC_HEADLESS_SCENARIO_ROXANNE_VICTORY,
    EC_HEADLESS_SCENARIO_FIRST_CENTER_ACQUISITION,
};

enum EmeraldChampionsHeadlessBattleSetListState
{
    EC_HEADLESS_BATTLE_SET_LIST_TOP,
    EC_HEADLESS_BATTLE_SET_LIST_MIDDLE,
    EC_HEADLESS_BATTLE_SET_LIST_BOTTOM,
};

enum EmeraldChampionsHeadlessCampaignQuery
{
    EC_HEADLESS_CAMPAIGN_QUERY_NONE,
    EC_HEADLESS_CAMPAIGN_QUERY_FLAG,
    EC_HEADLESS_CAMPAIGN_QUERY_VAR,
    EC_HEADLESS_CAMPAIGN_QUERY_OBJECT,
};

enum EmeraldChampionsHeadlessBattleResolution
{
    EC_HEADLESS_BATTLE_NATIVE,
    EC_HEADLESS_BATTLE_WIN,
    EC_HEADLESS_BATTLE_CAPTURE,
};

enum EmeraldChampionsHeadlessPokedexState
{
    EC_HEADLESS_POKEDEX_LIST,
    EC_HEADLESS_POKEDEX_INFO,
    EC_HEADLESS_POKEDEX_AREA,
    EC_HEADLESS_POKEDEX_STATS,
    EC_HEADLESS_POKEDEX_EVOLUTIONS,
    EC_HEADLESS_POKEDEX_FORMS,
    EC_HEADLESS_POKEDEX_CRY,
    EC_HEADLESS_POKEDEX_SIZE,
    EC_HEADLESS_POKEDEX_SEARCH,
    EC_HEADLESS_POKEDEX_SEARCH_RESULTS,
};

enum EmeraldChampionsHeadlessSummaryState
{
    EC_HEADLESS_SUMMARY_INFO,
    EC_HEADLESS_SUMMARY_SKILLS,
    EC_HEADLESS_SUMMARY_BATTLE_MOVES,
    EC_HEADLESS_SUMMARY_CONTEST_MOVES,
    EC_HEADLESS_SUMMARY_MOVE_DETAILS,
    EC_HEADLESS_SUMMARY_PARTY_ROUNDTRIP,
};

enum EmeraldChampionsHeadlessFurfrouTrimState
{
    EC_HEADLESS_FURFROU_TRIMS_OPEN,
    EC_HEADLESS_FURFROU_TRIMS_SCROLLED,
    EC_HEADLESS_FURFROU_TRIMS_B_CANCELLED,
    EC_HEADLESS_FURFROU_TRIMS_BACK_SELECTED,
};

#if EC_HEADLESS_FIXTURES
extern volatile u32 gEcHeadlessFixtureScenario;
extern volatile u32 gEcHeadlessFixtureActiveScenario;
extern volatile u32 gEcHeadlessFixtureSetupResult;
extern volatile u32 gEcHeadlessFixtureObservedResult;
extern volatile u32 gEcHeadlessFixtureParam;
extern volatile u32 gEcHeadlessFixtureTrigger;
extern volatile u32 gEcHeadlessCampaignBattleSerial;
extern volatile u32 gEcHeadlessCampaignLastBattleType;
extern volatile u32 gEcHeadlessCampaignLastOpponentA;
extern volatile u32 gEcHeadlessCampaignLastOpponentB;
extern volatile u32 gEcHeadlessCampaignMapId;
extern volatile u32 gEcHeadlessCampaignMapGroup;
extern volatile u32 gEcHeadlessCampaignMapNum;
extern volatile u32 gEcHeadlessCampaignPlayerX;
extern volatile u32 gEcHeadlessCampaignPlayerY;
extern volatile u32 gEcHeadlessCampaignPlayerFacing;
extern volatile u32 gEcHeadlessCampaignControlsLocked;
extern volatile u32 gEcHeadlessCampaignScriptEnabled;
extern volatile u32 gEcHeadlessCampaignInBattle;
extern volatile u32 gEcHeadlessCampaignQueryKind;
extern volatile u32 gEcHeadlessCampaignQueryId;
extern volatile u32 gEcHeadlessCampaignQueryValue;
extern volatile u32 gEcHeadlessCampaignQueryObjectActive;
extern volatile u32 gEcHeadlessCampaignQueryObjectX;
extern volatile u32 gEcHeadlessCampaignQueryObjectY;
extern volatile u32 gEcHeadlessCampaignCaptureSerial;
extern volatile u32 gEcHeadlessCampaignLastCapturedSpecies;
extern volatile u32 gEcHeadlessCampaignLastCaptureResult;
extern volatile u32 gEcHeadlessCampaignCaptureBookkeepingValid;
extern volatile u32 gEcHeadlessCampaignLastResolution;
bool32 EmeraldChampionsHeadlessBattleAutomationActive(void);
bool32 EmeraldChampionsHeadlessAutoCaptureActive(void);
enum EmeraldChampionsHeadlessBattleResolution EmeraldChampionsHeadlessGetBattleResolution(void);
void EmeraldChampionsHeadlessBeginAutoCapture(void);
void EmeraldChampionsHeadlessRecordCapture(enum Species species, u32 result);
void CB2_EmeraldChampionsHeadlessFixture(void);
void EmeraldChampionsHeadlessObserve(void);
#endif

#endif // GUARD_EMERALD_CHAMPIONS_HEADLESS_H
