// Reviewed camera positions for every physical one-off overworld Pokémon.
//
// This is deliberately a macro table: the test-only ROM consumes the map and
// camera coordinates, while the host renderer consumes the stable row/species
// names. The native UI gate independently derives the authoritative object set
// from live map.json files and requires an exact one-to-one match.

EC_HEADLESS_OVERWORLD_FIXTURE( 1, MAP_ALTERING_CAVE_1F,                    SPECIES_HOOPA,       6, 11)
EC_HEADLESS_OVERWORLD_FIXTURE( 2, MAP_ALTERING_CAVE_B1F,                   SPECIES_MEWTWO,      7, 15)
EC_HEADLESS_OVERWORLD_FIXTURE( 3, MAP_ASHEN_WOODS,                         SPECIES_OKIDOGI,     21, 37)
EC_HEADLESS_OVERWORLD_FIXTURE( 4, MAP_CAVE_OF_ORIGIN_DIANCIES_ROOM,        SPECIES_DIANCIE,      9, 11)
EC_HEADLESS_OVERWORLD_FIXTURE( 5, MAP_CAVE_OF_ORIGIN_DIANCIES_ROOM,        SPECIES_TERAPAGOS,     8, 12)
EC_HEADLESS_OVERWORLD_FIXTURE( 6, MAP_DEWFORD_MANOR_1F,                    SPECIES_MELOETTA,      8, 10)
EC_HEADLESS_OVERWORLD_FIXTURE( 7, MAP_DEWFORD_MANOR_1F,                    SPECIES_MUNKIDORI,     13, 11)
EC_HEADLESS_OVERWORLD_FIXTURE( 8, MAP_EMBER_PATH,                          SPECIES_MOLTRES,      21, 17)
EC_HEADLESS_OVERWORLD_FIXTURE( 9, MAP_METEOR_FALLS_B1F_1R,                 SPECIES_DIALGA,       15, 20)
EC_HEADLESS_OVERWORLD_FIXTURE(10, MAP_METEOR_FALLS_B1F_2R,                 SPECIES_CRESSELIA,      5,  4)
EC_HEADLESS_OVERWORLD_FIXTURE(11, MAP_METEOR_FALLS_JIRACHIS_ROOM,          SPECIES_JIRACHI,        7,  9)
EC_HEADLESS_OVERWORLD_FIXTURE(12, MAP_METEOR_FALLS_JIRACHIS_ROOM,          SPECIES_COSMOG,         4,  9)
EC_HEADLESS_OVERWORLD_FIXTURE(13, MAP_MT_PYRE_6F,                          SPECIES_PECHARUNT,      11,  8)
EC_HEADLESS_OVERWORLD_FIXTURE(14, MAP_MT_PYRE_SUMMIT,                      SPECIES_DARKRAI,        23, 13)
EC_HEADLESS_OVERWORLD_FIXTURE(15, MAP_NEW_MAUVILLE_INSIDE,                 SPECIES_ZAPDOS,         33, 18)
EC_HEADLESS_OVERWORLD_FIXTURE(16, MAP_NEW_MAUVILLE_INSIDE,                 SPECIES_MELTAN,         34,  7)
EC_HEADLESS_OVERWORLD_FIXTURE(17, MAP_PETALBURG_WOODS_2,                   SPECIES_VIRIZION,       39,  6)
EC_HEADLESS_OVERWORLD_FIXTURE(18, MAP_PETALBURG_WOODS_2,                   SPECIES_WO_CHIEN,         5,  7)
EC_HEADLESS_OVERWORLD_FIXTURE(19, MAP_PETALBURG_WOODS_3,                   SPECIES_CELEBI,          42, 41)
EC_HEADLESS_OVERWORLD_FIXTURE(20, MAP_ROUTE110,                            SPECIES_THUNDURUS,        6, 16)
EC_HEADLESS_OVERWORLD_FIXTURE(21, MAP_ROUTE111_RUINS_EXTERIOR,             SPECIES_LANDORUS,         9, 13)
EC_HEADLESS_OVERWORLD_FIXTURE(22, MAP_ROUTE119,                            SPECIES_TORNADUS,         29, 11)
EC_HEADLESS_OVERWORLD_FIXTURE(23, MAP_RUSTBORO_CITY_DEVON_CORP_2F,         SPECIES_MAGEARNA,         11,  8)
EC_HEADLESS_OVERWORLD_FIXTURE(24, MAP_SANDSTREWN_RUINS_B1F,                SPECIES_ZYGARDE,          31,  6)
EC_HEADLESS_OVERWORLD_FIXTURE(25, MAP_SCORCHED_SLAB_B2F,                   SPECIES_RESHIRAM,         10,  5)
EC_HEADLESS_OVERWORLD_FIXTURE(26, MAP_SCORCHED_SLAB_HEATRANS_ROOM,         SPECIES_HEATRAN,          10, 15)
EC_HEADLESS_OVERWORLD_FIXTURE(27, MAP_SEALED_CHAMBER_INNER_ROOM,           SPECIES_REGIGIGAS,        13, 12)
EC_HEADLESS_OVERWORLD_FIXTURE(28, MAP_SEASPRAY_CAVE_B1F,                   SPECIES_PALKIA,           36,  7)
EC_HEADLESS_OVERWORLD_FIXTURE(29, MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM,        SPECIES_ARTICUNO,          8,  5)
EC_HEADLESS_OVERWORLD_FIXTURE(30, MAP_VERDANTURF_MEADOW,                   SPECIES_SHAYMIN,           10, 11)
EC_HEADLESS_OVERWORLD_FIXTURE(31, MAP_VERDANTURF_MEADOW,                   SPECIES_ENAMORUS,           7, 12)
EC_HEADLESS_OVERWORLD_FIXTURE(32, MAP_VERDANTURF_MEADOW,                   SPECIES_FEZANDIPITI,       10, 12)
