from pathlib import Path
import json,re,struct
W=Path(__file__).resolve().parents[1];S=W.parent/'baseline/source';I=json.loads((W/'script-index.json').read_text());P=[]
def t(label,text=None,behavior=None):
 b=I[label];r={'source':b['path'],'label':label,'line':b['line'],'current':b['text'] or '\n'.join(b['code'])}
 if text is not None:r['replacement_text']=text
 if behavior:r['final_behavior']=behavior
 return r
def add(id,title,why,targets,deps=(),tests=(),disposition='REPAIR'):P.append({'id':id,'title':title,'disposition':disposition,'assessment':why,'targets':targets,'dependencies':list(deps),'acceptance':list(tests)})
add('W-INTRO-GEOMETRY','Show both rescue opponents without breaking the opening choreography','INTRO-01 introduces a scripted two-starter rescue against Poochyena and Zigzagoon. The new field actor must match that battle while preserving the existing approach tracks and access to Birch’s bag.',[
 {'source':'data/maps/Route101/map.json','label':'new LOCALID_ROUTE101_POOCHYENA','new_event':True,'current':'The snapshot rescue has Birch(9,13 template), Zigzagoon(10,13 template), bag(7,14), two player triggers(10/11,19); the scene repositions its moving actors before the chase.','final_object':{'local_id':'LOCALID_ROUTE101_POOCHYENA','graphics_id':'OBJ_EVENT_GFX_POOCHYENA','x':6,'y':14,'elevation':3,'movement_type':'MOVEMENT_TYPE_FACE_UP','movement_range_x':0,'movement_range_y':0,'trainer_type':'TRAINER_TYPE_NONE','trainer_sight_or_berry_tree_id':'0','script':'0','flag':'FLAG_HIDE_ROUTE_101_BIRCH_ZIGZAGOON_BATTLE'},'final_behavior':'Append the local object ID; reuse Birch’s rescue visibility lifecycle and do not add a second permanent hide flag.'},
 t('Route101_EventScript_StartBirchRescue',behavior='Keep existing player/Birch/Zigzagoon movement and synchronization. After their circle chase and final facing movements have completed, move LOCALID_ROUTE101_POOCHYENA one ordinary step up from(6,14) to(6,13), then face left; wait for its movement. At rest Birch is(4,13), Zigzagoon(5,13), Poochyena(6,13). The bag remains(7,14). INTRO-01 supplies the two-ball help line and battle selection.'),
 {'source':'data/maps/Route101/scripts.inc','label':'Route101_Movement_PoochyenaCloseIn','new_label':True,'final_behavior':'walk_up\nface_left\nstep_end'},
 t('Route101_EventScript_BirchsBag',behavior='Apply INTRO-01 selection/battle state. Remove both LOCALID_ROUTE101_ZIGZAGOON and LOCALID_ROUTE101_POOCHYENA during the post-win fade before moving the player to(6,13). Hide the rescue actor group only after the agreed legitimate rescue success. Cancellation and loss retain both field foes and a reachable bag. On a loss returning to the field, relocate the player while faded/locked to(7,15), face up, before restoring foes at(5,13)/(6,13) and Birch at(4,13); retain VAR_ROUTE101_STATE=2. Only then fade in and release. The standby tile is passable elevation3, directly south of the bag and contains no trigger or other object.'),
],['INTRO-01 authored by early battle volume; ordinary wild/static captures remain singles'],['Source geometry: both newactor cells are passable collision0/elevation3; the initial cell is off the chase track; the final cell is used only after the chase completes; bag is adjacent. Runtime: enter from each trigger(10,19)/(11,19); observe whole chase, approach bag from south/east, cancel starterchoice, lose/retry, win, and revisit. Confirm no actor overlap, blocked bag, duplicated Pokémon, or premature flags.'],disposition='REVISE')
add('W-FRONTIER-ANCILLARY','Align remaining active NPC services with Circuit','Some retained lobby NPCs and record surfaces still offer rules or forecasts for unavailable facility modes. Keep their historical context while removing actionable misinformation.',[
 t('BattleFrontier_BattlePyramidLobby_EventScript_HintGiver',behavior='Replace dynamic GetBattlePyramidHint forecast with a single current observer message below. Do not pretend the retired random-maze floor forecast describes the next Circuit opponent.'),
 {'source':'data/maps/BattleFrontier_BattlePyramidLobby/scripts.inc','label':'BattleFrontier_BattlePyramidLobby_Text_CircuitObserver','new_label':True,'replacement_text':"I once read the PYRAMID's omens.\\pThe CIRCUIT asks a different\nquestion: how will your team\nanswer the board before it?\\pA prediction helps. A sound\nfallback helps even more."},
 t('BattleFrontier_BattleArenaLobby_Text_OrderOfMonsImportant',"Your first two Pokémon begin\nthe Circuit battle together.\\pMake the opening pair support\none another, and keep useful\nanswers in reserve."),
 t('BattleFrontier_BattleArenaLobby_Text_LandingHitsWorked',"I kept finding safe chances\nto land my attacks.\\pThat won my last Circuit match!"),
 t('BattleFrontier_BattleArenaLobby_Text_MatchWasDeclaredDraw',"The old ARENA judged a match\nafter three turns.\\pThe CIRCUIT lets a longer plan\nplay out. You still have to\nsurvive those first turns."),
 t('BattleFrontier_BattleArenaLobby_Text_BadIdeaToNotAttack',"I protected every turn and\nnever built a winning position.\\pNext time, my defensive choices\nneed to create an opportunity."),
 t('BattleFrontier_OutsideWest_Text_ChooseFishingOverBattling',"I came to fish instead of battle.\\pI'll try the water and see\nwhat bites. A good partner\ncan be its own reward."),
 t('BattleFrontier_Lounge2_EventScript_FrontierManiac',behavior='Keep greeting and personality, replace old ShowFrontierManiacMessage selection with current Circuit observer text below. Do not recommend an unoffered singles/rental/Palace mode.'),
 {'source':'data/maps/BattleFrontier_Lounge2/scripts.inc','label':'BattleFrontier_Lounge2_Text_CurrentCircuitNews','new_label':True,'replacement_text':"Here's the latest: every desk\nenters the CHAMPIONS CIRCUIT!\\pDifferent buildings, one central\narena, and plenty of different\nteams to argue about."},
],['W-CIRCUIT-RULES; preserved architecture and archived records'],['Talk to every listed resident and invoke HintGiver repeatedly; no retired-mode forecast or challenge is advertised. Fishing statement remains neutral regardless of exact acquisition-table placement.'])
add('W-EREADER-NATIVE-RETIRE','Keep legacy houses while retiring unsupported native trainer battles','The live Sootopolis visitor path chooses three Pokémon and starts SPECIAL_BATTLE_EREADER. The Mossdeep RS Mystery Event door exposes a similar legacy route. No native trainer singles is the explicit final rule.',[
 t('SootopolisCity_MysteryEventsHouse_1F_EventScript_OldMan',behavior='Replace active visitor challenge dispatch with a harmless conversation pointing to the League/Frontier. Do not call SavePlayerParty, ChooseHalfPartyForBattle, ReducePlayerPartyToSelectedMons or warp to the battle basement. Preserve stored e-Reader team data.'),
 t('SootopolisCity_MysteryEventsHouse_1F_OnTransition',behavior='Keep the normal house layout and ordinary old-man placement. Do not open the basement based on imported visitor validity. Preserve IDs and data. An already saved legacy in-progress basement session must restore its saved player party and return safely to the 1F entrance without starting another battle; do not alter its recorded historical result.'),
 t('SootopolisCity_MysteryEventsHouse_B1F_OnFrame',behavior='Replace native battle-start entry with recovery-only handling when reached from a pre-revision in-progress save: restore original saved party if its backup is valid, reset only the retired session state, and return to1F(3,1). Never construct an e-Reader opponent or fabricate a battle outcome.'),
 {'source':'data/maps/SootopolisCity_MysteryEventsHouse_1F/scripts.inc','label':'SootopolisCity_MysteryEventsHouse_1F_Text_CurrentBattles','new_label':True,'replacement_text':"I still enjoy a fine Pokémon\nbattle. These old visitor records\nbring back good memories.\\pFor a new challenge, seek the\nLeague or the Frontier's\nCHAMPIONS CIRCUIT."},
 t('RS_MysteryEventsHouse_EventScript_Door',behavior='Retain the locked-door flavor; do not expose an imported trainer challenge through this native home. Preserve externally stored data and the harmless minigame record displays in Mossdeep.'),
],['No native trainer singles; shared save/party-restoration integrity; external link-format decisions owned centrally'],['New game and imported-record save: neither house starts a trainer battle. A valid existing legacy in-progress save restores the original party and exits; invalid backup is surfaced as an integrity failure, never overwritten. Records/minigame viewing and harmless residents remain usable.'])
# Record boards: current read-only API is owned centrally. Local roots are exact and exhaustive.
raw=json.loads((W/'inventory.raw.json').read_text());rr=[]
for m in raw['maps']:
 if not m['name'].startswith('BattleFrontier'):continue
 for e in m['events']:
  lab=e.get('root') or ''
  if lab in I and any(v in lab for v in ['ShowSinglesResults','ShowDoublesResults','ShowMultisResults','ShowLinkMultisResults','ShowPrevTourneyTree','ShowResults','TowerSinglesRecords','TowerDoublesRecords','TowerMultisRecords','TowerLinkRecords','ArenaRecords','PalaceRecords','FactoryRecords','DomeRecords','PikeRecords','PyramidRecords']):
   if any(v['label']==lab for v in rr):continue
   rr.append(t(lab,behavior='Replace body with: special ChampionsCircuitBufferRecord; msgbox BattleFrontier_BattleTowerLobby_Text_CurrentCircuitRecord, MSGBOX_SIGN; end. FAC-03 binds STR_VAR_1 to current VAR_CHAMPIONS_CIRCUIT_CURRENT_WINS, STR_VAR_2 to Best recorded VAR_EC_CIRCUIT_BEST_WINS (display -- when no observed record), STR_VAR_3 to lifetime VAR_CHAMPIONS_CIRCUIT_TOTAL_WINS. Five decimal digits must fit. Viewing never mutates state; retained old facility record data does not become a live challenge.'))
rr.append({'source':'data/maps/BattleFrontier_BattleTowerLobby/scripts.inc','label':'BattleFrontier_BattleTowerLobby_Text_CurrentCircuitRecord','new_label':True,'replacement_text':'CHAMPIONS CIRCUIT\\pCurrent run: {STR_VAR_1}\\pBest recorded: {STR_VAR_2}\\pTotal wins: {STR_VAR_3}'})
rr += [t('BattleFrontier_RankingHall_Text_ExplainRankingHall',"This hall celebrates the\nFrontier's competitive history.\\pToday's boards show CHAMPIONS\nCIRCUIT results: the current run,\nbest recorded run, and total wins."),t('BattleFrontier_RankingHall_Text_DomePikeFactoryRecords',"CHAMPIONS CIRCUIT RECORDS\nCurrent run, best recorded, total wins"),t('BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords',"CHAMPIONS CIRCUIT RECORDS\nCurrent run, best recorded, total wins")]
add('W-CIRCUIT-RECORDS','Show actual Circuit progress on current record boards','Existing monitors read retired mode counters. A current standard competition needs records tied to the same state that governs its results and entitlements, without a second scoreboard state.',rr,['FAC-03: CURRENT_WINS0x40DB, TOTAL_WINS0x40DC, proposed BEST_WINS0x40E3; initialize best only from observed currentrun, never infer historical best from lifetime. Legacy record data preserved'],['After Circuit wins, withdrawal, loss and reload, each current board matches the same authoritative counters. Tent/Hill wins do not change these values. Viewing any record cannot claim rewards, alter streaks or start a battle.'])
# Geometry evidence for the opening actors.
paths={}
for lab,start in [('Route101_Movement_BirchRunAway1',(0,15)),('Route101_Movement_ZigzagoonChase1',(0,16)),('Route101_Movement_BirchRunInCircles',(4,13)),('Route101_Movement_ZigzagoonChaseInCircles',(4,14))]:
 x,y=start;cells=[(x,y)]
 for line in I[lab]['code']:
  match=re.fullmatch(r'walk_fast_(up|down|left|right)',line)
  if match:
   dx,dy={'up':(0,-1),'down':(0,1),'left':(-1,0),'right':(1,0)}[match[1]];x+=dx;y+=dy;cells.append((x,y))
 paths[lab]={'start':start,'end':(x,y),'visited_cells':cells}
(S/'data/maps/Route101/map.json').exists()
(W/'opening-geometry.json').write_text(json.dumps({'scope':'Discrete source movement endpoints, not rendered or runtime collision proof','paths':paths,'new_actor_initial':[6,14],'new_actor_rest':[6,13],'bag':[7,14],'player_trigger_starts':[[10,19],[11,19]],'player_rest':[[10,15],[11,15]],'after_win_player':[6,13]},indent=2)+'\n')
(W/'proposals.supplement.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n');print('Supplement',len(P),'targets',sum(len(x['targets']) for x in P))
