from pathlib import Path
import json,re,hashlib
W=Path(__file__).resolve().parents[1];S=W.parent/'baseline/source';I=json.loads((W/'script-index.json').read_text());P=[]
def t(label,text=None,behavior=None):
 b=I[label];v={'source':b['path'],'label':label,'line':b['line'],'current':b['text'] or '\n'.join(b['code'])}
 if text is not None:v['replacement_text']=text
 if behavior:v['final_behavior']=behavior
 return v
def add(id,title,why,targets,deps=(),tests=(),status='REVISE'):
 P.append({'id':id,'title':title,'assessment':why,'disposition':status,'targets':targets,'dependencies':list(deps),'acceptance':list(tests)})
rooms={'EnterSpeedRoom':'MULTIHIT ROOM','EnterAccuracyRoom':'RETALIATION ROOM','EnterConfusionRoom':'TRICK ROOM','EnterDefenseRoom':'STATUS ROOM','EnterRecoveryRoom':'ENDURANCE ROOM','EnterStrengthRoom':'POWER ROOM','EnterOHKORoom':'BURST ROOM'}
roomtargets=[t('PetalburgCity_Gym_Text_'+k,'"'+v+'", the sign says.\\pDo you want to go through?') for k,v in rooms.items()]
roomtargets += [
 t('PetalburgCity_Gym_Text_GymGuideAdvice',"Welcome, CHAMPION-bound {PLAYER}!\\pDefeat the Trainers in a room\nto open its onward doors.\\pThe left door leads to the\nMULTIHIT ROOM. The right leads\nto the RETALIATION ROOM.\\pEach room's sign names its plan.\nChoose your route and prepare\nyour partners together."),
 t('PetalburgCity_Gym_Text_MaryPostBattle',"More formidable teams await.\\pThe left door leads to the\nSTATUS ROOM; the right leads\nto the ENDURANCE ROOM."),
 t('PetalburgCity_Gym_Text_RandallPostBattle',"Another challenge waits ahead.\\pThe left door leads to the\nTRICK ROOM; the right leads\nto the STATUS ROOM."),
 t('PetalburgCity_Gym_Text_ParkerPostBattle',"The next door leads to the\nPOWER ROOM.\\pKeep your team ready for it!"),
 t('PetalburgCity_Gym_Text_AlexiaPostBattle',"You've given me something\nto think about.\\pThe left door leads to the\nPOWER ROOM; the right leads\nto the BURST ROOM."),
 t('PetalburgCity_Gym_Text_GeorgePostBattle',"That was well played.\\pThe next door leads to the\nBURST ROOM. Be ready for\nits concentrated pressure."),
]
add('W-PETALBURG-ROOMS','Make Norman’s room names describe the inspected teams','The preserved teams no longer match the old Accuracy/Confusion/Defense names. Berke already has a Burst door but neighbors still direct players to One-hit KO. Names are coordinated with the early battle reviewer; maps, routes, identifiers, unlocking rules and geometry stay intact.',roomtargets,['Early battle volume: Randall MULTIHIT, Mary RETALIATION, Parker TRICK, Alexia STATUS, George ENDURANCE, Jody POWER, Berke BURST; intro paragraphs owned there'],['Walk both branching routes and compare each door name to its destination and neighbor directions. Defeating a room still opens exactly its existing onward doors. No encounter is added or removed.'])
wallace_code='''lock\nfaceplayer\ngoto_if_unset FLAG_SYS_GAME_CLEAR, CaveOfOrigin_DianciesRoom_EventScript_WallaceNotReady\ngoto_if_defeated TRAINER_WALLACE_DOUBLES_LEGENDS, CaveOfOrigin_DianciesRoom_EventScript_WallaceAfter\nmsgbox CaveOfOrigin_DianciesRoom_Text_WallaceOffer, MSGBOX_YESNO\ngoto_if_eq VAR_RESULT, NO, CaveOfOrigin_DianciesRoom_EventScript_WallaceDecline\ncall EventScript_CheckStoryDoubleBattleParty\ntrainerbattle_double TRAINER_WALLACE_DOUBLES_LEGENDS, CaveOfOrigin_DianciesRoom_Text_WallaceIntro, CaveOfOrigin_DianciesRoom_Text_WallaceDefeat, EmeraldChampions_Text_NeedTwoPokemon\ngoto CaveOfOrigin_DianciesRoom_EventScript_WallaceAfter'''
add('W-WALLACE-ROOT','Restore the authored Wallace exhibition as an optional chamber encounter','The complete E0510 team/script remains authored but has no object/coordinate/background entry. Restore this one named authored exhibition deliberately; do not revive every retired script.',[
 {'source':'data/maps/CaveOfOrigin_DianciesRoom/map.json','label':'new LOCALID_EC_WALLACE_EXHIBITION','new_event':True,'current':'Only Diancie at (9,9) and Diancite at (7,9) are present.','final_object':{'local_id':'LOCALID_EC_WALLACE_EXHIBITION','graphics_id':'OBJ_EVENT_GFX_WALLACE','x':11,'y':10,'elevation':3,'movement_type':'MOVEMENT_TYPE_FACE_LEFT','movement_range_x':0,'movement_range_y':0,'trainer_type':'TRAINER_TYPE_NONE','trainer_sight_or_berry_tree_id':'0','script':'CaveOfOrigin_DianciesRoom_EventScript_WallaceExhibition','flag':'0'},'final_behavior':'Wallace is visible whenever this chamber is reachable. Before game clear he declines. After game clear, interaction offers the existing one-time exhibition. He never auto-approaches or blocks Diancie, its stone, or the north exit. Preserve current map-local IDs and append the new ID.'},
 t('CaveOfOrigin_DianciesRoom_EventScript_WallaceExhibition',behavior=wallace_code),
 t('CaveOfOrigin_DianciesRoom_EventScript_WallaceReward',behavior='Retire the duplicate Diancite handoff path. After a legitimate win, go directly to WallaceAfter; retain the trainer defeated flag. The chamber pickup remains the Diancite acquisition owner.'),
 t('CaveOfOrigin_DianciesRoom_Text_WallaceAfter',"The chamber has heard two\nChampions answer one another.\\pThe DIANCITE beside its guardian\nbelongs to your exploration.\nOur battle was its own reward."),
 {'source':'data/maps/CaveOfOrigin_DianciesRoom/scripts.inc','label':'CaveOfOrigin_DianciesRoom_Text_WallaceOffer','new_label':True,'replacement_text':"Would you face my unrestricted\nrain exhibition here?\\pThe chamber's guardian and its\nstone will wait while we battle."},
 {'source':'data/maps/CaveOfOrigin_DianciesRoom/scripts.inc','label':'CaveOfOrigin_DianciesRoom_EventScript_WallaceDecline','new_label':True,'final_behavior':'msgbox CaveOfOrigin_DianciesRoom_Text_WallaceDecline, MSGBOX_DEFAULT; release; end'},
 {'source':'data/maps/CaveOfOrigin_DianciesRoom/scripts.inc','label':'CaveOfOrigin_DianciesRoom_Text_WallaceDecline','new_label':True,'replacement_text':"Whenever your team is ready.\nI will be here."},
],['E0510 final team and defeat prose owned by late battle volume; Diancite world pickup; no native trainer singles'],['Map.bin tile (11,10) is passable elevation3 in snapshot; render and walk around Wallace from each reachable side. Test pre-clear, decline, insufficient usable party, loss/Retry, first win, and revisit. Diancie remains independently interactable and Diancite is not reissued by battle.'],status='REPAIR')
add('W-TRICK-REWARDS','Make all Trick House reward retries preserve their earned contents','Puzzle4 changes its prize on the full-Bag route. Final puzzle8 collapses tent and Alakazite failures into one flag, while the entrance retries only the tent. Preserve both authored final rewards and support each independently.',[
 t('Route110_TrickHouseEntrance_EventScript_GivePuzzle4Reward',behavior='Change only giveitem ITEM_SMOKE_BALL to giveitem ITEM_KINGS_ROCK. Preserve result branches and the remaining stage rewards.'),
 t('Route110_TrickHouseEnd_EventScript_CompletedPuzzle8',behavior='Keep final story, chosen RED/BLUE TENT, Alakazite, departure and level advancement. Add separate receipt flags FLAG_EC_TRICK_FINAL_TENT_RECEIVED and FLAG_EC_TRICK_FINAL_ALAKAZITE_RECEIVED. A successful givedecoration sets only tent receipt; a successful giveitem sets only Alakazite receipt. Failure of either leaves that receipt false. At level8 both are owed until individually received; VAR_TRICK_HOUSE_PRIZE_PICKUP becomes1 whenever either receipt is false,0 only when both true. Completing one must not clear the other. Share this claim operation with the entrance courier; do not replay puzzle8 to claim a pending part.'),
 t('Route110_TrickHouseEntrance_EventScript_MechadollReward',behavior='Offer the tent choice only if its receipt is false, and Alakazite only if its receipt is false. After each insertion, mark only the successful part received. Keep the mechadoll visible whenever anything remains pending. When both receipts are true, clear PRIZE_PICKUP, retain LEVEL=8, and use the existing departure effect exactly once. Do not issue another tent just because Alakazite failed.'),
 t('Route110_TrickHouseEntrance_OnTransition',behavior='Before existing final-prize visibility selection, run one-time receipt initialization guarded by new FLAG_EC_TRICK_FINAL_STATE_INITIALIZED. If LEVEL<8, initialize marker only. For an old completed LEVEL>=8 and PRIZE_PICKUP=0, mark both receipts received. For old LEVEL>=8 and PRIZE_PICKUP=1, mark a tent received only if RED/BLUE TENT ownership is recorded (including placed decorations); mark Alakazite received if already in Bag, item PC or on any party/PC Pokémon. Otherwise preserve that part as a one-time claim. Then set the initialization marker and derive final PRIZE_PICKUP from the two receipts. Never reset puzzle progress, catches, other Mega flags or owned decorations. The old one-bit state cannot prove which reward was lost after disposal; record that migration limitation openly.'),
 {'source':'include/constants/flags.h','label':'new symbolic Trick House receipt flags','new_label':True,'final_behavior':'Use the central reservations in appendices/state-allocation.md and review/state-allocations.json: FLAG_EC_TRICK_FINAL_TENT_RECEIVED=0x2B2, FLAG_EC_TRICK_FINAL_ALAKAZITE_RECEIVED=0x2B3, FLAG_EC_TRICK_FINAL_STATE_INITIALIZED=0x2B4. They replace declaration-only unused flags. The single version4 migration initializes them once, then reconstructs legacy final-prize state; later loads never clear the initializer or receipts. Recheck live-source collisions before applying these reserved addresses.'},
 {'source':'data/maps/Route110_TrickHouseEntrance/scripts.inc','label':'Route110_TrickHouseEntrance_Text_FinalRewardsPending','new_label':True,'replacement_text':"YOUR FINAL REWARDS ARE RECORDED.\\pTHE TENT AND ALAKAZITE ARE\nSEPARATE GIFTS. MAKE ROOM FOR\nANY PART STILL WAITING HERE."},
],['Mega reward catalogue; persistent flag allocation; existing Alakazite Granite Cave alternate preserved'],['For stages1–7 compare immediate and pending item IDs; puzzle4 always King’s Rock. For stage8 exercise all four tent/stone insertion success combinations, reload/revisit, claim one part at a time, and verify no duplication. Test old completed saves with no pending state, tent-only ownership, stone-only ownership, both, neither; preserve unrelated inventory and puzzle flags.'],status='REPAIR')
quiz=[
 ('Which move guards your side against opposing priority moves?',['PROTECT','WIDE GUARD','QUICK GUARD'],2,'src/battle_util.c:5915'),
 ('Which type normally ignores RAGE POWDER when choosing a target?',['GRASS','NORMAL','ROCK'],0,'src/battle_util.c; powder/redirection target checks'),
 ('Which move normally hits both opponents instead of being redirected by FOLLOW ME?',['ROCK SLIDE','THUNDERBOLT','CLOSE COMBAT'],0,'src/data/moves_info.h; MOVE_ROCK_SLIDE target flags; redirection in src/battle_util.c'),
 ('TRICK ROOM reverses Speed order within which boundary?',['The whole turn','Each priority bracket','Only one side'],1,'src/battle_main.c:GetWhoStrikesFirst / Trick Room comparisons'),
 ('When can a Pokémon normally use FAKE OUT successfully?',['Only at full HP','After every Protect','First turn after entry'],2,'data/battle_scripts_1.s:BattleScript_EffectFirstTurnOnly; first-turn counter'),
 ('TAUNT prevents the target from choosing which moves?',['Non-damaging moves','All special attacks','All priority moves'],0,'src/battle_util.c:CheckMoveLimitations; tauntTimer'),
 ('Which status reduces physical damage for most attackers?',['BURN','POISON','SLEEP'],0,'src/battle_util.c physical damage modifier and Guts exception'),
 ('Which move boosts an ally’s attack damage for the current turn?',['REFLECT','SAFEGUARD','HELPING HAND'],2,'src/data/moves_info.h:MOVE_HELPING_HAND; damage modifier'),
 ('Which Pokémon can receive EVIOLITE’s defensive benefit?',['One with no evolution','One that can still evolve','Any below level 50'],1,'src/battle_util.c:7291; CanSpeciesEvolve'),
 ('Which held item can remove TAUNT from its holder?',['MENTAL HERB','POWER HERB','WHITE HERB'],0,'src/battle_script_commands.c:902; mental-herb status handling'),
 ('Which Ability redirects single-target WATER moves?',['STORM DRAIN','WATER ABSORB','RAIN DISH'],0,'src/battle_util.c:2358 and redirection handling'),
 ('Which opposing target does PSYCHIC TERRAIN protect from FAKE OUT?',['An airborne target','A grounded target','Every target'],1,'src/battle_util.c:IsBattlerGrounded; Psychic Terrain priority protection'),
 ('You switch out while TRICK ROOM is active. What happens to the room’s timer?',['It ends immediately','It keeps running','It starts over'],1,'src/battle_main.c and field timer update; no switch reset'),
 ('Which move guards your side against most damaging moves that hit multiple targets?',['SAFEGUARD','QUICK GUARD','WIDE GUARD'],2,'src/battle_util.c:5896'),
 ('PRANKSTER-boosted TAUNT normally fails against an opposing Pokémon of which type?',['DARK','DRAGON','PSYCHIC'],0,'src/battle_util.c:9458; B_PRANKSTER_DARK_TYPES'),
]
qt=[]
for ix,(question,choices,correct,evidence) in enumerate(quiz):
 doll=ix//3+1;q=ix%3+1; label=f'Route110_TrickHousePuzzle5_Text_Mechadoll{doll}Quiz{q}';script=f'Route110_TrickHousePuzzle5_EventScript_Mechadoll{doll}Quiz{q}'
 z=t(label,f'MECHADOLL {doll} QUIZ.\\p'+question);z['choices']=choices;z['correct_index']=correct;z['menu_array']=f'MultichoiceList_Mechadoll{doll}_Q{q}';z['menu_source']='src/data/script_menu.h';z['script_label']=script;z['evidence']=evidence;qt.append(z)
add('W-TRICK-QUIZ','Reauthor all fifteen quiz questions against actual battle rules','The current random quiz bank asks obsolete wild-table, prior-team, price and NPC-count questions. Retain five dolls, three randomly chosen questions per doll, movement/incorrect-answer reset and reward topology, with a complete stable doubles question bank. This optional puzzle is not a campaign training curriculum.',qt,['Configured battle mechanics; current move/ability/item behavior; W-TRICK-REWARDS'],['Update all15 menu arrays and matching correct-answer cases together. Exercise one correct and each incorrect choice per question through the script path, with mechanical claims checked against production behavior. Keep any future mechanic change tied to its affected question instead of a historical prose lock.'],status='REPAIR')
# Precise tent presentation; root owns FAC-01 execution API.
for city,flavor in [('SlateportCity','The port brings together teams\nfrom every shore.'),('VerdanturfTown','Bring a team that supports each\npartner through a hard match.'),('FallarborTown','Our challengers bring ideas from\nthe mountains and far beyond.')]:
 pre=city+'_BattleTentLobby';add('W-TENT-'+city.upper(),'Present '+city.replace('City','').replace('Town','')+' as a local doubles exhibition','FAC-01 supersedes native legacy Factory/Palace/Arena battle rules. Preserve the location, local residents and unrelated gift, and make the actual competition format explicit.',[
 t(pre+'_EventScript_Attendant',behavior='Replace the legacy challenge entry with FAC-01 local exhibition entry. First settle any existing pending '+city.replace('City','').replace('Town','').lower()+'TentPrize using its existing commit-on-success contract. Offer rules and participation; call the shared local exhibition API only after eligibility and affirmative choice. It performs battle in this lobby and returns here. Three exhibition victories earn exactly one prize from the existing local pool; no Circuit counters, legendary entitlements or legacy rental/Palace/Arena mode advances.'),
 t(pre+'_EventScript_RulesBoard',behavior='Display the new ExhibitionRules text below as a sign and end. Remove the old scrolling headings for rentals, swaps, autonomous Nature choice, Arena judging, level30 and three-Pokémon teams.'),
 {'source':f'data/maps/{pre}/scripts.inc','label':pre+'_Text_ExhibitionWelcome','new_label':True,'replacement_text':flavor+'\\pThis is a six-Pokémon doubles\nexhibition. You command every\nmove and switch.\\pYour team uses the current cap.\nDifficulty sets opponent levels.\nEnter with six healthy partners?'},
 {'source':f'data/maps/{pre}/scripts.inc','label':pre+'_Text_ExhibitionRules','new_label':True,'replacement_text':"LOCAL DOUBLES EXHIBITIONS\\pBring six healthy Pokémon,\nwith no Eggs. Prepare freely\nbefore entering.\\pThree victories earn one local\nprize. Your party is restored\nafter each exhibition.\\pThese results are separate from\nthe CHAMPIONS CIRCUIT. You\nreturn to this lobby afterward."},
],['FAC-01; DIFF-01; existing src/battle_tent.c local prize pool'],['Enter with5/6 and withEgg/faintedmember; decline cleanly; win three times, lose, withdraw, reload and fillBagbeforeprize. Preserve held items/moves/levels/HP and pendingprize transaction; never warp to Frontier. Confirm no change to Circuit lifetime/best/rewardstate.'])
add('W-TENT-FLAVOR','Remove obsolete rental and autonomous-move claims from live tent residents','Native tent mechanics change under FAC-01. Their NPCs need to talk about the actual exhibitions rather than an unoffered ruleset.',[
 t('SlateportCity_BattleTentLobby_Text_CouldntFindMonForMe',"I couldn't settle on a team.\nToo many interesting choices!\\pThen I found this PRISM SCALE.\nMaybe you can put it to use."),
 t('SlateportCity_BattleTentLobby_Text_BattleEvenWithoutToughMons',"The CENTER can prepare any legal\nset for free. Bring your own six\nand test them here."),
 t('SlateportCity_BattleTentLobby_Text_NiceIfMoreSelection',"A new opponent every match!\nI keep leaving with another\nidea for my team."),
 t('VerdanturfTown_BattleTentLobby_Text_MonsReluctantToUseDislikedMoves',"Natures change stats, not which\nmoves your Pokémon will obey.\\pYou command both partners here.\nA quiet Pokémon can have a\nvery aggressive battle set."),
 t('FallarborTown_BattleTentLobby_Text_FallarborTentMyFavorite',"The tents share the same serious\ndoubles competition.\\pFALLARBOR is my favorite place\nto visit between exhibitions."),
],['FAC-01'],['Talk to all three lobbies’ residents after entering an exhibition; no resident promises rental selection, autonomous commands, three-turn judging or a different native format.'])
# Shared Circuit rules root and current facilities guidance.
ctext="CHAMPIONS CIRCUIT\\pBring six healthy Pokémon and\nno Eggs. Every match is doubles;\nyou control your own team.\\pYour team battles at Lv. 100.\nOpponent levels begin from your\ndifficulty and rise with wins.\\pAfter each battle, your party\nand held items are restored.\nYou can leave between matches.\\pEvery Frontier desk registers\nyou for the central Tower arena.\nMilestone rewards remain recorded."
boards=[]
for name in ['Tower','Dome','Palace','Pyramid','Arena','Factory','Pike']:
 lab=f'BattleFrontier_Battle{name}Lobby_EventScript_RulesBoard'
 boards.append(t(lab,behavior='Replace the old mode-selection help with: msgbox BattleFrontier_BattleTowerLobby_Text_CurrentCircuitRules, MSGBOX_SIGN; end. This is information only and never starts a battle.'))
boards.append({'source':'data/maps/BattleFrontier_BattleTowerLobby/scripts.inc','label':'BattleFrontier_BattleTowerLobby_Text_CurrentCircuitRules','new_label':True,'replacement_text':ctext})
boards += [t('BattleFrontier_BattleTowerLobby_Text_CanLeaveUntilLossOrSevenWins',"The CIRCUIT restores your team\nafter each match.\\pYou may continue or leave then.\nA strong run deserves another\nwell-prepared decision."),t('BattleFrontier_BattleTowerLobby_Text_CircuitWelcome',"Welcome to the CHAMPIONS CIRCUIT!\\pEvery match is a full-team Double\nBattle with a competitive opponent.\\pYour team battles at Lv. 100.\nOpponents grow stronger as your\nrun continues, up to Lv. 255.\\pEvery Frontier desk registers you\nfor the central Tower arena.")]
add('W-CIRCUIT-RULES','Give every active Frontier rules board one truthful contract','All current desks enter Circuit, but all seven legacy rule boards remain live and advertise incompatible old formats. Replace those interaction roots; keep their historical underlying labels inert for archival source compatibility.',boards,['Shared Circuit API; DIFF-01; all native trainer battles doubles'],['Read every active lobby rules board and every desk. None offers singles, three-Pokémon teams, rentals, autonomous player move choice, Arena judging or seven-win forced lock-in. Confirm actual central-room route and between-match withdrawal.'],status='REPAIR')
rec=[]
for name,where in [('BattleTower','the great tower'),('BattleDome','the oval building'),('BattlePalace','the red building to the east'),('BattleArena','the central dojo'),('BattleFactory','the building nearest this gate'),('BattlePike','the SEVIPER-shaped building'),('BattlePyramid','the enormous pyramid')]:
 lab='BattleFrontier_ReceptionGate_Text_'+name+'Info'
 rec.append(t(lab,f'The {name.replace("Battle","BATTLE ").upper()} is {where}.\\pIts reception desk enters the\nCHAMPIONS CIRCUIT at the central\nTower arena. All matches are doubles.'))
rec += [
 t('BattleFrontier_ReceptionGate_EventScript_RulesGuide',behavior='Show BattleFrontier_BattleTowerLobby_Text_CurrentCircuitRules with MSGBOX_NPC and end; retire old Level50/Open/duplicate-item/rental-entry menu from native interaction.'),
 t('BattleFrontier_ReceptionGate_Text_ScottGreatToSeeYouHere',"SCOTT: It's great to see you here!\\pEvery desk enters the CHAMPIONS\nCIRCUIT. Six partners, coordinated\nopponents, and no easy matches.\\pThe buildings preserve the\nFrontier's history. The Tower\nholds our central arena.\\pVisit my house when you have time.\nI'd like to hear about your teams."),
 t('BattleFrontier_ReceptionGate_Text_RankingHallInfo',"The RANKING HALL is near\nthe BATTLE TOWER.\\pIts current displays show your\nCHAMPIONS CIRCUIT run, best\nrecorded run, and total wins."),
 t('BattleFrontier_ReceptionGate_EventScript_FrontierPassGuide',behavior='Keep Pass acquisition/ownership. Replace the old symbol/recording submenu with an accurate current Pass explanation: it retains the Trainer Card, Battle Points and historical symbol records. Current Circuit records are displayed at current record boards; do not claim old symbols are earned from Circuit unless another explicit chapter authorizes it.'),
 t('BattleFrontier_ScottsHouse_Text_HaveYouMetFrontierBrain',"SCOTT: The FRONTIER BRAINS gave\nthese buildings their character.\\pToday every desk enters the\nCHAMPIONS CIRCUIT. I want to see\nwhat your team can do there!"),
]
add('W-FRONTIER-GUIDES','Reconcile the reception tour and Scott with the current competition','Reception still claims the other buildings preserve classic challenges, while their actual desks were replaced. Keep architecture and character history; describe current services exactly.',rec,['W-CIRCUIT-RULES; Circuit record display; historic earned-symbol rewards remain stored'],['Read each reception menu choice, initial Scott scene and later Scott random comments. They all describe the same active Circuit. Historical symbol flags and already earned Scott gifts remain retrievable without creating new claims.'],status='REPAIR')
# Short, exact replacements for current residents whose claims conflict with Circuit.
f={
'BattleFrontier_OutsideWest_Text_SureWeCanChallengeWithNoMons':"Hey, bro... We need six Pokémon\nfor the CIRCUIT.\\pLet's visit the CENTER and\nfinish our team first.",
'BattleFrontier_OutsideWest_Text_BigGuySaidIllLendYouMons':"That big fellow showed me how\nto prepare a set at the CENTER.\\pHe said the team still needs\nto be ours. Fair enough!",
'BattleFrontier_OutsideWest_Text_WhosRaisingThoseRentalMons':"That's the BATTLE FACTORY. Its\ndesk also enters the CIRCUIT.\\pWho prepares all those opposing\nteams? I'd like to compare notes!",
'BattleFrontier_OutsideWest_Text_KeepBattlingUntilIGetSymbol':"I'm going to keep battling until\nI beat my best Circuit streak!",
'BattleFrontier_OutsideWest_Text_WonIllTakePikeChallenge':"I won! I'll register at the PIKE\nand start another Circuit run!",
'BattleFrontier_OutsideWest_Text_LostIllPutOffPikeChallenge':"I lost. Maybe that's my cue to\nreview my team before the CIRCUIT.",
'BattleFrontier_OutsideWest_Text_BattlePikeSign':"BATTLE PIKE\\pCHAMPIONS CIRCUIT RECEPTION\nCentral arena: BATTLE TOWER",
'BattleFrontier_OutsideEast_Text_PyramidTooHarsh':"The CIRCUIT is too harsh!\nI keep losing at the same point.\\pMaybe I should change my plan\ninstead of climbing this pyramid.",
'BattleFrontier_OutsideEast_Text_ThriveInDarkness':"I thrive in darkness...\\pA quiet pyramid, a difficult\nteam to build, and nobody\ninterrupting my thoughts...",
'BattleFrontier_OutsideEast_Text_PeopleCallMeBusybody':"People call me a busybody.\nI keep spotting something to fix!\\pThat habit helps in doubles.\nThere are two sides of the\nboard to watch at once.",
'BattleFrontier_OutsideEast_Text_PowerOfOurLoveWillOvercome':"Let's sit down and build a team\ntogether, darling!\\pSix partners that support one\nanother. Then we can each see\nhow far our plan goes!",
'BattleFrontier_OutsideEast_Text_BattlePyramidSign':"BATTLE PYRAMID\\pCHAMPIONS CIRCUIT RECEPTION\nCentral arena: BATTLE TOWER",
'BattleFrontier_BattleDomeLobby_Text_NeedToCheckOpponentCarefully':"I committed my best answer too\nearly and lost it.\\pA reserve is valuable only if\nyou preserve the chance to use it.",
'BattleFrontier_BattleDomeLobby_Text_WinnersGainReputation':"The DOME built its reputation\non great tournament battles.\\pNow its desk enters the CIRCUIT.\nKeep winning, and people\nremember your team!",
'BattleFrontier_BattleDomeLobby_Text_TrashedInFirstRound':"My very first Circuit opponent\nbroke through my opening.\\pI need a stronger answer\nfrom the first turn.",
'BattleFrontier_BattleDomeLobby_Text_LastWinnerWasTough':"These monitors preserve the\nDOME's old tournaments.\\pToday's Circuit records are\nmarked separately. A different\nchallenge, the same ambition!",
'BattleFrontier_BattlePalaceLobby_Text_WhatNatureFavorsChippingAway':"A careful Nature and Stat Point\nspread can help a partner\nsurvive the turn that matters.\\pThen I choose what it does\nwith that extra turn!",
'BattleFrontier_BattlePalaceLobby_Text_NatureAndMovesKeyHere':"The old Palace tested how\nPokémon acted on their own.\\pIn the CIRCUIT, you command\nevery move. Natures change\nstats, not obedience.",
'BattleFrontier_BattleFactoryLobby_Text_NeedKnowledgeOfMonsMoves':"Don't judge an opposing Pokémon\nby its reputation alone.\\pLook at the board and what its\npartner makes possible. That's\nhow the CIRCUIT keeps surprising me.",
'BattleFrontier_BattleFactoryLobby_Text_SwappedForWeakMon':"I changed one member of my team\nand lost the support another\npartner depended on.\\pThe new Pokémon wasn't weak.\nMy combination was incomplete.",
'BattleFrontier_BattleFactoryLobby_Text_CantFigureOutStaffHints':"A name tells you which Pokémon\nyou're facing. It doesn't tell\nyou every choice it can make.\\pI keep that in mind when the\nCIRCUIT introduces an opponent.",
'BattleFrontier_BattlePikeLobby_Text_OneRoomAwayFromGoal':"One more victory would have\nbeaten my Circuit record.\\pA status move stopped me.\nI left that answer out of my team.",
'BattleFrontier_BattlePikeLobby_Text_NeverHadToBattleTrainer':"I used to get lucky in the PIKE.\\pThe CIRCUIT makes you face\na complete opposing team\nevery match. I like that.",
'BattleFrontier_BattlePyramidLobby_Text_TrainersNoticeRunning':"The old PYRAMID was a maze.\nNow I study the CIRCUIT here.\\pIts opponents can punish a\ncareless switch just as quickly\nas a careless attack.",
'BattleFrontier_BattlePyramidLobby_Text_LostLotOfItems':"I used to worry about losing\nitems in the old PYRAMID.\\pThe CIRCUIT restores my team\nand held items after each match.\nI can focus on the battle.",
'BattleFrontier_PokemonCenter_1F_Text_GoingThroughEveryChallenge':"I'm bringing SKITTY on my\nnext Circuit team!\\pFive partners will help this\nlittle one find its chance.",
'BattleFrontier_Mart_Text_FacilitiesDontAllowItems':"Trainer battles here don't allow\nitems from the BAG.\\pPrepare held items before entering\nthe CHAMPIONS CIRCUIT.",
}
add('W-FRONTIER-RESIDENTS','Keep local personality while removing unavailable-service promises','The outdoor residents and active lobby NPCs still describe rentals, maze goals, autonomous move choice and classic-symbol ambitions that the live Circuit does not supply. These complete replacements preserve individual attitudes and the buildings’ history.',[t(k,v) for k,v in f.items()],['W-CIRCUIT-RULES; preserved legacy maps/records'],['Read each changed NPC/sign from its real map position. All current-service claims match the Circuit entry, restoration and withdrawal behavior. No new battle or reward is introduced.'],status='REPAIR')
# Two duplicate paid services become the existing free specialist/vendor.
services=[]
for side in ['Left','Right']:
 services.append(t(f'BattleFrontier_Lounge7_EventScript_{side}MoveTutor',behavior=f'Keep a brief {side.lower()} veteran greeting (new text below), close it, then goto Common_EventScript_EmeraldChampionsMoveTutor. Remove this live path to paid BP tutor selection and debit. Existing free legality/selection/cancel behavior is the owner; no second learnset table.'))
 services.append({'source':'data/maps/BattleFrontier_Lounge7/scripts.inc','label':f'BattleFrontier_Lounge7_Text_{side}TutorFree','new_label':True,'replacement_text':('Buhahaha! I still know a thing\nor two about beautiful moves.' if side=='Left' else 'Ihihihi! Experience makes every\nmove worth another look.')+'\\pThe lessons are free now.\nLet us prepare your team.'})
services.append(t('BattleFrontier_ExchangeServiceCorner_EventScript_EvolutionClerk',behavior='Explain that the evolution archive is free with the Mega Ring, then goto Common_EventScript_EmeraldChampionsBattleVendor. Do not take Battle Points for ordinary evolution items. Keep decoration and field-supply BP counters unchanged.'))
services.append(t('BattleFrontier_ExchangeServiceCorner_Text_ItemsWillGetMonTougher',"I save Battle Points for supplies\nand decorations.\\pOrdinary evolution items are free\nfrom CENTER vendors once you\nhave the MEGA RING."))
add('W-FREE-SERVICE-COHESION','Consolidate paid duplicate preparation into the existing free services','The native Frontier tutors still debit BP for moves available free elsewhere, and an evolution counter sells the free Ring archive. Keep the NPCs and their personality, with one owner for legal preparation.',services,['Shared Center specialist/vendor; unchanged decoration and field-supply economics'],['Talk to both veteran tutors and the evolution clerk. Perform a legal edit, cancel a selection, and request an unavailable move; Battle Points never change. Ordinary item/decor purchases retain their current debit-on-success checks.'],status='REPAIR')
add('W-GAMBLER-RETIRE','Retire bets on unavailable formats without losing recorded stakes','The gambler’s challenge selection and settlement are indexed to classic facility modes; Circuit does not complete those records. Retire new stakes and settle any existing obligation before ordinary flavor.',[
 t('BattleFrontier_Lounge3_EventScript_Gambler',behavior='Before all old introduction/gate branches, inspect VAR_FRONTIER_GAMBLER_STATE and AMOUNT_BET. WAITING/no placed wager: show new observer text and end, never debit BP. PLACED_BET: refund5/10/15 according to the existing validated amount enum. WON: pay the recorded10/20/30 owed by the old win. LOST: preserve the recorded result, clear only this resolved wager state, and show outcome text. For a refund/payment that would exceed MAX_BATTLE_FRONTIER_POINTS, leave the complete obligation pending and ask player to make room by spending BP; never clamp away the balance. Once the full exact amount is credited, set state WAITING and clear the obsolete selected wager; repeated interaction cannot pay again. Invalid historical amount/state is not authority to invent funds; show neutral unavailable-record text and preserve data for repair review.'),
 {'source':'data/maps/BattleFrontier_Lounge3/scripts.inc','label':'BattleFrontier_Lounge3_Text_CurrentObserver','new_label':True,'replacement_text':"I used to wager on the old\nFrontier events.\\pNow I watch the CIRCUIT and argue\nabout teams. It's cheaper...\nusually."},
 {'source':'data/maps/BattleFrontier_Lounge3/scripts.inc','label':'BattleFrontier_Lounge3_Text_SettlementPending','new_label':True,'replacement_text':"Your old wager is still recorded.\\pSpend a few Battle Points, then\nreturn. I will settle the full\namount without losing any of it."},
],['Existing VAR_FRONTIER_GAMBLER_STATE/AMOUNT_BET; MAX_BATTLE_FRONTIER_POINTS=9999'],['Test no wager, each placed stake, each recorded win, a recorded loss, cap-insufficient credit space and repeated visit/reload. Credits match the original obligation exactly; no new bets or Circuit milestones created.'],status='REPAIR')
(W/'proposals.systems.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n');print('System proposals',len(P),'targets',sum(len(v['targets']) for v in P))
