"""Author the world volume specification. Writes book artifacts only."""
from pathlib import Path
import json,re,textwrap,hashlib
W=Path(__file__).resolve().parents[1]; B=W.parent; S=B/'baseline/source'; I=json.loads((W/'script-index.json').read_text())
P=[]
def target(label,new_text=None,behavior=None):
 b=I[label];r={'source':b['path'],'label':label,'line':b['line'],'baseline_sha256':hashlib.sha256((S/b['path']).read_bytes()).hexdigest(),'current':b['text'] or '\n'.join(b['code'])}
 if new_text is not None:r['replacement_text']=new_text
 if behavior is not None:r['final_behavior']=behavior
 return r
def add(id,title,assessment,targets,dependencies=(),acceptance=(),disposition='REPAIR'):
 P.append({'id':id,'title':title,'disposition':disposition,'assessment':assessment,'targets':targets,'dependencies':list(dependencies),'acceptance':list(acceptance)})
add('W-SIGN-OPTIONAL','Remove live mandatory-Devon instructions','The acquisition definitions explicitly make Devon optional, but several live story handoffs still require a visit before every Sign. These are active interactions, unlike the unbound expansion-guide scripts cataloged separately.',[
 target('Route110_Text_MayExplainItemfinder',"MAY: That's a DOWSING MACHINE.\nIt reacts to hidden items.\\pDEVON's researcher has useful leads\nif you want help finding a SIGN.\\pI'm heading north to MAUVILLE!\nWATTSON's GYM is there. See you!"),
 target('GraniteCave_StevensRoom_Text_IveGotToHurryAlong',"I'm heading east. MAGMA and AQUA\nare disturbing more than land and sea.\\pInspect the marked stone in the\nlower cave. COBALION may answer\nonce you hold the STONE BADGE.\\pDEVON's researcher keeps optional\nclues. You can explore without him."),
 target('NewMauville_Inside_Text_RotomCaught',"The generator finally falls silent.\\pThe ROTOM CATALOG nearby changes\nROTOM into its five appliances.\\pInspect the plant's marked stone\nfor other unusual discoveries.\\pREGIELEKI responds to REGISTEEL.\nDEVON can explain that clue and\nthe conditions for the other SIGNS."),
 target('Route119_WeatherInstitute_2F_Text_PokemonChangesWithWeather',"CASTFORM changes with the weather.\nLet it show you what a storm can do.\\pInvestigate SIGNS as you explore.\nDEVON's researcher offers clues\nwhenever you want some guidance."),
 target('Route119_WeatherInstitute_2F_Text_ChangingWeatherRidiculous',"Our instruments still trace that\nold network beneath HOENN.\\pDEVON's lab has optional leads for\nthe SIGNS you want to investigate.\\pThe road north leads to FORTREE.\nYou're welcome to rest here."),
],['Acquisition Sign definitions; GUIDE-01'],['Read both rival variants and every listed first/repeat branch. Reach and activate a qualified landmark without ever speaking to Devon researcher; then read its completed clue afterward.'])
add('W-SIGN-LOCAL','Replace obsolete partner silhouettes with truthful local leads','Current Sign definitions removed most species prerequisites. Physical signs and live residents still name former required families. Keep clues exciting while making each specified badge or story condition match the snapshot acquisition owner.',[
 target('Route110_Text_MauvilleCitySign',"ROUTE 110\n{UP_ARROW} MAUVILLE CITY\\pA storm is carved into the stone.\nReturn with the DYNAMO BADGE\nand inspect the nearby landmark."),
 target('Route112_Text_MtChimneySign',"MT. CHIMNEY\\pFor LAVARIDGE TOWN or the summit,\nplease take the CABLE CAR.\\pA newer carving points to FIERY\nPATH. A fiery guardian may answer\na holder of the DYNAMO BADGE."),
 target('Route119_Text_WeatherInstitute',"WEATHER INSTITUTE\\pFIELD NOTE: Inspect this route's\nmarked stone with the BALANCE\nBADGE. A storm may answer."),
 target('Route120_Text_RouteSignFortree',"ROUTE 120\n{LEFT_ARROW} FORTREE CITY\\pA lakeside SIGN answers the\nBALANCE BADGE. Other marks await\na Champion who returns here."),
 target('Route123_Text_RouteSignMtPyre',"{UP_ARROW} MT. PYRE\nForbidden to the faint of heart.\\pA guardian's mark stands among\nthese fields. Return with the\nFEATHER BADGE and inspect it."),
 target('MossdeepCity_Text_LifeNeedsSeaToLive') if 'MossdeepCity_Text_LifeNeedsSeaToLive' in I else target('MossdeepCity_EventScript_ExpertM',behavior='Replace the single msgbox target with the W-SIGN-LOCAL expert text supplied below; preserve MSGBOX_NPC and end.'),
 target('PetalburgWoods_Text_TrainerTipsPP',"FOREST FIELD NOTES\\pCUT reveals paths into the\nold-growth forest.\\pOne SIGN answers the KNUCKLE\nBADGE. Deeper marks answer the\nHEAT BADGE. Inspect them yourself;\nDEVON offers clues if you want."),
 target('MeteorFalls_1F_2R_Text_NicolasPostBattle',"A mark here answers REGIROCK\nonce you hold the FEATHER BADGE.\\pOther SIGNS lie deeper in the\nFalls. Inspect them as you explore;\nDEVON keeps their conditions on file."),
 target('Route114_FossilManiacsTunnel_Text_NotSafeThatWay',"Oh... It's not safe that way...\\pI was digging when the wall fell\ninto an enormous cavern!\\pIt connects to SANDSTREWN RUINS.\nLook for ancient fossils and a\nmarked stone beneath the desert."),
 target('MtPyre_Summit_Text_GroudonKyogreTale',"Long ago, GROUDON raised the land\nand KYOGRE carved the sea. Their\nclash grew until neither could stop.\\pAncient Trainers formed a network\nof SIGNS with trusted POKéMON.\\pThe RED and BLUE ORBS joined it,\nbut RAYQUAZA supplied its balance.\\pThe mountain still bears other\nSIGNS. Inspect them yourself;\ntheir conditions differ."),
 target('MtPyre_Summit_Text_HoennTrioTale',"Land and sea became absolute,\nand HOENN began to break.\\pA green POKéMON descended from\nthe sky and answered your call.\\pRAYQUAZA restored the balance.\nYou gave it a reason to answer.\\pThe sixth floor holds another\nSIGN. Return there after earning\nthe title of Champion."),
],['src/data/pokemon/legendary_signs.h; GUIDE-01'],['Inspect the exact listed landmarks at just-below and just-at their conditions. Confirm none of the removed ordinary-family prerequisites is checked. Preserve current Cresselia/Darkrai/Regi/quest prerequisites that remain intentional.'])
# Replace ExpertM's actual text by resolving its msgbox, without relying on an assumed label name.
expert=I['MossdeepCity_EventScript_ExpertM']; explabel=re.search(r'msgbox\s+(\w+)',expert['body'])[1]
P[-1]['targets']=[t for t in P[-1]['targets'] if t['label']!='MossdeepCity_EventScript_ExpertM' and t['label']!=explabel]
P[-1]['targets'].append(target(explabel,"All life needs the sea, even when\nit makes its home on the land.\\pDivers found a princely SIGN near\nthe SEAFLOOR CAVERN approach.\\pInspect that underwater landmark\nwith the MIND BADGE. The stolen\nsubmarine points the way."))
add('W-MEGA-GUIDE','Make Mr. Stone describe the actual Mega economy','Mr. Stone promises a free Mega archive that no longer exists. The free archive contains evolution items; Mega Stones are world rewards.',[
 target('RustboroCity_DevonCorp_3F_Text_ExplainPidgeotite',"PIDGEOTITE lets a PIDGEOT Mega\nEvolve when it holds the stone\nand you possess a MEGA RING.\\pFind Mega Stones in HOENN's caves,\ngyms and side paths, or through\nthe people you meet.\\pCENTER vendors supply held items\nand ordinary evolution items\nfree of charge."),
 target('RustboroCity_DevonCorp_3F_Text_NotFamiliarWithTrends',"The old records call these marks\na network of CHAMPION'S SIGNS.\\pEach has its own conditions.\nSome answer a BADGE or a deed;\na few recognize another POKéMON.\\pOur researcher can explain them.\nHis guidance is entirely optional."),
],['World Mega reward catalogue'],['After obtaining Ring, read Mr. Stone repeat text and open a Center vendor: no Mega archive is offered; original world Mega routes remain unchanged.'])
add('W-OUTCOME-PROSE','Acknowledge wins without inventing their turn sequence','Scripted after-battle lines cannot know whether Tailwind occurred, a lead was read in one turn, or the player rebuilt a team. Level differences remain an intentional difficulty lever.',[
 target('Route104_Text_MayIntro',"MAY: {PLAYER}{KUN}! We've both found\nnew partners since ROUTE 103.\\pShow me how your team works!"),
 target('Route110_Text_MayTakeThis',"MAY: Your partners found an answer\nto mine. That was a good battle!\\pTake this. It finds what routes hide."),
 target('Route110_Text_BrendanTakeThis',"BRENDAN: A strong team, well played.\nYou earned that win.\\pHere. Take this."),
 target('MauvilleCity_Text_WallyDefeat') if 'MauvilleCity_Text_WallyDefeat' in I else target('MauvilleCity_EventScript_Wally',behavior='Use the resolved Wally defeat text target in W-OUTCOME-PROSE.'),
 target('Route119_Text_MayPresentForYou',"MAY: Your partners came through\nthat battle together.\\pHere. I have a present for you."),
 target('LilycoveCity_Text_MayDefeat',"MAY: I remember our first battle\non ROUTE 103.\\pYou keep finding ways through\nmy teams. I'll have to try again!"),
 target('LilycoveCity_Text_BrendanDefeat',"BRENDAN: You found a way through\nmy team. That stings.\\pI had a head start as a TRAINER...\nI'll have to make the next one count."),
],['INTRO-01; DIFF-01; individual battle dialogue volume'],['Read each branch after different valid wins, including letting the opponent establish its field and preserving a favorite team. No line asserts an unobserved move or exact turn.'])
# Resolve Wally's custom defeat label by baseline content.
wally=[k for k,b in I.items() if b['path']=='data/maps/MauvilleCity/scripts.inc' and 'My wind never came' in b.get('text','')]
P[-1]['targets']=[t for t in P[-1]['targets'] if t['label'] not in {'MauvilleCity_EventScript_Wally','MauvilleCity_Text_WallyDefeat'}]
for k in wally:P[-1]['targets'].append(target(k,"WALLY: ...\\pI had a plan for every partner.\nYou still found your way through.\\pI lost..."))
add('W-OPENING-TIPS','Align opening field advice with the final doubles opening','Opening services and roster are changed by INTRO-01. Existing lead-order advice describes a single lead and can mislead players building their first doubles pair.',[
 target('OldaleTown_House1_Text_LeftPokemonGoesOutFirst',"In a DOUBLE BATTLE, your first\ntwo Pokémon able to battle form\nyour opening pair.\\pChange their party order before\nyou challenge a Trainer. Those\ntwo partners set the opening."),
 target('Route104_Text_TrainerTipsDoubleBattles',"TRAINER TIPS\\pTrainer battles in HOENN are\nDOUBLE BATTLES. Prepare your\nfirst two partners together.\\pA good opening pair gives each\nPOKéMON room to do its job."),
 target('Route109_Text_TrainerTipsSign',"TRAINER TIPS\\pEvery partner has competitive\npotential. Battles do not award\nEVs to grind.\\pUse a CENTER specialist to set\nNature and STAT POINTS. Compare\nthe resulting stats before battle."),
 target('Route104_Text_RouteSignPetalburg',"ROUTE 104\n{RIGHT_ARROW} PETALBURG CITY"),
 target('Route104_Text_RouteSignRustboro',"ROUTE 104\n{UP_ARROW} RUSTBORO CITY"),
],['INTRO-01; DIFF-01; GUIDE-01'],['Check party lead selection with a fainted first slot and two healthy partners. Display both route signs with dynamic roster appendix and verify no obsolete Hidden roster appears.'])
add('W-FIELD-CLUES','Explain the existing HM license and compatible-party model','The source already requires a badge, the received HM license, and a party member capable of learning the technique. Several NPCs still imply that the battle moveset must contain the HM.',[
 target('RustboroCity_CuttersHouse_Text_ExplainCut',"That HM registers CUT as a field\ntechnique for your team.\\pWith the STONE BADGE, a party\nmember able to learn CUT can\nchop thin trees.\\pIt needn't keep CUT among its\nfour battle moves."),
 target('RusturfTunnel_Text_ExplainStrength',"That HM registers STRENGTH.\\pWith the HEAT BADGE, a party\nmember able to learn STRENGTH\ncan move large boulders.\\pIt needn't keep the move in its\nbattle set."),
 target('Route118_Text_CanCrossRiversWithSurf',"With SURF registered and the\nBALANCE BADGE, a compatible\nparty member can cross water.\\pIt doesn't need SURF in its\nbattle moveset. Partners can\nhelp in more ways than one!"),
 target('RustboroCity_Flat2_2F_Text_PokemonHoldFloatStone',"DEVON refines METAL COATS.\\pUse one from the BAG to evolve\nONIX or SCYTHER. No trade with\nanother player is required."),
 target('BattleFrontier_Lounge6_Text_PromiseIllBeGoodToIt',"Oh, it's adorable! Thank you!\nI promise I'll be good to it.\\pTYPE: NULL already has a battle\nset. Raise its friendship, then\nlevel it up to get SILVALLY.\\pA memory held by SILVALLY\nchanges its type."),
 target('RustboroCity_PokemonSchool_Text_ScottMetAlreadyCut',"SCOTT: We met in PETALBURG, didn't we?\nI'm looking for exceptional Trainers.\\pThe CUTTER nearby has the CUT HM.\nCollect it and the STONE BADGE.\\pThen a compatible party member can\nclear thin trees without keeping\nCUT in its battle moves."),
 target('SlateportCity_Harbor_Text_TeamAquaLeftNeedDive',"CAPT. STERN: AQUA left before you\ncould stop them... Don't blame yourself.\\pTo follow that submarine, you'll need\nDIVE registered, the MIND BADGE, and\na partner able to use the technique.\\pTravel to MOSSDEEP. Its divers and\nthe SPACE CENTER may be able to help."),
 target('SlateportCity_Harbor_Text_NeedDiveToCatchSub',"CAPT. STERN: To follow the submarine,\nyou'll need DIVE registered, the\nMIND BADGE, and a compatible partner.\\pVisit MOSSDEEP's SPACE CENTER and\nfind STEVEN. He may be able to help."),
],['Evolution/acquisition catalogue; PREP-02; src/field_move.c; src/data/pokemon/species_info/gen_7_families.h'],['Perform Cut/Strength/Surf with compatible species whose four moves omit the HM; test missing badge, missing license, and no compatible species independently. Level Type: Null at friendship threshold; memory changes Silvally rather than evolving Type: Null.'])
add('W-FIELD-SURF','Use actual traversal capability when deleting Surf','IsLastMonThatKnowsSurf in src/party_menu.c checks only learned moves and can block reclaiming a move slot despite the compatible-species fallback. Preserve the softlock safeguard with the same field capability model.',[
 {'source':'src/party_menu.c','label':'IsLastMonThatKnowsSurf','line':8604,'current':'Rejects the last known Surf when no storage Pokémon knows Surf and P_CAN_FORGET_HIDDEN_MOVE is false.','final_behavior':'For Hoenn, when the selected move is Surf and the HM+badge license is unlocked, evaluate the party as if that slot no longer knew Surf: any other non-Egg member that knows Surf or any non-Egg member (including the selected member) whose species can learn Surf supplies a safe field user. If one exists, return FALSE. Otherwise retain the existing last-Surf safeguard. PC selection remains freely deletable as before. Do not mutate moves while checking, toggle global P_CAN_FORGET_HIDDEN_MOVE, or bypass HM/badge gates.'},
 target('EmeraldChampions_EventScript_OpenMoveDeleter',behavior='KEEP this menu and its call to IsLastMonThatKnowsSurf; it receives corrected capability semantics.'),
 target('LilycoveCity_MoveDeletersHouse_EventScript_MoveDeleter',behavior='KEEP this native specialist and its call to IsLastMonThatKnowsSurf; it receives corrected capability semantics.'),
],['src/field_move.c:SpeciesCanLearnFieldMove and IsFieldMoveUnlocked'],['A Surf-compatible Pokémon can delete its only learned Surf and still use Surf in the field. A species that only acquired Surf through an exceptional move-copy route retains protection if deleting it removes the last usable carrier. Test both specialist interfaces and cancellation; no source/game changes executed in book phase.'])
add('W-CENTER-FIRST-VISIT','Complete the first nurse visit with healing','The first nurse visit gives four useful tools and returns after explanation without the ordinary healing branch. A first visit to a nurse should offer the same immediate recovery as subsequent visits.',[
 target('Common_EventScript_PkmnCenterNurse',behavior='Preserve all current item delivery and Bag-full retry branches. After the final ExplainTools message on first successful tool delivery, wait for its text and acknowledgment, then enter EventScript_PkmnCenterNurse_Main instead of returning. The ordinary Yes/No heal flow, vial refill, and pending legendary relic delivery execute exactly once if accepted. Do not repeat tool grants or suppress the first-visit explanation.'),
],['Shared nurse contract; INTRO-01'],['Enter any first Center with injured party. Finish tool handoff and accept healing in the same conversation; party and vial refill. Decline healing leaves items safely owned. Interrupt after each Bag-full delivery and return without duplication.'])
add('W-SPIRITOMB-01','Give the ship shrine a legible, thematic requirement','The active trash-can encounter silently requires Lickitung or Slugma as well as Odd Keystone. No map dialogue explains those species; ordinary Spiritomb routes already exist, so this is an optional thematic alternate.',[
 target('AbandonedShip_Room_B1F_EventScript_Spiritomb',behavior='Remove both checkspecies branches. Lock and check ITEM_ODD_KEYSTONE directly. Without it, show the new eerie receptacle clue below, release and end. With it, retain existing placement Yes/No, species construction, cry, encounter and outcome handling. Consume exactly one Keystone only after B_OUTCOME_CAUGHT. Losing, fleeing, defeating Spiritomb or declining keeps the Keystone and allows another attempt. Preserve ordinary wild Spiritomb routes.'),
 {'source':'data/maps/AbandonedShip_Room_B1F/scripts.inc','label':'AbandonedShip_Room_B1F_Text_KeystoneMissing','new_label':True,'replacement_text':"Cold air seeps from the old bin.\\pA cracked socket in its base\nlooks made for an ODD KEYSTONE."},
 target('AbandonedShip_Room_B1F_Text_PutKeystoneInTrash',"The ODD KEYSTONE fits the\ncracked socket in this old bin.\\pA whisper rises from the hull.\nSet the stone in place?"),
],['Ordinary Spiritomb and Odd Keystone acquisition entries; wild/static battles remain singles'],['Interact without either former required species. Missing Keystone gives clue; declined/fled/defeated battle retains it; successful catch removes one. No unrelated item, flag, party member or ordinary encounter route is changed.'])
add('W-STATUS-REFERENCE','Make optional status explanations accurate for doubles','These optional field references should describe the configured game without absolute claims that would mislead an expert player. They remain available from the opening, never a staged skill unlock.',[
 target('Route110_Text_TrainerTipsPrlzSleep',"TRAINER TIPS\\pParalysis usually lowers Speed\nand can interrupt a move.\\pSleep stops most moves until the\nPokémon wakes. Abilities and terrain\ncan change which plans work."),
 target('RustboroCity_PokemonSchool_Text_ExplainSleep',"Sleep prevents most moves until\nthe Pokémon wakes.\\pSLEEP TALK and SNORE are exceptions.\nA sleeping Pokémon stays asleep\nafter battle; AWAKENING cures it."),
 target('RustboroCity_PokemonSchool_Text_ExplainBurn',"A burn normally lowers damage from\nphysical attacks and causes HP loss.\\pSome Abilities change that result.\nGUTS attackers can benefit from burn!\\pBURN HEAL removes a burn outside\na trainer battle."),
 target('RustboroCity_PokemonSchool_Text_ExplainFreeze',"A frozen Pokémon usually cannot move.\nIt may thaw, and certain moves can\nhelp it thaw as well.\\pFreezing remains after battle.\nAn ICE HEAL removes it."),
],['Configured status mechanics and individual battle/AI volume'],['Verify each stated interaction against actual configured production mechanics, including Sleep Talk/Snore and Guts. Render every paragraph without clipping. No new mechanics or difficulty easing.'])

# Write base tranche. Later script adds facilities, quiz, rewards, and map ledger annotations.
(W/'proposals.core.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n')
print('Core proposals',len(P),'targets',sum(len(x['targets']) for x in P))
